CREATE OR REPLACE FORCE VIEW CABIODEV.GENE_ALIAS_OBJECT
(ID, GENE_ALIAS_ID, ALIAS_ID, NAME, GENE_ID, 
 ALIAS_TYPE)
AS 
select rownum, GENE_ALIAS_ID, ALIAS_ID, NAME, GENE_ID, ALIAS_TYPE  from ( 
SELECT to_number(-1 || to_char(GENE_ID)) GENE_ALIAS_ID, 
-1 ALIAS_ID, BC_ID NAME, GENE_ID, 'BioCarta' ALIAS_TYPE 
FROM BIOGENES 
UNION 
SELECT to_number(to_char(GENE_ID) || to_char(GENE_ID)) GENE_ALIAS_ID, 
GENE_ID ALIAS_ID, ALIAS NAME, GENE_ID, 'CGAP' ALIAS_TYPE 
FROM CGAP_GENE_ALIAS);


