CREATE OR REPLACE FORCE VIEW CABIODEV.CONTEXT_TYPE_VIEW
(TISSUE_NAME, HISTOLOGY_NAME, CONTEXT_CODE, TISSUE_CODE, HISTOLOGY_CODE)
AS 
SELECT tissue_name, histology_name, context_code, g.TISSUE_CODE, g.HISTOLOGY_CODE
FROM CONTEXT g, HISTOLOGY_CODE h, TISSUE_CODE t
WHERE g.TISSUE_CODE = t.TISSUE_CODE
AND g.HISTOLOGY_CODE = h.HISTOLOGY_CODE;


