CREATE OR REPLACE FORCE VIEW CABIODEV.LOC_TEMP
(GENE_ID, NID, SNP_ID, CHROMOSOME_ID)
AS 
SELECT GENE_ID, NUCLEIC_ACID_SEQUENCE_ID nid, SNP_ID, CHROMOSOME_ID 
FROM CYTOGENIC_LOCATION_CYTOBAND 
UNION all 
SELECT GENE_ID, NUCLEIC_ACID_ID nid, SNP_ID, CHROMOSOME_ID 
FROM PHYSICAL_LOCATION;


