CREATE OR REPLACE FORCE VIEW CABIODEV.REGELEMENT_PROMOTER_VIEW
(NAME, REGULATORYELEMENT_ID, REGULATORYELEMENTTYPE_ID, TAXON_ID, TRANSGENE_ID, 
 GENE_ID, PROMOTER_ID)
AS 
select REGULATORYELEMENT.NAME, REGULATORYELEMENT.REGULATORYELEMENT_ID, REGULATORYELEMENT.REGULATORYELEMENTTYPE_ID, REGULATORYELEMENT.TAXON_ID, REGULATORYELEMENT.TRANSGENE_ID,
       PROMOTER.GENE_ID, PROMOTER.PROMOTER_ID
from REGULATORYELEMENT, PROMOTER
where REGULATORYELEMENT.REGULATORYELEMENT_ID = PROMOTER.REGULATORYELEMENT_ID;


