<!-- Welcome Content include begins -->
The Molecular Annotation Service provides a set of interfaces for the annotation of experimental or other types of data with molecular information.  
Molecular annotations may include detailed information on:
<ul>
	<li>
	  Molecular entities (e.g. genes, proteins, chromosomes, etc.) and their properties
	</li><li>
	  Biological networks (cellular pathways) and molecular interactions
	</li><li>
      Molecular alterations (SNPs, etc.) which may be biomarkers of disease
	</li><li>
	  Relationships of all entities and interactions to disease and outcomes
	</li>
</ul>  
The purpose of Molecular Annotations service is to provide specifications for a set of molecular annotations that may be integrated with user-facing applications.  
The development of a common, reusable set of interfaces provided by this service will facilitate standardization, integration, and interoperability between various systems that provide and consume molecular annotations.
<br>
This service specification provides a key infrastructure component for the NCI's support of molecular annotations. 
This service serves as a main platform for integrating molecular annotations among all heterogeneous systems/components independent of platform within the life sciences domain.

<br>
<br>
<!-- Welcome Content include ends -->