
alter table ZSTG_INTERACTIONCOMPPTMTERMS enable constraint SYS_C0020857;
alter table ZSTG_INTERACTIONCOMPPTMTERMS enable constraint SYS_C0020858;
alter table ZSTG_INTERACTIONCOMPPTMTERMS enable constraint SYS_C0020859;
alter table ZSTG_INTERACTIONCOMPPTMTERMS enable constraint SYS_C0020860;
alter table ZSTG_INTERACTIONCOMPPTMTERMS enable constraint SYS_C0020861;
alter table ZSTG_INTERACTIONCOMPPTMTERMS enable constraint SYS_C0020862;
alter table ZSTG_INTERACTIONCOMPPTMTERMS enable constraint SYS_C0020863;

--EXIT;
