
alter table ZSTG_MOLECULECOMPONENTLABELS disable constraint SYS_C0020887;
alter table ZSTG_MOLECULECOMPONENTLABELS disable constraint SYS_C0020888;
alter table ZSTG_MOLECULECOMPONENTLABELS disable constraint SYS_C0020889;
alter table ZSTG_MOLECULECOMPONENTLABELS disable constraint SYS_C0020890;
alter table ZSTG_MOLECULECOMPONENTLABELS disable constraint SYS_C0020891;
alter table ZSTG_MOLECULECOMPONENTLABELS disable constraint SYS_C0020892;

--EXIT;
