
create index DISEASE_SHIP_ID on DISEASE_RELATIONSHIP(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DISEASE_SHIP_PARENT_ID on DISEASE_RELATIONSHIP(PARENT_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DISEASE_SHIP_CHILD_ID on DISEASE_RELATIONSHIP(CHILD_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DISEASE_SHIP_RELATIONSH on DISEASE_RELATIONSHIP(RELATIONSHIP) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
