
drop index EVIDENCIDENCE_BIG_ID_LWR;
drop index EVIDENCEENCE_SENTENCE_S_LWR;
drop index EVIDENCEENCE_CELLLINE_S_LWR;
drop index EVIDENCEENCE_NEGATION_S_LWR;
drop index EVIDENCEENCE_COMMENTS_LWR;
drop index EVID_SENT_LWR;
drop index EVID_SENT;
drop index EVIDENCIDENCE_BIG_ID;
drop index EVIDENCEENCE_ID;
drop index EVIDENCEENCE_SENTENCE_S;
drop index EVIDENCEENCE_CELLLINE_S;
drop index EVIDENCEENCE_COMMENTS;
drop index EVIDENCEENCE_NEGATION_S;
drop index EVIDENCEENCE_PUBMED_ID;
drop index SYS_IL0000052365C00007$$;

--EXIT;
