
drop index GENE_FUNTION_HISTOLOGYC;
drop index GENE_FUNTION_AGENT_ID;
drop index GENE_FUNTION_ROLE_ID;
drop index GENE_FUNTION_GENE_ID;
drop index GENE_FUNTION_DISCRIMINA_LWR;
drop index GENE_FUNTION_ROLE_ID_LWR;
drop index GENE_FUNCTION_ID;
drop index GENE_FUNTION_DISCRIMINA;
drop index GENE_FUNTION_EVIDENCE_I;

--EXIT;
