
drop index TARGETGET_BIG_ID_LWR;
drop index TARGETRGET_TARGET_TYP;
drop index TARGETRGET_TARGET_NAM;
drop index TARGETRGET_LOCUS_ID;
drop index TARGETRGET_TARGET_ID;
drop index TARGETRGET_TARGET_NAM_LWR;
drop index TARGETGET_BIG_ID;

--EXIT;
