
drop index TRANSCRIRIPT_PROBE_COUN_LWR;
drop index XSCRIPTBIGID;
drop index TRANSCRIRIPT_PROBE_COUN;
drop index TRANSCRIRIPT_STRAND;
drop index TRANSCRIRIPT_SOURCE;
drop index TRANSCRIRIPT_ID;
drop index TRANSCRIPT_MI_INDEX;
drop index TRANSCRANSCRIPT_BIG_ID_LWR;
drop index TRANSCRIRIPT_STRAND_LWR;
drop index TRANSCRIRIPT_SOURCE_LWR;
drop index TRANSCRIRIPT_MANUFACTUR_LWR;

--EXIT;
