
drop index ZSTG_PID_LOC_ORDER_OF_C_LWR;
drop index ZSTG_PID_LOC_LOCATION_LWR;
drop index ZSTG_PID_LOC_XREF_LWR;
drop index ZSTG_PID_LOC_COMPLEX_CO;
drop index ZSTG_PID_LOC_XREF;
drop index ZSTG_PID_LOC_ORDER_OF_C;
drop index ZSTG_PID_LOC_LOCATION;

--EXIT;
