
drop index ZSTG_EXORTER_STOP_LOCAT;
drop index ZSTG_EXORTER_STRAND;
drop index ZSTG_EXORTER_PROBE_COUN;
drop index ZSTG_EXORTER_MANUFACTUR;
drop index ZSTG_EXORTER_MICROARRAY;
drop index ZSTG_EXORTER_NAME;
drop index ZSTG_EXORTER_ID;
drop index ZSTG_EXTER_BIG_ID_LWR;
drop index ZSTG_EXORTER_EXON_ID;
drop index ZSTG_EXORTER_TRANSCRIPT;
drop index ZSTG_EXORTER_START_LOCA;
drop index ZSTG_EXORTER_CHROMOSOME;
drop index SYS_C004892;

--EXIT;
