
drop index ZSTG_MOLBELS_SOURCE_ID_LWR;
drop index ZSTG_MOLBELS_VALUE_LWR;
drop index ZSTG_MOLBELS_LABEL_TYPE_LWR;
drop index ZSTG_MOLBELS_MOLECULE_I_LWR;
drop index ZSTG_MOLBELS_MTYPE_LWR;
drop index ZSTG_MOLBELS_VALUE;
drop index ZSTG_MOLBELS_LABEL_TYPE;
drop index ZSTG_MOLBELS_MOLECULE_I;
drop index ZSTG_MOLBELS_MTYPE;
drop index ZSTG_MOLBELS_SOURCE_ID;

--EXIT;
