
create index ZSTG_AGECGID_DRUG_lwr on ZSTG_AGENT_CGID(lower(DRUG)) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_AGECGID_EVS_ID_lwr on ZSTG_AGENT_CGID(lower(EVS_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
