
create index ZSTG_GEN_MAP_FIRST_SNP__lwr on ZSTG_GENETIC_MAP(lower(FIRST_SNP_TSC_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GEN_MAP_SECOND_SNP_lwr on ZSTG_GENETIC_MAP(lower(SECOND_SNP_TSC_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GEN_MAP_TYPE_lwr on ZSTG_GENETIC_MAP(lower(TYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GEN_MAP_PROBE_SET__lwr on ZSTG_GENETIC_MAP(lower(PROBE_SET_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GEN_MAP_FIRST_MARK_lwr on ZSTG_GENETIC_MAP(lower(FIRST_MARKER_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GEN_MAP_FIRST_MARK_lwr on ZSTG_GENETIC_MAP(lower(FIRST_MARKER_NAME)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GEN_MAP_SECOND_MAR_lwr on ZSTG_GENETIC_MAP(lower(SECOND_MARKER_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GEN_MAP_SECOND_MAR_lwr on ZSTG_GENETIC_MAP(lower(SECOND_MARKER_NAME)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
