
create index ZSTG_AGECGID_ID on ZSTG_AGENT_CGID(ID) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_AGECGID_DRUG on ZSTG_AGENT_CGID(DRUG) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_AGECGID_EVS_ID on ZSTG_AGENT_CGID(EVS_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
