
drop index ZSTG_SNPAFFY_PROBE_SET_;
drop index ZSTG_SNPAFFY_NUM_CHRM;
drop index ZSTG_SNPAFFY_ARRAY_NAME;
drop index ZSTG_SNPAFFY_AFFY_SNP_I;
drop index ZSTG_SNPAFFY_CHROMOSOME;
drop index ZSTG_SNPAFFY_IN_HAPMAP;
drop index ZSTG_SNPAFFY_COPY_NUM_V;
drop index ZSTG_SNPAFFY_DBSNP_RS_I;
drop index ZSTG_SNPAFFY_HET_FREQ;
drop index ZSTG_SNPAFFY_STRAND_VS_;
drop index ZSTG_SNPAFFY_FRAGMENT_L;
drop index ZSTG_SNPAFFY_DB_SNP_VER;
drop index ZSTG_SNPAFFY_GENOME_VER;
drop index ZSTG_SNPAFFY_ALLELE_A;
drop index ZSTG_SNPAFFY_MICROSATEL;
drop index ZSTG_SNPAFFY_GENETIC_MA;
drop index ZSTG_SNPAFFY_CHRX_PSEUD;
drop index ZSTG_SNPAFFY_ALLELE_FRE;
drop index ZSTG_SNPAFFY_STRAND;
drop index ZSTG_SNPAFFY_ALLELE_B;
drop index ZSTG_SNPAFFY_CYTOBAND;
drop index ZSTG_SNPAFFY_PHYSICAL_P;
drop index ZSTG_SNPAFFY_FLANK;

--EXIT;
