
create index ZSTG_EXOAFFY_CATEGORY_lwr on ZSTG_EXON_TRANS_AFFY(lower(CATEGORY)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_TRANSCRIPT_lwr on ZSTG_EXON_TRANS_AFFY(lower(TRANSCRIPT_CLUSTER_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_PROBE_SET__lwr on ZSTG_EXON_TRANS_AFFY(lower(PROBE_SET_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_SEQNAME_lwr on ZSTG_EXON_TRANS_AFFY(lower(SEQNAME)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_STRAND_lwr on ZSTG_EXON_TRANS_AFFY(lower(STRAND)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_START_LOCA_lwr on ZSTG_EXON_TRANS_AFFY(lower(START_LOCATION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_STOP_LOCAT_lwr on ZSTG_EXON_TRANS_AFFY(lower(STOP_LOCATION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_TOTAL_PROB_lwr on ZSTG_EXON_TRANS_AFFY(lower(TOTAL_PROBES)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
