
drop index ZSTG_INTABEL_VALUE_LWR;
drop index ZSTG_INTABEL_LABEL_TYPE_LWR;
drop index ZSTG_INTABEL_ROLE_TYPE_LWR;
drop index ZSTG_INTABEL_MOLECULE_I_LWR;
drop index ZSTG_INTABEL_SOURCE_ID_LWR;
drop index ZSTG_INTABEL_INTERACTIO_LWR;
drop index ZSTG_INTABEL_VALUE;
drop index ZSTG_INTABEL_LABEL_TYPE;
drop index ZSTG_INTABEL_ROLE_TYPE;
drop index ZSTG_INTABEL_MOLECULE_I;
drop index ZSTG_INTABEL_SOURCE_ID;
drop index ZSTG_INTABEL_INTERACTIO;

--EXIT;
