
create index ZSTG_DISCGID_DISEASEONT_lwr on ZSTG_DISEASEONTOLOGY_CGID(lower(DISEASEONTOLOGY)) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_DISCGID_EVS_ID_lwr on ZSTG_DISEASEONTOLOGY_CGID(lower(EVS_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
