
drop index ZSTG_SEQGENE_GROUP_LABE;
drop index ZSTG_SEQGENE_CONTIG;
drop index ZSTG_SEQGENE_CHR_ORIENT;
drop index ZSTG_SEQGENE_CHR_STOP;
drop index ZSTG_SEQGENE_EVIDENCE_C;
drop index ZSTG_SEQGENE_TRANSCRIPT;
drop index ZSTG_SEQGENE_CHR_START;
drop index ZSTG_SEQGENE_TAX_ID;
drop index ZSTG_SEQGENE_CHROMOSOME;
drop index ZSTG_SEQGENE_FEATURE_TY;
drop index ZSTG_SEQGENE_FEATURE_NA;
drop index ZSTG_SEQGENE_FEATURE_ID;
drop index ZSTG_SEQGENE_CTG_ORIENT;
drop index ZSTG_SEQGENE_CTG_STOP;
drop index ZSTG_SEQGENE_CTG_START;

--EXIT;
