LOAD DATA 
 
INFILE '$CABIO_DATA_DIR/temp/protein/new_protein.dat'
 
APPEND
 
INTO TABLE PROTEIN_UNIPROT 
 
REENABLE DISABLED_constraints  
FIELDS TERMINATED BY "	"
 
TRAILING NULLCOLS
(PROTEIN_ID "TRIM(:PROTEIN_ID)",
  ACCESSION_NUMBER "TRIM(:ACCESSION_NUMBER)",
  Uniprot_ID "TRIM(:UNIPROT_ID)",
  PROTEIN_DESCRIPTION "TRIM(:PROTEIN_DESCRIPTION)")
