                  <!-- application ftr begins -->                  
                  <table summary="layout" cellpadding="0" cellspacing="0" border="0" width="100%">
                    <tr>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="mailto:ncicb@pop.nci.nih.gov">CONTACT US</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="http://www.nih.gov/about/privacy.htm" target="blank">PRIVACY NOTICE</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="http://www.nih.gov/about/disclaim.htm" target="blank">DISCLAIMER</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="http://www3.cancer.gov/accessibility/nci508.htm" target="blank">ACCESSIBILITY</a>&nbsp;&nbsp;
                      </td>
                      <td><img src="images/ftrMenuSeparator.gif" width="1" height="16" alt="" /></td>
                      <td align="center" height="20" class="footerMenuItem" onmouseover="changeMenuStyle(this,'footerMenuItemOver'),showCursor()" onmouseout="changeMenuStyle(this,'footerMenuItem'),hideCursor()" onclick="document.location.href='#'">
                        &nbsp;&nbsp;<a class="footerMenuLink" href="http://ncicb.nci.nih.gov/NCICB/support" target="blank">APPLICATION SUPPORT</a>&nbsp;&nbsp;
                      </td>
                    </tr>
                  </table>
                  <!-- application ftr ends -->