LOAD DATA 
 
INFILE '$CABIO_DATA_DIR/temp/protein/protein_embl.dat'
 
APPEND
 
INTO TABLE ZSTG_PROTEIN_EMBL 
 
REENABLE DISABLED_constraints  
FIELDS TERMINATED BY "	"
 
TRAILING NULLCOLS
(ID	sequence(MAX,1),
  PROTEIN_ID "TRIM(:PROTEIN_ID)",
  ACC_NUM "TRIM(:ACC_NUM)")
