CREATE OR REPLACE procedure GENE_PROTEIN_TV_LD as

  CURSOR GENEPROTEINTVCUR IS
  (SELECT UNIQUE A.PROTIEN_ID PROTEIN_ID, GENE_ID
	FROM PROTEIN_EMBL_STG A, NUCLEIC_ACID_SEQUENCE B, GENE_NUCLEIC_ACID_SEQUENCE C
	WHERE A.ACC_NUM = B.ACCESSION_NUMBER
	AND C.GENE_SEQUENCE_ID = B.ID);

  aID number:=0;

BEGIN

   EXECUTE IMMEDIATE('TRUNCATE TABLE GENE_PROTEIN_TV REUSE STORAGE ');

   FOR aRec in GENEPROTEINTVCUR LOOP

      aID := aID + 1;

      INSERT INTO ZSTG_GENE_PROTEIN(PROTEIN_ID, GENE_ID)
      VALUES (aRec.PROTEIN_ID,
              aRec.GENE_ID);

      IF MOD(aID, 500) = 0 THEN
         COMMIT;
      END IF;

   END LOOP;

COMMIT;

END; 
/

