CREATE OR REPLACE procedure GENE_NUCLEIC_ACID_SEQUENCE_LD as

  CURSOR GSEQCUR IS
  (SELECT GENE_ID, SEQUENCE_ID from GENE_SEQUENCE);

  aID number:=0;

BEGIN

   EXECUTE IMMEDIATE('TRUNCATE TABLE GENE_NUCLEIC_ACID_SEQUENCE REUSE STORAGE ');

   FOR aRec in GSEQCUR LOOP
      aID := aID + 1;

      INSERT INTO GENE_NUCLEIC_ACID_SEQUENCE(GENE_ID, GENE_SEQUENCE_ID)
      VALUES (aRec.GENE_ID, aRec.SEQUENCE_ID);

      IF MOD(aID, 500) = 0 THEN
         COMMIT;
      END IF;

   END LOOP;

COMMIT;

END; 
/

