DROP PUBLIC SYNONYM AR_CHROMOSOMAL_LOCATION
/

--
-- AR_CHROMOSOMAL_LOCATION  (Synonym) 
--
--  Dependencies: 
--   AR_CHROMOSOMAL_LOCATION (Table)
--
CREATE PUBLIC SYNONYM AR_CHROMOSOMAL_LOCATION FOR AR_CHROMOSOMAL_LOCATION
/


