DROP PUBLIC SYNONYM AR_GENE_SYMBOL_TMP
/

--
-- AR_GENE_SYMBOL_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_GENE_SYMBOL_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_GENE_SYMBOL_TMP FOR AR_GENE_SYMBOL_TMP
/


