DROP PUBLIC SYNONYM AR_GO_BIOLOGICAL_PROCESS_TMP
/

--
-- AR_GO_BIOLOGICAL_PROCESS_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_GO_BIOLOGICAL_PROCESS_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_GO_BIOLOGICAL_PROCESS_TMP FOR AR_GO_BIOLOGICAL_PROCESS_TMP
/


