DROP PUBLIC SYNONYM AR_RNA_PROBESETS_AFFY
/

--
-- AR_RNA_PROBESETS_AFFY  (Synonym) 
--
--  Dependencies: 
--   AR_RNA_PROBESETS_AFFY (Table)
--
CREATE PUBLIC SYNONYM AR_RNA_PROBESETS_AFFY FOR AR_RNA_PROBESETS_AFFY
/


