DROP PUBLIC SYNONYM DATABASE_CROSS_REFERENCE
/

--
-- DATABASE_CROSS_REFERENCE  (Synonym) 
--
--  Dependencies: 
--   DATABASE_CROSS_REFERENCE (Table)
--
CREATE PUBLIC SYNONYM DATABASE_CROSS_REFERENCE FOR DATABASE_CROSS_REFERENCE
/


