DROP PUBLIC SYNONYM DISEASE_RELATIONSHIP
/

--
-- DISEASE_RELATIONSHIP  (Synonym) 
--
--  Dependencies: 
--   DISEASE_RELATIONSHIP (Table)
--
CREATE PUBLIC SYNONYM DISEASE_RELATIONSHIP FOR DISEASE_RELATIONSHIP
/


