DROP PUBLIC SYNONYM EXON_REPORTER_GENE
/

--
-- EXON_REPORTER_GENE  (Synonym) 
--
--  Dependencies: 
--   EXON_REPORTER_GENE (Table)
--
CREATE PUBLIC SYNONYM EXON_REPORTER_GENE FOR EXON_REPORTER_GENE
/


