DROP PUBLIC SYNONYM GENE_RELATIVE_LOCATION
/

--
-- GENE_RELATIVE_LOCATION  (Synonym) 
--
--  Dependencies: 
--   GENE_RELATIVE_LOCATION (Table)
--
CREATE PUBLIC SYNONYM GENE_RELATIVE_LOCATION FOR GENE_RELATIVE_LOCATION
/


