DROP PUBLIC SYNONYM GENE_HISTOPATHOLOGY
/

--
-- GENE_HISTOPATHOLOGY  (Synonym) 
--
--  Dependencies: 
--   GENE_HISTOPATHOLOGY (Table)
--
CREATE PUBLIC SYNONYM GENE_HISTOPATHOLOGY FOR GENE_HISTOPATHOLOGY
/


