DROP PUBLIC SYNONYM GENE_FUNCTION_ASSOCIATION
/

--
-- GENE_FUNCTION_ASSOCIATION  (Synonym) 
--
--  Dependencies: 
--   GENE_FUNCTION_ASSOCIATION (Table)
--
CREATE PUBLIC SYNONYM GENE_FUNCTION_ASSOCIATION FOR GENE_FUNCTION_ASSOCIATION
/


