DROP PUBLIC SYNONYM HISTOPATHOLOGY_DISEASE
/

--
-- HISTOPATHOLOGY_DISEASE  (Synonym) 
--
--  Dependencies: 
--   HISTOPATHOLOGY_DISEASE (Table)
--
CREATE PUBLIC SYNONYM HISTOPATHOLOGY_DISEASE FOR HISTOPATHOLOGY_DISEASE
/


