DROP PUBLIC SYNONYM LIBRARY_HISTOPATHOLOGY
/

--
-- LIBRARY_HISTOPATHOLOGY  (Synonym) 
--
--  Dependencies: 
--   LIBRARY_HISTOPATHOLOGY (Table)
--
CREATE PUBLIC SYNONYM LIBRARY_HISTOPATHOLOGY FOR LIBRARY_HISTOPATHOLOGY
/


