DROP PUBLIC SYNONYM NUCLEIC_ACID_SEQUENCE
/

--
-- NUCLEIC_ACID_SEQUENCE  (Synonym) 
--
--  Dependencies: 
--   NUCLEIC_ACID_SEQUENCE (Table)
--
CREATE PUBLIC SYNONYM NUCLEIC_ACID_SEQUENCE FOR NUCLEIC_ACID_SEQUENCE
/


