DROP PUBLIC SYNONYM PID_ENTITY_SEQUENCE
/

--
-- PID_ENTITY_SEQUENCE  (Synonym) 
--
--  Dependencies: 
--   PID_ENTITY_SEQUENCE (Table)
--
CREATE PUBLIC SYNONYM PID_ENTITY_SEQUENCE FOR PID_ENTITY_SEQUENCE
/


