DROP PUBLIC SYNONYM PUBLICATION_SOURCE
/

--
-- PUBLICATION_SOURCE  (Synonym) 
--
--  Dependencies: 
--   PUBLICATION_SOURCE (Table)
--
CREATE PUBLIC SYNONYM PUBLICATION_SOURCE FOR PUBLICATION_SOURCE
/


