DROP PUBLIC SYNONYM URL_SOURCE_REFERENCE
/

--
-- URL_SOURCE_REFERENCE  (Synonym) 
--
--  Dependencies: 
--   URL_SOURCE_REFERENCE (Table)
--
CREATE PUBLIC SYNONYM URL_SOURCE_REFERENCE FOR URL_SOURCE_REFERENCE
/


