DROP PUBLIC SYNONYM ZSTG_HISTOLOGY_CODE
/

--
-- ZSTG_HISTOLOGY_CODE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_HISTOLOGY_CODE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_HISTOLOGY_CODE FOR ZSTG_HISTOLOGY_CODE
/


