DROP PUBLIC SYNONYM ZSTG_ROLECODE_CGID
/

--
-- ZSTG_ROLECODE_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_ROLECODE_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_ROLECODE_CGID FOR ZSTG_ROLECODE_CGID
/


