DROP PUBLIC SYNONYM ZSTG_BIO_PATHWAYS_TV
/

--
-- ZSTG_BIO_PATHWAYS_TV  (Synonym) 
--
--  Dependencies: 
--   ZSTG_BIO_PATHWAYS_TV (Table)
--
CREATE PUBLIC SYNONYM ZSTG_BIO_PATHWAYS_TV FOR ZSTG_BIO_PATHWAYS_TV
/


