DROP PUBLIC SYNONYM ZSTG_PID_PHYSICALENTITY
/

--
-- ZSTG_PID_PHYSICALENTITY  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_PHYSICALENTITY (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_PHYSICALENTITY FOR ZSTG_PID_PHYSICALENTITY
/


