DROP PUBLIC SYNONYM ZSTG_MICROSATELLITE
/

--
-- ZSTG_MICROSATELLITE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MICROSATELLITE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MICROSATELLITE FOR ZSTG_MICROSATELLITE
/


