DROP PUBLIC SYNONYM ZSTG_PID_INTERACTANTS
/

--
-- ZSTG_PID_INTERACTANTS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_INTERACTANTS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_INTERACTANTS FOR ZSTG_PID_INTERACTANTS
/


