/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP PUBLIC SYNONYM ZSTG_STARTEXPRARRAYREPCYTOIDS
/

--
-- ZSTG_STARTEXPRARRAYREPCYTOIDS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_STARTEXPRARRAYREPCYTOIDS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_STARTEXPRARRAYREPCYTOIDS FOR ZSTG_STARTEXPRARRAYREPCYTOIDS
/


