DROP PUBLIC SYNONYM ZSTG_PID_COMPLEX_COMPONENT
/

--
-- ZSTG_PID_COMPLEX_COMPONENT  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_COMPLEX_COMPONENT (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_COMPLEX_COMPONENT FOR ZSTG_PID_COMPLEX_COMPONENT
/


