DROP PUBLIC SYNONYM ZSTG_PID_EVIDENCECODE
/

--
-- ZSTG_PID_EVIDENCECODE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_EVIDENCECODE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_EVIDENCECODE FOR ZSTG_PID_EVIDENCECODE
/


