DROP PUBLIC SYNONYM ZSTG_HUMAN_CYTOBAND
/

--
-- ZSTG_HUMAN_CYTOBAND  (Synonym) 
--
--  Dependencies: 
--   ZSTG_HUMAN_CYTOBAND (Table)
--
CREATE PUBLIC SYNONYM ZSTG_HUMAN_CYTOBAND FOR ZSTG_HUMAN_CYTOBAND
/


