DROP PUBLIC SYNONYM ZSTG_MISSING_AGENT_CGID
/

--
-- ZSTG_MISSING_AGENT_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MISSING_AGENT_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MISSING_AGENT_CGID FOR ZSTG_MISSING_AGENT_CGID
/


