DROP PUBLIC SYNONYM ZSTG_POPULATION_FREQUENCY
/

--
-- ZSTG_POPULATION_FREQUENCY  (Synonym) 
--
--  Dependencies: 
--   ZSTG_POPULATION_FREQUENCY (Table)
--
CREATE PUBLIC SYNONYM ZSTG_POPULATION_FREQUENCY FOR ZSTG_POPULATION_FREQUENCY
/


