DROP PUBLIC SYNONYM ZSTG_PID_FMLY_PRTPNT_PTM
/

--
-- ZSTG_PID_FMLY_PRTPNT_PTM  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_FMLY_PRTPNT_PTM (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_FMLY_PRTPNT_PTM FOR ZSTG_PID_FMLY_PRTPNT_PTM
/


