DROP PUBLIC SYNONYM AR_ENTREZ_GENE_TMP
/

--
-- AR_ENTREZ_GENE_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_ENTREZ_GENE_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_ENTREZ_GENE_TMP FOR AR_ENTREZ_GENE_TMP
/


