DROP PUBLIC SYNONYM AR_GO_BIOLOGICAL_PROCESS
/

--
-- AR_GO_BIOLOGICAL_PROCESS  (Synonym) 
--
--  Dependencies: 
--   AR_GO_BIOLOGICAL_PROCESS (Table)
--
CREATE PUBLIC SYNONYM AR_GO_BIOLOGICAL_PROCESS FOR AR_GO_BIOLOGICAL_PROCESS
/


