DROP PUBLIC SYNONYM AR_GO_MOLECULAR_FUNCTION_TMP
/

--
-- AR_GO_MOLECULAR_FUNCTION_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_GO_MOLECULAR_FUNCTION_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_GO_MOLECULAR_FUNCTION_TMP FOR AR_GO_MOLECULAR_FUNCTION_TMP
/


