DROP PUBLIC SYNONYM AR_REPRESENTATIVE_PUBLIC_ID
/

--
-- AR_REPRESENTATIVE_PUBLIC_ID  (Synonym) 
--
--  Dependencies: 
--   AR_REPRESENTATIVE_PUBLIC_ID (Table)
--
CREATE PUBLIC SYNONYM AR_REPRESENTATIVE_PUBLIC_ID FOR AR_REPRESENTATIVE_PUBLIC_ID
/


