DROP PUBLIC SYNONYM AR_REP_PUBLIC_ID_TMP
/

--
-- AR_REP_PUBLIC_ID_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_REP_PUBLIC_ID_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_REP_PUBLIC_ID_TMP FOR AR_REP_PUBLIC_ID_TMP
/


