DROP PUBLIC SYNONYM CYTOGENIC_LOCATION_CYTOBAND
/

--
-- CYTOGENIC_LOCATION_CYTOBAND  (Synonym) 
--
--  Dependencies: 
--   CYTOGENIC_LOCATION_CYTOBAND (Table)
--
CREATE PUBLIC SYNONYM CYTOGENIC_LOCATION_CYTOBAND FOR CYTOGENIC_LOCATION_CYTOBAND
/


