DROP PUBLIC SYNONYM EXPR_REPORTER_PROTEIN_DOMAIN
/

--
-- EXPR_REPORTER_PROTEIN_DOMAIN  (Synonym) 
--
--  Dependencies: 
--   EXPR_REPORTER_PROTEIN_DOMAIN (Table)
--
CREATE PUBLIC SYNONYM EXPR_REPORTER_PROTEIN_DOMAIN FOR EXPR_REPORTER_PROTEIN_DOMAIN
/


