DROP PUBLIC SYNONYM OLD_PROTOCOL_AGENTS
/

--
-- OLD_PROTOCOL_AGENTS  (Synonym) 
--
--  Dependencies: 
--   OLD_PROTOCOL_AGENTS (Table)
--
CREATE PUBLIC SYNONYM OLD_PROTOCOL_AGENTS FOR OLD_PROTOCOL_AGENTS
/


