DROP PUBLIC SYNONYM PID_PHYSICAL_ENTITY_ACCESSION
/

--
-- PID_PHYSICAL_ENTITY_ACCESSION  (Synonym) 
--
--  Dependencies: 
--   PID_PHYSICAL_ENTITY_ACCESSION (Table)
--
CREATE PUBLIC SYNONYM PID_PHYSICAL_ENTITY_ACCESSION FOR PID_PHYSICAL_ENTITY_ACCESSION
/


