DROP PUBLIC SYNONYM ZSTG_SNPREP_SNTV_IDS_MPNG
/

--
-- ZSTG_SNPREP_SNTV_IDS_MPNG  (Synonym) 
--
--  Dependencies: 
--   ZSTG_SNPREP_SNTV_IDS_MPNG (Table)
--
CREATE PUBLIC SYNONYM ZSTG_SNPREP_SNTV_IDS_MPNG FOR ZSTG_SNPREP_SNTV_IDS_MPNG
/


