DROP PUBLIC SYNONYM ZSTG_ENDSNPARRAYREPCYTOIDS
/

--
-- ZSTG_ENDSNPARRAYREPCYTOIDS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_ENDSNPARRAYREPCYTOIDS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_ENDSNPARRAYREPCYTOIDS FOR ZSTG_ENDSNPARRAYREPCYTOIDS
/


