/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP PUBLIC SYNONYM ZSTG_MOLECULECOMPONENTLABELS
/

--
-- ZSTG_MOLECULECOMPONENTLABELS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MOLECULECOMPONENTLABELS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MOLECULECOMPONENTLABELS FOR ZSTG_MOLECULECOMPONENTLABELS
/


