DROP PUBLIC SYNONYM ZSTG_ARRAY_REPORTER_CH
/

--
-- ZSTG_ARRAY_REPORTER_CH  (Synonym) 
--
--  Dependencies: 
--   ZSTG_ARRAY_REPORTER_CH (Table)
--
CREATE PUBLIC SYNONYM ZSTG_ARRAY_REPORTER_CH FOR ZSTG_ARRAY_REPORTER_CH
/


