/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP PUBLIC SYNONYM ZSTG_INTERACTIONCOMPPTMTERMS
/

--
-- ZSTG_INTERACTIONCOMPPTMTERMS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_INTERACTIONCOMPPTMTERMS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_INTERACTIONCOMPPTMTERMS FOR ZSTG_INTERACTIONCOMPPTMTERMS
/


