DROP PUBLIC SYNONYM ZSTG_PATHWAYCOMPONENTS
/

--
-- ZSTG_PATHWAYCOMPONENTS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PATHWAYCOMPONENTS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PATHWAYCOMPONENTS FOR ZSTG_PATHWAYCOMPONENTS
/


