DROP PUBLIC SYNONYM ZSTG_GENE_DISEASE_EVID_CGID
/

--
-- ZSTG_GENE_DISEASE_EVID_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_DISEASE_EVID_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_DISEASE_EVID_CGID FOR ZSTG_GENE_DISEASE_EVID_CGID
/


