DROP PUBLIC SYNONYM ZSTG_DISEASEONTOLOGY_CGID
/

--
-- ZSTG_DISEASEONTOLOGY_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_DISEASEONTOLOGY_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_DISEASEONTOLOGY_CGID FOR ZSTG_DISEASEONTOLOGY_CGID
/


