DROP PUBLIC SYNONYM ZSTG_ENDEXPRARRAYREPCYTOIDS
/

--
-- ZSTG_ENDEXPRARRAYREPCYTOIDS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_ENDEXPRARRAYREPCYTOIDS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_ENDEXPRARRAYREPCYTOIDS FOR ZSTG_ENDEXPRARRAYREPCYTOIDS
/


