DROP PUBLIC SYNONYM ZSTG_MOLECULENAMES
/

--
-- ZSTG_MOLECULENAMES  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MOLECULENAMES (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MOLECULENAMES FOR ZSTG_MOLECULENAMES
/


