LOAD DATA 
 
INFILE '/cabio/cabiodb/cabio_data/temp/arrays/Agilent/HumanGenome44K/phyloc.dat'

APPEND
 
INTO TABLE ZSTG_RNA_AGILENT 
 
REENABLE DISABLED_CONSTRAINTS 
FIELDS TERMINATED BY "#"
TRAILING NULLCOLS
 
(
PROBE_SET_ID,
PRIMARY_ACCESSION,
REF_SEQ_ACCESSION,
GENBANK_ACCESSION,
UNIGENE_ID,
ENTREZ_GENE_ID,
GENE_SYMBOL,
GENE_NAME,
ENSEMBL_ID,
TIGR_ID,
GO_ANNOTATION char(40000),
DESCRIPTION char(1000),
COORDINATES,
CYTOBAND,
CHROMOSOME_NUMBER,
CHR_START,
CHR_STOP,
CYTO_START,
CYTO_STOP
)
