CREATE OR REPLACE procedure NUCLEIC_ACID_SEQUENCE_LD as

  CURSOR NUCLEICACIDSEQUENCECUR IS
  (SELECT SEQUENCE_ID, ACCESSION_NUMBER, VERSION, SEQUENCE_TYPE, CLONE_ID, LENGTH from sequence);

  aID number:=0;

BEGIN

   EXECUTE IMMEDIATE('TRUNCATE TABLE NUCLEIC_ACID_SEQUENCE REUSE STORAGE ');

   FOR aRec in NUCLEICACIDSEQUENCECUR LOOP

      aID := aID + 1;

      INSERT INTO NUCLEIC_ACID_SEQUENCE(ID, ACCESSION_NUMBER, VERSION, SEQUENCE_TYPE, CLONE_ID, LENGTH)
      VALUES (aRec.SEQUENCE_ID,
              aRec.ACCESSION_NUMBER,
              aRec.VERSION,
              aRec.SEQUENCE_TYPE,
	      aRec.CLONE_ID,
	      aRec.LENGTH);

      IF MOD(aID, 500) = 0 THEN
         COMMIT;
      END IF;

   END LOOP;

COMMIT;

END; 
/

