CREATE OR REPLACE procedure NUCLEIC_ACID_SEQUENCE_01_LD as

BEGIN

   EXECUTE IMMEDIATE('TRUNCATE TABLE NUCLEIC_ACID_SEQUENCE REUSE STORAGE ');

   INSERT INTO NUCLEIC_ACID_SEQUENCE(ID, ACCESSION_NUMBER, VERSION, SEQUENCE_TYPE, CLONE_ID, VALUE, LENGTH)
   SELECT SEQUENCE_ID, ACCESSION_NUMBER, VERSION, SEQUENCE_TYPE, CLONE_ID, TO_LOB(ASCII_STRING), LENGTH from sequence
	WHERE Sequence_ID <= 500000;

COMMIT;
END; 
/

