CREATE OR REPLACE FORCE VIEW CABIODEV.GO_RELATIONSHIP_VIEW
(GO_ID, CHILD_ID, PARENT_ID, RELATIONSHIP)
AS 
SELECT child_id go_id, child_id, parent_id, RELATIONSHIP FROM GO_RELATIONSHIP
UNION
SELECT parent_id go_id, child_id, parent_id, RELATIONSHIP FROM go_relationship;


