CREATE OR REPLACE FORCE VIEW CABIODEV.RELATIVE_LOCATION_VIEW
(ID, ORIENTATION, SNP_ID, DISTANCE, BIG_ID)
AS 
select ID, ORIENTATION, SNP_ID, DISTANCE, BIG_ID from MARKER_RELATIVE_LOCATION
UNION
select ID, ORIENTATION, SNP_ID, DISTANCE, BIG_ID from GENE_RELATIVE_LOCATION;


