
TRUNCATE TABLE protein_domain REUSE STORAGE;
TRUNCATE TABLE gene_relative_location REUSE STORAGE;
TRUNCATE TABLE marker_marker_rel_location REUSE STORAGE;
TRUNCATE TABLE marker_relative_location REUSE STORAGE;
TRUNCATE TABLE expression_reporter REUSE STORAGE;
TRUNCATE TABLE zstg_expression_reporter REUSE STORAGE;
TRUNCATE TABLE zstg_exon_reporter REUSE STORAGE;
TRUNCATE TABLE expr_reporter_protein_domain REUSE STORAGE;
TRUNCATE TABLE snp_reporter REUSE STORAGE;
TRUNCATE TABLE zstg_snp_reporter REUSE STORAGE;
TRUNCATE TABLE exon_reporter_gene REUSE STORAGE;
TRUNCATE TABLE exon_reporter REUSE STORAGE;
TRUNCATE TABLE exon REUSE STORAGE;
TRUNCATE TABLE transcript_gene REUSE STORAGE;
TRUNCATE TABLE transcript REUSE STORAGE;
TRUNCATE TABLE microarray REUSE STORAGE;
TRUNCATE TABLE transcript_array_reporter;
