
drop index CLONE_RION_BIG_ID_LWR;
drop index CLONE_RION_BIG_ID;
drop index SYS_C0021074_IDX;
drop index CLONE_RETION_NUCLEIC_AC;
drop index CLONE_RETION_ID;
drop index CLONE_RETION_TYPE;
drop index CLONE_RETION_CLONE_ID;
drop index CLONE_RETION_TYPE_LWR;

--EXIT;
