
create index DATABASEENCE_ENGINEERED on DATABASE_CROSS_REFERENCE(ENGINEEREDGENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_PROTEIN_ID on DATABASE_CROSS_REFERENCE(PROTEIN_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_NUCLEIC_AC on DATABASE_CROSS_REFERENCE(NUCLEIC_ACID_SEQ_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_SNP_ID on DATABASE_CROSS_REFERENCE(SNP_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_GENE_ID on DATABASE_CROSS_REFERENCE(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_SUMMARY on DATABASE_CROSS_REFERENCE(SUMMARY) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_SOURCE_TYP on DATABASE_CROSS_REFERENCE(SOURCE_TYPE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_CROSS_REFE on DATABASE_CROSS_REFERENCE(CROSS_REFERENCE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_SOURCE_NAM on DATABASE_CROSS_REFERENCE(SOURCE_NAME) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_TYPE on DATABASE_CROSS_REFERENCE(TYPE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index DATABASEENCE_ID on DATABASE_CROSS_REFERENCE(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
