
drop index RELATIVE_LOC_BIGID;
drop index ARRAY_REP_BIGID;
drop index BIN$dRmTCelEBP7gQLuJp7QCYA==$0;
drop index BIN$dRmTCelfBP7gQLuJp7QCYA==$0;
drop index BIN$dQIRDnC2t43gQLuJp7RasA==$0;
drop index TISSUE_PLE_BIG_ID;
drop index ZSTG_AGENT_BIG_ID;
drop index CHROMOSOME_BIG_ID;
drop index DISEASEHIP_BIG_ID;
drop index ARRAY_RNEW_BIG_ID;
drop index ORGANONHIP_BIG_ID;
drop index PROTOCOCOL_BIG_ID;
drop index TISSUE_ODE_BIG_ID;
drop index VOCABULARY_BIG_ID;
drop index AGENT_OOLD_BIG_ID;
drop index REL_LOC_BIGID;
drop index LOC43_BIG_ID;
drop index AR_REP_CH_BIGID;
drop index BIN$dQIRDnDRt43gQLuJp7RasA==$0;
drop index BIN$dUi3KgDhN4bgQLuJp7RvhA==$0;
drop index BIN$dTdrCa57rdHgQLuJp7RLkw==$0;
drop index BIN$dUi3KgDGN4bgQLuJp7RvhA==$0;
drop index ZSTG_OLOLS_BIG_ID;
drop index ZSTG_OLSES_BIG_ID;
drop index ZSTG_AG_BK_BIG_ID;
drop index ZSTG_TAGET_BIG_ID;
drop index ZSTG_MAKER_BIG_ID;
drop index ZSTG_TAXON_BIG_ID;
drop index ZSTG_BI_TV_BIG_ID;
drop index LIBRARYARY_BIG_ID;
drop index BIN$dTdrCa5grdHgQLuJp7RLkw==$0;

EXIT;
