
create index ZSTG_INTABEL_VALUE_lwr on ZSTG_INTERACTIONCOMPONENTLABEL(lower(VALUE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTABEL_LABEL_TYPE_lwr on ZSTG_INTERACTIONCOMPONENTLABEL(lower(LABEL_TYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTABEL_ROLE_TYPE_lwr on ZSTG_INTERACTIONCOMPONENTLABEL(lower(ROLE_TYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTABEL_MOLECULE_I_lwr on ZSTG_INTERACTIONCOMPONENTLABEL(lower(MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTABEL_SOURCE_ID_lwr on ZSTG_INTERACTIONCOMPONENTLABEL(lower(SOURCE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTABEL_INTERACTIO_lwr on ZSTG_INTERACTIONCOMPONENTLABEL(lower(INTERACTION_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
