
drop index ZSTG_INTERMS_PROTEIN_LWR;
drop index ZSTG_INTERMS_POSITION_LWR;
drop index ZSTG_INTERMS_AA_LWR;
drop index ZSTG_INTERMS_MODIFICATI_LWR;
drop index ZSTG_INTERMS_INTERACTIO;
drop index ZSTG_INTERMS_SOURCE_ID;
drop index ZSTG_INTERMS_MOLECULE_I;
drop index ZSTG_INTERMS_ROLE_TYPE;
drop index ZSTG_INTERMS_PROTEIN;
drop index ZSTG_INTERMS_POSITION;
drop index ZSTG_INTERMS_AA;
drop index ZSTG_INTERMS_MODIFICATI;
drop index ZSTG_INTERMS_INTERACTIO_LWR;
drop index ZSTG_INTERMS_SOURCE_ID_LWR;
drop index ZSTG_INTERMS_MOLECULE_I_LWR;
drop index ZSTG_INTERMS_ROLE_TYPE_LWR;

--EXIT;
