ALTER TABLE AGENT
 DROP PRIMARY KEY CASCADE
/
DROP TABLE AGENT CASCADE CONSTRAINTS PURGE
/

--
-- AGENT  (Table) 
--
CREATE TABLE AGENT ( AGENT_ID NUMBER NOT NULL, AGENT_TYPE VARCHAR2(100 BYTE) NULL, AGENT_NAME VARCHAR2(2500 BYTE) NULL, AGENT_SOURCE VARCHAR2(400 BYTE) NULL, AGENT_COMMENT VARCHAR2(400 BYTE) NULL, CMAP_AGENT NUMBER DEFAULT 0 NULL, NSC_NUMBER NUMBER NULL, EVS_ID VARCHAR2(50 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT AGENT_ID_NEW_PK PRIMARY KEY (AGENT_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


