/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE AR_ENSEMBL_TMP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE AR_ENSEMBL_TMP CASCADE CONSTRAINTS PURGE
/

--
-- AR_ENSEMBL_TMP  (Table) 
--
CREATE TABLE AR_ENSEMBL_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, ENSEMBL_ID VARCHAR2(20 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL, PRIMARY KEY (PROBE_SET_ID, ENSEMBL_ID, GENECHIP_ARRAY) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT ) MONITORING
/


