/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE BIOGENES CASCADE CONSTRAINTS PURGE
/

--
-- BIOGENES  (Table) 
--
CREATE TABLE BIOGENES ( ORGANISM CHAR(2 BYTE) NOT NULL, BC_ID VARCHAR2(4000 BYTE) NOT NULL, LOCUS_ID NUMBER NULL, GENE_ID NUMBER NULL, BIOGENES_ID NUMBER NULL, CHECK ("LOCUS_ID" IS NOT NULL) DISABLE ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


