ALTER TABLE CGAP_TISSUE_SELECTION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CGAP_TISSUE_SELECTION CASCADE CONSTRAINTS PURGE
/

--
-- CGAP_TISSUE_SELECTION  (Table) 
--
--  Dependencies: 
--   TISSUE_CODE (Table)
--
CREATE TABLE CGAP_TISSUE_SELECTION ( TISSUE_NAME VARCHAR2(40 BYTE) NULL, TISSUE_CODE NUMBER(3) NULL, CONSTRAINT CGTPK PRIMARY KEY (TISSUE_CODE, TISSUE_NAME), CONSTRAINT CGTFK FOREIGN KEY (TISSUE_CODE) REFERENCES TISSUE_CODE (TISSUE_CODE) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


