/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE CHROMOSOME
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CHROMOSOME CASCADE CONSTRAINTS PURGE
/

--
-- CHROMOSOME  (Table) 
--
--  Dependencies: 
--   TAXON (Table)
--
CREATE TABLE CHROMOSOME ( CHROMOSOME_ID NUMBER NOT NULL, TAXON_ID NUMBER NOT NULL, CHROMOSOME_NUMBER VARCHAR2(40 BYTE) NOT NULL, BIG_ID VARCHAR2(200 BYTE) NOT NULL, PRIMARY KEY (CHROMOSOME_ID), CONSTRAINT CHRBIGID UNIQUE (BIG_ID), CONSTRAINT CHRNODUPS UNIQUE (CHROMOSOME_NUMBER, TAXON_ID), UNIQUE (TAXON_ID, CHROMOSOME_NUMBER), CONSTRAINT CHTAX FOREIGN KEY (TAXON_ID) REFERENCES TAXON (TAXON_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


