/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE CLONE_DIFF_MOUSE CASCADE CONSTRAINTS PURGE
/

--
-- CLONE_DIFF_MOUSE  (Table) 
--
CREATE TABLE CLONE_DIFF_MOUSE ( IMAGE_ID VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


