/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE DISEASE_RELATIONSHIP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE DISEASE_RELATIONSHIP CASCADE CONSTRAINTS PURGE
/

--
-- DISEASE_RELATIONSHIP  (Table) 
--
CREATE TABLE DISEASE_RELATIONSHIP ( ID NUMBER(8,2) NOT NULL, PARENT_ID NUMBER(8,2) NULL, CHILD_ID NUMBER(8,2) NULL, RELATIONSHIP VARCHAR2(50 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT PK_DISEASE_RELATIONSHIP PRIMARY KEY (ID), CONSTRAINT DRBIGID UNIQUE (BIG_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


