/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE EXON_REPORTER_GENE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EXON_REPORTER_GENE CASCADE CONSTRAINTS PURGE
/

--
-- EXON_REPORTER_GENE  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--   EXON_REPORTER (Table)
--
CREATE TABLE EXON_REPORTER_GENE ( EXON_REPORTER_ID NUMBER NOT NULL, GENE_ID NUMBER NOT NULL, PRIMARY KEY (EXON_REPORTER_ID, GENE_ID), CONSTRAINT EXPRREPGENEFK2 FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), CONSTRAINT EXREPFK FOREIGN KEY (EXON_REPORTER_ID) REFERENCES EXON_REPORTER (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


