/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE EXON_REPORTER
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EXON_REPORTER CASCADE CONSTRAINTS PURGE
/

--
-- EXON_REPORTER  (Table) 
--
--  Dependencies: 
--   TRANSCRIPT (Table)
--   MICROARRAY (Table)
--
CREATE TABLE EXON_REPORTER ( ID NUMBER NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, MICROARRAY_ID NUMBER NOT NULL, MANUFACTURER_PSR_ID VARCHAR2(20 BYTE) NOT NULL, PROBE_COUNT VARCHAR2(20 BYTE) NOT NULL, STRAND VARCHAR2(20 BYTE) NOT NULL, TRANSCRIPT_ID NUMBER NOT NULL, EXON_ID NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT EXON_REPORTER_PK PRIMARY KEY (ID), UNIQUE (NAME, MICROARRAY_ID, MANUFACTURER_PSR_ID, PROBE_COUNT, STRAND, TRANSCRIPT_ID, EXON_ID), CONSTRAINT XONREPORTER UNIQUE (BIG_ID), CONSTRAINT EXREPFK1 FOREIGN KEY (TRANSCRIPT_ID) REFERENCES TRANSCRIPT (ID), CONSTRAINT EXREPFK2 FOREIGN KEY (MICROARRAY_ID) REFERENCES MICROARRAY (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


