/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE GENE_TARGET
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENE_TARGET CASCADE CONSTRAINTS PURGE
/

--
-- GENE_TARGET  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--   TARGET (Table)
--
CREATE TABLE GENE_TARGET ( TARGET_ID NUMBER NOT NULL, GENE_ID NUMBER NOT NULL, LOCUS_ID NUMBER NULL, CONSTRAINT GT_PK PRIMARY KEY (GENE_ID, TARGET_ID), CONSTRAINT GTFK1 FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), CONSTRAINT GTFK2 FOREIGN KEY (TARGET_ID) REFERENCES TARGET (TARGET_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


