ALTER TABLE GENE_HOMOLOGUE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENE_HOMOLOGUE CASCADE CONSTRAINTS PURGE
/

--
-- GENE_HOMOLOGUE  (Table) 
--
CREATE TABLE GENE_HOMOLOGUE ( GENE_ID NUMBER NOT NULL, RELATED_GENE NUMBER NOT NULL, PERCENT_ALIGNMENT NUMBER NOT NULL, PRIMARY KEY (GENE_ID, RELATED_GENE, PERCENT_ALIGNMENT) ) TABLESPACE CABIO_MAP LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


