ALTER TABLE GENERIC_ARRAY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENERIC_ARRAY CASCADE CONSTRAINTS PURGE
/

--
-- GENERIC_ARRAY  (Table) 
--
CREATE TABLE GENERIC_ARRAY ( ID NUMBER(8,2) NOT NULL, ARRAY_NAME VARCHAR2(50 BYTE) NOT NULL, PLATFORM VARCHAR2(50 BYTE) NOT NULL, TYPE VARCHAR2(50 BYTE) NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT PK_GENERIC_ARRAY PRIMARY KEY (ID), CONSTRAINT GABIGID UNIQUE (BIG_ID), CONSTRAINT GENERICARRNODUPS UNIQUE (TYPE, PLATFORM, ARRAY_NAME) DISABLE, UNIQUE (ARRAY_NAME, PLATFORM, TYPE) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


