/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE GENE_NUCLEIC_ACID_SEQUENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENE_NUCLEIC_ACID_SEQUENCE CASCADE CONSTRAINTS PURGE
/

--
-- GENE_NUCLEIC_ACID_SEQUENCE  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--
CREATE TABLE GENE_NUCLEIC_ACID_SEQUENCE ( GENE_ID NUMBER NOT NULL, GENE_SEQUENCE_ID NUMBER NOT NULL, CONSTRAINT PK_GENE_SEQUENCE PRIMARY KEY (GENE_ID, GENE_SEQUENCE_ID), CONSTRAINT GNAS FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


