/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE IMT_TO_TISSUE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE IMT_TO_TISSUE CASCADE CONSTRAINTS PURGE
/

--
-- IMT_TO_TISSUE  (Table) 
--
CREATE TABLE IMT_TO_TISSUE ( IMT_CODE NUMBER NULL, TISSUE_CODE NUMBER NULL, CONSTRAINT IMTTISS PRIMARY KEY (IMT_CODE, TISSUE_CODE) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


