/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE MARKER_RELATIVE_LOCATION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE MARKER_RELATIVE_LOCATION CASCADE CONSTRAINTS PURGE
/

--
-- MARKER_RELATIVE_LOCATION  (Table) 
--
CREATE TABLE MARKER_RELATIVE_LOCATION ( ID NUMBER NOT NULL, TYPE VARCHAR2(50 BYTE) NOT NULL, ORIENTATION VARCHAR2(50 BYTE) NULL, DISTANCE VARCHAR2(50 BYTE) NOT NULL, SNP_ID NUMBER NOT NULL, PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT MARKER_RL_PK PRIMARY KEY (ID), UNIQUE (TYPE, ORIENTATION, DISTANCE, SNP_ID, PROBE_SET_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


