/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ONTOLOGY_RELATIONSHIP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ONTOLOGY_RELATIONSHIP CASCADE CONSTRAINTS PURGE
/

--
-- ONTOLOGY_RELATIONSHIP  (Table) 
--
CREATE TABLE ONTOLOGY_RELATIONSHIP ( PARENT_ID NUMBER NULL, CHILD_ID NUMBER NULL, RELATIONSHIP VARCHAR2(100 BYTE) NULL, CONSTRAINT ORPK PRIMARY KEY (PARENT_ID, CHILD_ID, RELATIONSHIP) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


