/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PID_ENTITY_AGENT
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_ENTITY_AGENT CASCADE CONSTRAINTS PURGE
/

--
-- PID_ENTITY_AGENT  (Table) 
--
--  Dependencies: 
--   PID_PHYSICAL_ENTITY (Table)
--   AGENT (Table)
--
CREATE TABLE PID_ENTITY_AGENT ( PHYSICAL_ENTITY_ID NUMBER NOT NULL, AGENT_ID NUMBER NOT NULL, PRIMARY KEY (PHYSICAL_ENTITY_ID, AGENT_ID), FOREIGN KEY (PHYSICAL_ENTITY_ID) REFERENCES PID_PHYSICAL_ENTITY (ID), FOREIGN KEY (AGENT_ID) REFERENCES AGENT (AGENT_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


