/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PID_PHYSICAL_ENTITY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_PHYSICAL_ENTITY CASCADE CONSTRAINTS PURGE
/

--
-- PID_PHYSICAL_ENTITY  (Table) 
--
CREATE TABLE PID_PHYSICAL_ENTITY ( ID NUMBER NOT NULL, PROT_SUBUNIT_START NUMBER NULL, PROT_SUBUNIT_STOP NUMBER NULL, DISCRIMINATOR VARCHAR2(2500 BYTE) NOT NULL, PROTEIN_ENTITY_ID NUMBER NULL, PID_PHYSICALENTITY_ID NUMBER NOT NULL, BIG_ID VARCHAR2(2500 BYTE) NULL, ORDER_OF_COMPONENT NUMBER NULL, PRIMARY KEY (ID), UNIQUE (PROTEIN_ENTITY_ID, PID_PHYSICALENTITY_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


