/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PID_ENTITY_NAME
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_ENTITY_NAME CASCADE CONSTRAINTS PURGE
/

--
-- PID_ENTITY_NAME  (Table) 
--
CREATE TABLE PID_ENTITY_NAME ( ID NUMBER NOT NULL, NAME VARCHAR2(2500 BYTE) NOT NULL, PID_PHYSICALENTITY_ID NUMBER NOT NULL, BIG_ID VARCHAR2(2500 BYTE) NULL, PRIMARY KEY (ID), UNIQUE (NAME, PID_PHYSICALENTITY_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


