ALTER TABLE PROTEIN_TAXON
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PROTEIN_TAXON CASCADE CONSTRAINTS PURGE
/

--
-- PROTEIN_TAXON  (Table) 
--
--  Dependencies: 
--   NEW_PROTEIN (Table)
--   TAXON (Table)
--
CREATE TABLE PROTEIN_TAXON ( PROTEIN_ID NUMBER NOT NULL, TAXON_ID NUMBER NOT NULL, CONSTRAINT PT_PK PRIMARY KEY (PROTEIN_ID, TAXON_ID), CONSTRAINT PTFK1 FOREIGN KEY (PROTEIN_ID) REFERENCES NEW_PROTEIN (PROTEIN_ID), CONSTRAINT PT_FK1 FOREIGN KEY (TAXON_ID) REFERENCES TAXON (TAXON_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


