/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PROTEIN_DOMAIN
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PROTEIN_DOMAIN CASCADE CONSTRAINTS PURGE
/

--
-- PROTEIN_DOMAIN  (Table) 
--
CREATE TABLE PROTEIN_DOMAIN ( ID NUMBER NOT NULL, ACCESSION_NUMBER VARCHAR2(20 BYTE) NOT NULL, DESCRIPTION VARCHAR2(2000 BYTE) NOT NULL, TYPE VARCHAR2(200 BYTE) NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT PROTEIN_DOMAIN_PK PRIMARY KEY (ID), CONSTRAINT PDBIGID UNIQUE (BIG_ID), UNIQUE (ACCESSION_NUMBER, DESCRIPTION, TYPE) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


