DROP TABLE PROTEIN_PROTEIN_ALIAS CASCADE CONSTRAINTS PURGE
/

--
-- PROTEIN_PROTEIN_ALIAS  (Table) 
--
--  Dependencies: 
--   NEW_PROTEIN (Table)
--
CREATE TABLE PROTEIN_PROTEIN_ALIAS ( PROTEIN_ID NUMBER NOT NULL, PROTEIN_ALIAS_ID NUMBER NOT NULL, UNIQUE (PROTEIN_ID, PROTEIN_ALIAS_ID), CONSTRAINT PPAFK1 FOREIGN KEY (PROTEIN_ID) REFERENCES NEW_PROTEIN (PROTEIN_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


