/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PUBLICATIONSTATUS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PUBLICATIONSTATUS CASCADE CONSTRAINTS PURGE
/

--
-- PUBLICATIONSTATUS  (Table) 
--
CREATE TABLE PUBLICATIONSTATUS ( PUBLICATIONSTATUS_ID NUMBER NOT NULL, PUBLICATIONSTATUS_NAME VARCHAR2(50 BYTE) NOT NULL, PRIMARY KEY (PUBLICATIONSTATUS_ID, PUBLICATIONSTATUS_NAME) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


