/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE SNP_TV
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SNP_TV CASCADE CONSTRAINTS PURGE
/

--
-- SNP_TV  (Table) 
--
CREATE TABLE SNP_TV ( ID NUMBER NOT NULL, DB_SNP_ID VARCHAR2(20 BYTE) NOT NULL, VALIDATION_STATUS VARCHAR2(50 BYTE) NOT NULL, CHROMOSOME_ID NUMBER NOT NULL, ALLELE_A VARCHAR2(30 BYTE) NULL, ALLELE_B VARCHAR2(30 BYTE) NULL, FLANK VARCHAR2(55 BYTE) NULL, CHR_X_PSEUDO_AUTOSOMAL_REGION NUMBER NULL, CODING_STATUS VARCHAR2(10 BYTE) NULL, AMINO_ACID_CHANGE VARCHAR2(30 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT SNPTVPK PRIMARY KEY (ID), CONSTRAINT SNPTVUNIQ UNIQUE (DB_SNP_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


