/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE TARGET_AGENT
 DROP PRIMARY KEY CASCADE
/
DROP TABLE TARGET_AGENT CASCADE CONSTRAINTS PURGE
/

--
-- TARGET_AGENT  (Table) 
--
--  Dependencies: 
--   TARGET (Table)
--
CREATE TABLE TARGET_AGENT ( TARGET_ID NUMBER NOT NULL, AGENT_ID NUMBER NOT NULL, CONSTRAINT TAPK PRIMARY KEY (TARGET_ID, AGENT_ID), CONSTRAINT TAFK1 FOREIGN KEY (TARGET_ID) REFERENCES TARGET (TARGET_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


