/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE TISSUE_CLOSURE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE TISSUE_CLOSURE CASCADE CONSTRAINTS PURGE
/

--
-- TISSUE_CLOSURE  (Table) 
--
CREATE TABLE TISSUE_CLOSURE ( TISSUE_CODE NUMBER NOT NULL, ANCESTOR NUMBER NOT NULL, HIERARCHY_LEVEL NUMBER NULL, CONSTRAINT TCPK PRIMARY KEY (TISSUE_CODE, ANCESTOR) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


