/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_ARRAY_REPORTER_CH CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_ARRAY_REPORTER_CH  (Table) 
--
CREATE TABLE ZSTG_ARRAY_REPORTER_CH ( ID NUMBER NOT NULL, NAME VARCHAR2(500 BYTE) NOT NULL, MICROARRAY_ID NUMBER NULL, DISCRIMINATOR VARCHAR2(500 BYTE) NOT NULL, SEQUENCE_TYPE VARCHAR2(500 BYTE) NULL, SEQUENCE_SOURCE VARCHAR2(2500 BYTE) NULL, TARGET_ID VARCHAR2(2500 BYTE) NULL, TARGET_DESCRIPTION VARCHAR2(2500 BYTE) NULL, PHAST_CONSERVATION VARCHAR2(500 BYTE) NULL, MANUFACTURER_PSR_ID VARCHAR2(500 BYTE) NULL, PROBE_COUNT VARCHAR2(500 BYTE) NULL, STRAND VARCHAR2(500 BYTE) NULL, SNP_ID NUMBER NULL, NAS_ID NUMBER NULL, GENE_ID NUMBER NULL, TRANSCRIPT_ID NUMBER NULL, EXON_ID NUMBER NULL, BIG_ID VARCHAR2(500 BYTE) NULL, CHR_START NUMBER NULL, CHR_STOP NUMBER NULL, CYTO_START VARCHAR2(40 BYTE) NULL, CYTO_STOP VARCHAR2(40 BYTE) NULL, CHROMOSOME_ID NUMBER NULL, START_CYTOID NUMBER NULL, END_CYTOID NUMBER NULL, ASSEMBLY VARCHAR2(80 BYTE) DEFAULT 'reference' NULL, ORIG_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


