/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_GENE_ROLE_CGID
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE_ROLE_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE_ROLE_CGID  (Table) 
--
CREATE TABLE ZSTG_GENE_ROLE_CGID ( GENE_ID NUMBER NULL, ROLE_ID NVARCHAR2(500) NULL, PRIMARY KEY (GENE_ID, ROLE_ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


