/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_GENE2REFSEQ
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE2REFSEQ CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE2REFSEQ  (Table) 
--
CREATE TABLE ZSTG_GENE2REFSEQ ( TAX_ID NUMBER NOT NULL, GENEID NUMBER NOT NULL, STATUS VARCHAR2(50 BYTE) NOT NULL, RNA_NUCLEOTIDE_ACC VARCHAR2(50 BYTE) NOT NULL, RNA_NUCLEOTIDE_GI VARCHAR2(50 BYTE) NOT NULL, PROTEIN_ACCESSION VARCHAR2(50 BYTE) NOT NULL, PROTEIN_GI VARCHAR2(50 BYTE) NOT NULL, GENOMIC_NUCLEOTIDE_ACC VARCHAR2(50 BYTE) NOT NULL, GENOMIC_NUCLEOTIDE_GI VARCHAR2(50 BYTE) NOT NULL, START_POSITION VARCHAR2(50 BYTE) NOT NULL, END_POSITON VARCHAR2(50 BYTE) NOT NULL, ORIENTATION VARCHAR2(50 BYTE) NOT NULL, PROTEIN_ID NUMBER NOT NULL, ASSEMBLY VARCHAR2(2500 BYTE) NOT NULL, PRIMARY KEY (TAX_ID, GENEID, STATUS, RNA_NUCLEOTIDE_ACC, RNA_NUCLEOTIDE_GI, PROTEIN_ACCESSION, PROTEIN_GI, GENOMIC_NUCLEOTIDE_ACC, GENOMIC_NUCLEOTIDE_GI, START_POSITION, END_POSITON, ORIENTATION, PROTEIN_ID, ASSEMBLY) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


