/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_GENE_EXPRESSED_IN
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE_EXPRESSED_IN CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE_EXPRESSED_IN  (Table) 
--
CREATE TABLE ZSTG_GENE_EXPRESSED_IN ( GENE_ID NUMBER NOT NULL, ORGAN_ID NUMBER NOT NULL, PRIMARY KEY (GENE_ID, ORGAN_ID) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


