DROP TABLE ZSTG_CGH_AGILENT CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_CGH_AGILENT  (Table) 
--
CREATE TABLE ZSTG_CGH_AGILENT ( PROBE_SET_ID VARCHAR2(20 BYTE) NOT NULL, TARGET_ID VARCHAR2(40 BYTE) NOT NULL, GENE_SYMBOL VARCHAR2(20 BYTE) NULL, GENE_NAME VARCHAR2(255 BYTE) NULL, ACCESSIONS VARCHAR2(255 BYTE) NULL, DESCRIPTION VARCHAR2(1000 BYTE) NOT NULL, CHROMOSOME_NUMBER VARCHAR2(20 BYTE) NOT NULL, PROBE_START NUMBER NULL, PROBE_END NUMBER NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


