DROP TABLE ZSTG_HISTOLOGY_CODE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_HISTOLOGY_CODE  (Table) 
--
CREATE TABLE ZSTG_HISTOLOGY_CODE ( HISTOLOGY_CODE NUMBER NOT NULL, HISTOLOGY_NAME VARCHAR2(100 BYTE) NOT NULL, PARENT NUMBER NULL, CONCEPT_ID VARCHAR2(10 BYTE) NULL, RELATIONSHIP VARCHAR2(10 BYTE) NULL, EVS_ID VARCHAR2(50 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


