/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_STARTEXPRARRAYREPCYTOIDS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_STARTEXPRARRAYREPCYTOIDS  (Table) 
--
CREATE TABLE ZSTG_STARTEXPRARRAYREPCYTOIDS ( ID NUMBER NOT NULL, CYTO_START VARCHAR2(250 BYTE) NULL, CYTOBANDID NUMBER NOT NULL, CHROMOSOME_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


