/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_RNA_AGILENT CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_RNA_AGILENT  (Table) 
--
CREATE TABLE ZSTG_RNA_AGILENT ( PROBE_SET_ID VARCHAR2(20 BYTE) NOT NULL, PRIMARY_ACCESSION VARCHAR2(20 BYTE) NOT NULL, REF_SEQ_ACCESSION VARCHAR2(20 BYTE) NULL, GENBANK_ACCESSION VARCHAR2(20 BYTE) NULL, UNIGENE_ID VARCHAR2(20 BYTE) NULL, ENTREZ_GENE_ID VARCHAR2(20 BYTE) NULL, GENE_SYMBOL VARCHAR2(20 BYTE) NULL, GENE_NAME VARCHAR2(255 BYTE) NULL, ENSEMBL_ID VARCHAR2(20 BYTE) NULL, TIGR_ID VARCHAR2(20 BYTE) NULL, GO_ANNOTATION CLOB NOT NULL, DESCRIPTION VARCHAR2(1000 BYTE) NULL, COORDINATES VARCHAR2(100 BYTE) NULL, CYTOBAND VARCHAR2(100 BYTE) NULL, CYTOLOC VARCHAR2(50 BYTE) NULL, CYTO_START VARCHAR2(50 BYTE) NULL, CYTO_STOP VARCHAR2(50 BYTE) NULL, CHR_STOP NUMBER NULL, CHR_START NUMBER NULL, CHROMOSOME_NUMBER VARCHAR2(10 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS LOB (GO_ANNOTATION) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


