/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_BIOPATHWAY_DESCR CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_BIOPATHWAY_DESCR  (Table) 
--
CREATE TABLE ZSTG_BIOPATHWAY_DESCR ( PATH_ID VARCHAR2(30 BYTE) NOT NULL, PATHWAY_DESCR CLOB NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS LOB (PATHWAY_DESCR) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


