ALTER TABLE ZSTG_GENE_DISEASEONTO_CGID
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE_DISEASEONTO_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE_DISEASEONTO_CGID  (Table) 
--
CREATE TABLE ZSTG_GENE_DISEASEONTO_CGID ( GENE_ID NUMBER NOT NULL, DISEASE_ID NUMBER NOT NULL, PRIMARY KEY (GENE_ID, DISEASE_ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


