DROP TABLE ZSTG_CMAP_AGENTS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_CMAP_AGENTS  (Table) 
--
CREATE TABLE ZSTG_CMAP_AGENTS ( AGENT_ID NUMBER NOT NULL, AGENT_NAME VARCHAR2(120 BYTE) NULL, AGENT_SOURCE VARCHAR2(400 BYTE) NULL, AGENT_COMMENT VARCHAR2(400 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


