DROP TABLE ZSTG_INTERACTIONS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_INTERACTIONS  (Table) 
--
CREATE TABLE ZSTG_INTERACTIONS ( INTERACTION_TYPE VARCHAR2(2500 BYTE) NOT NULL, INTERACTION_ID VARCHAR2(2500 BYTE) NOT NULL, PATHWAY_IDREF VARCHAR2(2500 BYTE) NULL, PATHWAY_NAME VARCHAR2(2500 BYTE) NULL, EXTERNAL_PATHWAY_ID VARCHAR2(2500 BYTE) NULL, SOURCE_ID VARCHAR2(2500 BYTE) NOT NULL, SOURCE_NAME VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


