/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_PID_INTR_PARTPANT_LOC CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_INTR_PARTPANT_LOC  (Table) 
--
CREATE TABLE ZSTG_PID_INTR_PARTPANT_LOC ( INTERACTION_ID NUMBER NOT NULL, ORDER_OF_INTERACTION NUMBER NOT NULL, LOCATION VARCHAR2(2500 BYTE) NOT NULL, PID_PHYSICALENTITY_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


