/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_MISSING_DISEASEONTOL_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MISSING_DISEASEONTOL_CGID  (Table) 
--
CREATE TABLE ZSTG_MISSING_DISEASEONTOL_CGID ( DISEASEONTOLOGY VARCHAR2(2500 BYTE) NOT NULL, MATCHING_CONCEPT VARCHAR2(2500 BYTE) NULL, EVS_ID VARCHAR2(50 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


