/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_PROTEIN_EMBL
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_PROTEIN_EMBL CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PROTEIN_EMBL  (Table) 
--
CREATE TABLE ZSTG_PROTEIN_EMBL ( ID NUMBER NOT NULL, PROTEIN_ID NUMBER NOT NULL, ACC_NUM VARCHAR2(50 BYTE) NOT NULL, CONSTRAINT ZPEPK PRIMARY KEY (ID) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


