/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_INTERACTIONCOMPPTMTERMS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_INTERACTIONCOMPPTMTERMS  (Table) 
--
CREATE TABLE ZSTG_INTERACTIONCOMPPTMTERMS ( INTERACTION_ID VARCHAR2(2500 BYTE) NOT NULL, SOURCE_ID VARCHAR2(2500 BYTE) NOT NULL, MOLECULE_ID VARCHAR2(2500 BYTE) NOT NULL, ROLE_TYPE VARCHAR2(2500 BYTE) NOT NULL, PROTEIN VARCHAR2(2500 BYTE) NULL, POSITION VARCHAR2(2500 BYTE) NOT NULL, AA VARCHAR2(2500 BYTE) NOT NULL, MODIFICATION VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


