/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_PID_INTR_PARTCPANT_PTM CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_INTR_PARTCPANT_PTM  (Table) 
--
CREATE TABLE ZSTG_PID_INTR_PARTCPANT_PTM ( INTERACTION_ID NUMBER NOT NULL, ORDER_OF_INTERACTION NUMBER NOT NULL, PTM VARCHAR2(2500 BYTE) NOT NULL, PID_PHYSICALENTITY_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


