/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_GENE_HOMOLOGUE_REFERENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE_HOMOLOGUE_REFERENCE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE_HOMOLOGUE_REFERENCE  (Table) 
--
CREATE TABLE ZSTG_GENE_HOMOLOGUE_REFERENCE ( GENE_ID NUMBER NOT NULL, RELATED_GENE NUMBER NOT NULL, URL_OF_SOURCE NUMBER NOT NULL, PRIMARY KEY (GENE_ID, RELATED_GENE, URL_OF_SOURCE) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


