/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_CMAP_IDS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_CMAP_IDS  (Table) 
--
CREATE TABLE ZSTG_CMAP_IDS ( CMAP_ID NUMBER NOT NULL, GENE_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


