DROP TABLE ZSTG_GENE2ACCESSION CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE2ACCESSION  (Table) 
--
CREATE TABLE ZSTG_GENE2ACCESSION ( TAX_ID NUMBER NOT NULL, GENEID NUMBER NOT NULL, STATUS VARCHAR2(50 BYTE) NULL, RNA_NUCLEOTIDE_ACC VARCHAR2(50 BYTE) NOT NULL, RNA_NUCLEOTIDE_GI VARCHAR2(50 BYTE) NOT NULL, PROTEIN_ACCESSION VARCHAR2(50 BYTE) NOT NULL, PROTEIN_GI VARCHAR2(50 BYTE) NOT NULL, GENOMIC_NUCLEOTIDE_ACC VARCHAR2(50 BYTE) NOT NULL, GENOMIC_NUCLEOTIDE_GI VARCHAR2(50 BYTE) NOT NULL, START_POSITION VARCHAR2(50 BYTE) NOT NULL, END_POSITON VARCHAR2(50 BYTE) NOT NULL, ORIENTATION VARCHAR2(50 BYTE) NOT NULL, PROTEIN_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


