@$LOAD/indexes/ar_ec.drop.sql
@$LOAD/indexes/ar_ensembl.drop.sql
@$LOAD/indexes/ar_omim_id.drop.sql
@$LOAD/indexes/ar_rna_probesets_affy.drop.sql
@$LOAD/indexes/ar_alignments.drop.sql
@$LOAD/indexes/ar_chromosomal_location.drop.sql
@$LOAD/indexes/ar_entrez_gene.drop.sql
@$LOAD/indexes/ar_gene_symbol.drop.sql
@$LOAD/indexes/ar_gene_title.drop.sql
@$LOAD/indexes/ar_go_biological_process.drop.sql
@$LOAD/indexes/ar_go_cellular_component.drop.sql
@$LOAD/indexes/ar_go_molecular_function.drop.sql
@$LOAD/indexes/ar_pathway.drop.sql
@$LOAD/indexes/ar_refseq_protein.drop.sql
@$LOAD/indexes/ar_refseq_transcripts.drop.sql
@$LOAD/indexes/ar_representative_public_id.drop.sql
@$LOAD/indexes/ar_swissprot.drop.sql
@$LOAD/indexes/ar_unigene_id.drop.sql
@$LOAD/indexes/zstg_interpro.drop.sql
@$LOAD/indexes/zstg_rna_probesets.drop.sql
@$LOAD/indexes/zstg_genetic_map.drop.sql
@$LOAD/indexes/zstg_microsatellite.drop.sql
@$LOAD/indexes/zstg_pop_frequency.drop.sql
@$LOAD/indexes/zstg_snp_affy.drop.sql
@$LOAD/indexes/zstg_snp_associated_gene.drop.sql
@$LOAD/indexes/zstg_exon_affy.drop.sql
@$LOAD/indexes/zstg_exon_trans_affy.drop.sql
@$LOAD/indexes/zstg_exon_trans_genes.drop.sql
@$LOAD/indexes/ar_ensembl_tmp.drop.sql
@$LOAD/indexes/ar_omim_id_tmp.drop.sql
@$LOAD/indexes/ar_rna_probesets_affy_tmp.drop.sql
@$LOAD/indexes/ar_alignments_tmp.drop.sql
@$LOAD/indexes/ar_chromosomal_location_tmp.drop.sql
@$LOAD/indexes/ar_entrez_gene_tmp.drop.sql
@$LOAD/indexes/ar_gene_symbol_tmp.drop.sql
@$LOAD/indexes/ar_gene_title_tmp.drop.sql
@$LOAD/indexes/ar_go_biological_process_tmp.drop.sql
@$LOAD/indexes/ar_go_cellular_component_tmp.drop.sql
@$LOAD/indexes/ar_go_molecular_function_tmp.drop.sql
@$LOAD/indexes/ar_omim_id_tmp.drop.sql
@$LOAD/indexes/ar_pathway_tmp.drop.sql
@$LOAD/indexes/ar_refseq_protein_tmp.drop.sql
@$LOAD/indexes/ar_refseq_transcripts_tmp.drop.sql
@$LOAD/indexes/ar_rep_public_id_tmp.drop.sql
@$LOAD/indexes/ar_swissprot_tmp.drop.sql
@$LOAD/indexes/ar_unigene_id_tmp.drop.sql
@$LOAD/indexes/ar_ensembl_tmp.drop.sql
@$LOAD/indexes/ar_rna_probesets_affy_tmp.drop.sql
@$LOAD/indexes/zstg_rna_probesets_tmp.drop.sql
@$LOAD/indexes/zstg_rna_probesets.drop.sql
@$LOAD/indexes/zstg_interpro_tmp.drop.sql
@$LOAD/indexes/ar_ec_tmp.drop.sql
@$LOAD/indexes/zstg_snp_illumina.drop.sql
