@$LOAD/constraints/ar_ec.enable.sql
@$LOAD/constraints/ar_ensembl.enable.sql
@$LOAD/constraints/ar_omim_id.enable.sql
@$LOAD/constraints/ar_rna_probesets_affy.enable.sql
@$LOAD/constraints/ar_alignments.enable.sql
@$LOAD/constraints/ar_chromosomal_location.enable.sql
@$LOAD/constraints/ar_entrez_gene.enable.sql
@$LOAD/constraints/ar_gene_symbol.enable.sql
@$LOAD/constraints/ar_gene_title.enable.sql
@$LOAD/constraints/ar_go_biological_process.enable.sql
@$LOAD/constraints/ar_go_cellular_component.enable.sql
@$LOAD/constraints/ar_go_molecular_function.enable.sql
@$LOAD/constraints/ar_pathway.enable.sql
@$LOAD/constraints/ar_refseq_protein.enable.sql
@$LOAD/constraints/ar_refseq_transcripts.enable.sql
@$LOAD/constraints/ar_representative_public_id.enable.sql
@$LOAD/constraints/ar_swissprot.enable.sql
@$LOAD/constraints/ar_unigene_id.enable.sql
@$LOAD/constraints/zstg_interpro.enable.sql
@$LOAD/constraints/zstg_rna_probesets.enable.sql
@$LOAD/constraints/zstg_genetic_map.enable.sql
@$LOAD/constraints/zstg_microsatellite.enable.sql
@$LOAD/constraints/zstg_pop_frequency.enable.sql
@$LOAD/constraints/zstg_snp_affy.enable.sql
@$LOAD/constraints/zstg_snp_associated_gene.enable.sql
@$LOAD/constraints/zstg_exon_affy.enable.sql
@$LOAD/constraints/zstg_exon_trans_affy.enable.sql
@$LOAD/constraints/zstg_exon_trans_genes.enable.sql
@$LOAD/constraints/ar_ensembl_tmp.enable.sql
@$LOAD/constraints/ar_ec_tmp.enable.sql
@$LOAD/constraints/ar_omim_id_tmp.enable.sql
@$LOAD/constraints/ar_chromosomal_location_tmp.enable.sql
@$LOAD/constraints/ar_rna_probesets_affy_tmp.enable.sql
@$LOAD/constraints/ar_alignments_tmp.enable.sql
@$LOAD/constraints/ar_refseq_transcripts_tmp.enable.sql
@$LOAD/constraints/ar_entrez_gene_tmp.enable.sql
@$LOAD/constraints/ar_gene_symbol_tmp.enable.sql
@$LOAD/constraints/ar_gene_title_tmp.enable.sql
@$LOAD/constraints/ar_pathway_tmp.enable.sql
@$LOAD/constraints/ar_go_biological_process_tmp.enable.sql
@$LOAD/constraints/ar_go_cellular_component_tmp.enable.sql
@$LOAD/constraints/ar_go_molecular_function_tmp.enable.sql
@$LOAD/constraints/ar_refseq_protein_tmp.enable.sql
@$LOAD/constraints/ar_rep_public_id_tmp.enable.sql
@$LOAD/constraints/ar_swissprot_tmp.enable.sql
@$LOAD/constraints/ar_unigene_id_tmp.enable.sql
@$LOAD/constraints/zstg_interpro_tmp.enable.sql
@$LOAD/constraints/zstg_rna_probesets_tmp.enable.sql
