CREATE OR REPLACE FORCE VIEW CABIODEV.CONTEXT_VIEW
(TISSUE_NAME, HISTOLOGY_NAME)
AS 
SELECT tissue_name, histology_name
FROM TEMP_HISTOLOGY g, HISTOLOGY_CODE h, TISSUE_CODE t
WHERE g.TISSUE_CODE = t.TISSUE_CODE
AND g.HISTOLOGY_CODE = h.HISTOLOGY_CODE;


