CREATE OR REPLACE FORCE VIEW CABIODEV.PROTOCOL_TISSUE
(PRO_ID, TISSUE_CODE)
AS 
SELECT PRO_ID, IMT_TO_TISSUE.TISSUE_CODE FROM
PROTOCOL_DISEASES, IMT_TO_TISSUE
WHERE PROTOCOL_DISEASES.IMT_CODE = IMT_TO_TISSUE.IMT_CODE;


