@$LOAD/constraints.sql ar_ec
@$LOAD/constraints.sql ar_ec_tmp
@$LOAD/constraints.sql ar_ensembl
@$LOAD/constraints.sql ar_ensembl_tmp
@$LOAD/constraints.sql ar_omim_id
@$LOAD/constraints.sql ar_omim_id_tmp
@$LOAD/constraints.sql ar_rna_probesets_affy
@$LOAD/constraints.sql ar_rna_probesets_affy_tmp
@$LOAD/constraints.sql ar_alignments
@$LOAD/constraints.sql ar_alignments_tmp
@$LOAD/constraints.sql ar_chromosomal_location
@$LOAD/constraints.sql ar_chromosomal_location_tmp
@$LOAD/constraints.sql ar_entrez_gene
@$LOAD/constraints.sql ar_entrez_gene_tmp
@$LOAD/constraints.sql ar_gene_symbol
@$LOAD/constraints.sql ar_gene_symbol_tmp
@$LOAD/constraints.sql ar_gene_title
@$LOAD/constraints.sql ar_gene_title_tmp
@$LOAD/constraints.sql ar_go_biological_process
@$LOAD/constraints.sql ar_go_biological_process_tmp
@$LOAD/constraints.sql ar_go_cellular_component
@$LOAD/constraints.sql ar_go_cellular_component_tmp
@$LOAD/constraints.sql ar_go_molecular_function
@$LOAD/constraints.sql ar_go_molecular_function_tmp
@$LOAD/constraints.sql ar_pathway
@$LOAD/constraints.sql ar_pathway_tmp
@$LOAD/constraints.sql ar_refseq_protein
@$LOAD/constraints.sql ar_refseq_protein_tmp
@$LOAD/constraints.sql ar_refseq_transcripts
@$LOAD/constraints.sql ar_refseq_transcripts_tmp
@$LOAD/constraints.sql ar_representative_public_id
@$LOAD/constraints.sql ar_rep_public_id_tmp
@$LOAD/constraints.sql ar_swissprot
@$LOAD/constraints.sql ar_swissprot_tmp
@$LOAD/constraints.sql ar_unigene_id
@$LOAD/constraints.sql ar_unigene_id_tmp
@$LOAD/constraints.sql zstg_interpro
@$LOAD/constraints.sql zstg_interpro_tmp
@$LOAD/constraints.sql zstg_rna_probesets
@$LOAD/constraints.sql zstg_rna_probesets_tmp
@$LOAD/constraints.sql zstg_genetic_map
@$LOAD/constraints.sql zstg_microsatellite
@$LOAD/constraints.sql zstg_pop_frequency
@$LOAD/constraints.sql zstg_snp_affy
@$LOAD/constraints.sql zstg_snp_associated_gene
@$LOAD/constraints.sql zstg_exon_affy
@$LOAD/constraints.sql zstg_exon_trans_affy
@$LOAD/constraints.sql zstg_exon_trans_genes
@$LOAD/constraints.sql zstg_rna_agilent
@$LOAD/constraints.sql zstg_cgh_accessions
@$LOAD/constraints.sql zstg_cgh_agilent
@$LOAD/constraints.sql zstg_snp_illumina
@$LOAD/constraints.sql zstg_rna_probesets_tmp
