@$LOAD/constraints/ar_ec.disable.sql
@$LOAD/constraints/ar_ensembl.disable.sql
@$LOAD/constraints/ar_omim_id.disable.sql
@$LOAD/constraints/ar_rna_probesets_affy.disable.sql
@$LOAD/constraints/ar_alignments.disable.sql
@$LOAD/constraints/ar_chromosomal_location.disable.sql
@$LOAD/constraints/ar_entrez_gene.disable.sql
@$LOAD/constraints/ar_gene_symbol.disable.sql
@$LOAD/constraints/ar_gene_title.disable.sql
@$LOAD/constraints/ar_go_biological_process.disable.sql
@$LOAD/constraints/ar_go_cellular_component.disable.sql
@$LOAD/constraints/ar_go_molecular_function.disable.sql
@$LOAD/constraints/ar_pathway.disable.sql
@$LOAD/constraints/ar_refseq_protein.disable.sql
@$LOAD/constraints/ar_refseq_transcripts.disable.sql
@$LOAD/constraints/ar_representative_public_id.disable.sql
@$LOAD/constraints/ar_swissprot.disable.sql
@$LOAD/constraints/ar_unigene_id.disable.sql
@$LOAD/constraints/zstg_interpro.disable.sql
@$LOAD/constraints/zstg_rna_probesets.disable.sql
@$LOAD/constraints/zstg_genetic_map.disable.sql
@$LOAD/constraints/zstg_microsatellite.disable.sql
@$LOAD/constraints/zstg_pop_frequency.disable.sql
@$LOAD/constraints/zstg_snp_affy.disable.sql
@$LOAD/constraints/zstg_snp_associated_gene.disable.sql
@$LOAD/constraints/zstg_exon_affy.disable.sql
@$LOAD/constraints/zstg_exon_trans_affy.disable.sql
@$LOAD/constraints/zstg_exon_trans_genes.disable.sql
@$LOAD/constraints/ar_ensembl_tmp.disable.sql
@$LOAD/constraints/ar_ec_tmp.disable.sql
@$LOAD/constraints/ar_omim_id_tmp.disable.sql
@$LOAD/constraints/ar_chromosomal_location_tmp.disable.sql
@$LOAD/constraints/ar_rna_probesets_affy_tmp.disable.sql
@$LOAD/constraints/ar_alignments_tmp.disable.sql
@$LOAD/constraints/ar_refseq_transcripts_tmp.disable.sql
@$LOAD/constraints/ar_entrez_gene_tmp.disable.sql
@$LOAD/constraints/ar_gene_symbol_tmp.disable.sql
@$LOAD/constraints/ar_gene_title_tmp.disable.sql
@$LOAD/constraints/ar_pathway_tmp.disable.sql
@$LOAD/constraints/ar_go_biological_process_tmp.disable.sql
@$LOAD/constraints/ar_go_cellular_component_tmp.disable.sql
@$LOAD/constraints/ar_go_molecular_function_tmp.disable.sql
@$LOAD/constraints/ar_refseq_protein_tmp.disable.sql
@$LOAD/constraints/ar_rep_public_id_tmp.disable.sql
@$LOAD/constraints/ar_swissprot_tmp.disable.sql
@$LOAD/constraints/ar_unigene_id_tmp.disable.sql
@$LOAD/constraints/zstg_interpro_tmp.disable.sql
@$LOAD/constraints/zstg_rna_probesets_tmp.disable.sql
@$LOAD/constraints/zstg_rna_agilent.disable.sql
@$LOAD/constraints/zstg_cgh_accessions.disable.sql
@$LOAD/constraints/zstg_cgh_agilent.disable.sql
@$LOAD/constraints/zstg_snp_illumina.disable.sql
