@$LOAD/constraints/ar_ec.enable.sql
@$LOAD/constraints/ar_ensembl.enable.sql
@$LOAD/constraints/ar_omim.enable.sql
@$LOAD/constraints/ar_rna_probesets_affy.enable.sql
@$LOAD/constraints/ar_alignments.enable.sql
@$LOAD/constraints/ar_chromosomal_location.enable.sql
@$LOAD/constraints/ar_entrez_gene.enable.sql
@$LOAD/constraints/ar_gene_symbol.enable.sql
@$LOAD/constraints/ar_gene_title.enable.sql
@$LOAD/constraints/ar_go_biological_process.enable.sql
@$LOAD/constraints/ar_go_cellular_component.enable.sql
@$LOAD/constraints/ar_go_molecular_function.enable.sql
@$LOAD/constraints/ar_pathway.enable.sql
@$LOAD/constraints/ar_refseq_protein.enable.sql
@$LOAD/constraints/ar_refseq_transcripts.enable.sql
@$LOAD/constraints/ar_representative_public_id.enable.sql
@$LOAD/constraints/ar_swissprot.enable.sql
@$LOAD/constraints/ar_unigene_id.enable.sql
@$LOAD/constraints/zstg_interpro.enable.sql
@$LOAD/constraints/zstg_rna_probesets.enable.sql
@$LOAD/constraints/zstg_genetic_map.enable.sql
@$LOAD/constraints/zstg_microsatellite.enable.sql
@$LOAD/constraints/zstg_pop_frequency.enable.sql
@$LOAD/constraints/zstg_snp_affy.enable.sql
@$LOAD/constraints/zstg_snp_associated_gene.enable.sql
@$LOAD/constraints/zstg_exon_affy.enable.sql
@$LOAD/constraints/zstg_exon_trans_affy.enable.sql
@$LOAD/constraints/zstg_exon_trans_genes.enable.sql
@$LOAD/constraints/ar_ensembl.enable.sql
@$LOAD/constraints/ar_ec.enable.sql
@$LOAD/constraints/ar_omim.enable.sql
@$LOAD/constraints/ar_chromosomal_location.enable.sql
@$LOAD/constraints/ar_rna_probesets_affy.enable.sql
@$LOAD/constraints/ar_alignments.enable.sql
@$LOAD/constraints/ar_refseq_transcripts.enable.sql
@$LOAD/constraints/ar_entrez_gene.enable.sql
@$LOAD/constraints/ar_gene_symbol.enable.sql
@$LOAD/constraints/ar_gene_title.enable.sql
@$LOAD/constraints/ar_pathway.enable.sql
@$LOAD/constraints/ar_go_biological_process.enable.sql
@$LOAD/constraints/ar_go_cellular_component.enable.sql
@$LOAD/constraints/ar_go_molecular_function.enable.sql
@$LOAD/constraints/ar_refseq_protein.enable.sql
@$LOAD/constraints/ar_representative_public_id.enable.sql
@$LOAD/constraints/ar_swissprot.enable.sql
@$LOAD/constraints/ar_unigene_id.enable.sql
@$LOAD/constraints/zstg_interpro.enable.sql
@$LOAD/constraints/zstg_rna_probesets.enable.sql
@$LOAD/constraints/zstg_rna_agilent.enable.sql
@$LOAD/constraints/zstg_cgh_accessions.enable.sql
@$LOAD/constraints/zstg_cgh_agilent.enable.sql
@$LOAD/constraints/zstg_snp_illumina.enable.sql
