$SQLPLUS $1 @pidData_preprocess.sql
$SQLLDR $1 readsize=1000000 parallel=true control=InteractionComponentLabel.ctl log=InteractionComponentLabel.log bad=InteractionComponentLabel.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=InteractionComponentPTMTerms.ctl log=InteractionComponentPTMTerms.log bad=InteractionComponentPTMTerms.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=InteractionCondition.ctl log=InteractionCondition.log bad=InteractionCondition.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=InteractionEvidence.ctl log=InteractionEvidence.log bad=InteractionEvidence.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=InteractionReference.ctl log=InteractionReference.log bad=InteractionReference.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=Interactions.ctl log=Interactions.log bad=Interactions.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=MoleculeComponentLabel.ctl log=MoleculeComponentLabel.log bad=MoleculeComponentLabel.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=MoleculeComponentPTMTerms.ctl log=MoleculeComponentPTMTerms.log bad=MoleculeComponentPTMTerms.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=MoleculeFamilies.ctl log=MoleculeFamilies.log bad=MoleculeFamilies.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=MoleculeNames.ctl log=MoleculeNames.log bad=MoleculeNames.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=MoleculeParts.ctl log=MoleculeParts.log bad=MoleculeParts.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=PathwayComponents.ctl log=PathwayComponents.log bad=PathwayComponents.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=PathwayCurators.ctl log=PathwayCurators.log bad=PathwayCurators.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=PathwayReviewers.ctl log=PathwayReviewers.log bad=PathwayReviewers.bad errors=50000 direct=true silent=(HEADER)
$SQLLDR $1 readsize=1000000 parallel=true control=Pathways.ctl log=Pathways.log bad=Pathways.bad errors=50000 direct=true silent=(HEADER)
$SQLPLUS $1 @pidData_postprocess.sql
