DROP TABLE AR_EC_TMP CASCADE CONSTRAINTS PURGE
/

--
-- AR_EC_TMP  (Table) 
--
CREATE TABLE AR_EC_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, EC VARCHAR2(20 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT ) MONITORING
/


