DROP TABLE AR_GO_CELLULAR_COMPONENT CASCADE CONSTRAINTS PURGE
/

--
-- AR_GO_CELLULAR_COMPONENT  (Table) 
--
CREATE TABLE AR_GO_CELLULAR_COMPONENT ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, ACCESSION_NUMBER NUMBER NOT NULL, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL, EVIDENCE VARCHAR2(100 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


