DROP TABLE AR_PATHWAY CASCADE CONSTRAINTS PURGE
/

--
-- AR_PATHWAY  (Table) 
--
CREATE TABLE AR_PATHWAY ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, PATHWAY VARCHAR2(100 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


