DROP TABLE ENGINEEREDGENE CASCADE CONSTRAINTS PURGE
/

--
-- ENGINEEREDGENE  (Table) 
--
CREATE TABLE ENGINEEREDGENE ( ENGINEEREDGENE_ID NUMBER NOT NULL, NAME VARCHAR2(255 BYTE) NULL, DBCROSSREFS VARCHAR2(255 BYTE) NULL, LOCUSLINKSUMMARY VARCHAR2(255 BYTE) NULL, TITLE VARCHAR2(255 BYTE) NULL, CABIOID NUMBER NULL, CONDITIONALITY_ID NUMBER NULL, GENOTYPESUMMARY_ID NUMBER NULL, IMAGE_ID NUMBER NULL, GENOMICSEGMENT_ID NUMBER NULL, INDUCEDMUTATION_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


