ALTER TABLE EVIDENCE_EVIDENCE_CODE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EVIDENCE_EVIDENCE_CODE CASCADE CONSTRAINTS PURGE
/

--
-- EVIDENCE_EVIDENCE_CODE  (Table) 
--
CREATE TABLE EVIDENCE_EVIDENCE_CODE ( EVIDENCE_ID NUMBER NULL, EVIDENCE_CODE_ID NUMBER NULL, CONSTRAINT EV_EVCODE_PK PRIMARY KEY (EVIDENCE_CODE_ID, EVIDENCE_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


