DROP TABLE GENE CASCADE CONSTRAINTS PURGE
/

--
-- GENE  (Table) 
--
CREATE TABLE GENE ( GENE_ID NUMBER NOT NULL, GENE_SYMBOL VARCHAR2(50 BYTE) NULL, GENE_TITLE VARCHAR2(2000 BYTE) NOT NULL, CHROMOSOME_ID NUMBER NULL, TAXON_ID NUMBER NOT NULL, CLUSTER_ID NUMBER NOT NULL, LOCUS_LINK_SUMMARY VARCHAR2(4000 BYTE) NULL, ENGINEEREDGENE_ID NUMBER NULL, LOCUS_LINK_ID VARCHAR2(50 BYTE) NULL, OMIM_ID VARCHAR2(50 BYTE) NULL, UNIQUE (GENE_ID, GENE_SYMBOL, GENE_TITLE, CHROMOSOME_ID, TAXON_ID, CLUSTER_ID, LOCUS_LINK_SUMMARY, ENGINEEREDGENE_ID, LOCUS_LINK_ID, OMIM_ID) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


