ALTER TABLE LOCATION_TV
 DROP PRIMARY KEY CASCADE
/
DROP TABLE LOCATION_TV CASCADE CONSTRAINTS PURGE
/

--
-- LOCATION_TV  (Table) 
--
--  Dependencies: 
--   EXON_REPORTER (Table)
--   TRANSCRIPT (Table)
--   MARKER (Table)
--   SNP_TV (Table)
--   GENE_TV (Table)
--   CHROMOSOME (Table)
--   NUCLEIC_ACID_SEQUENCE (Table)
--
CREATE TABLE LOCATION_TV ( ID NUMBER NOT NULL, GENE_ID NUMBER NULL, NUCLEIC_ACID_ID NUMBER NULL, SNP_ID NUMBER NULL, CHROMOSOME_ID NUMBER NOT NULL, TRANSCRIPT_ID NUMBER NULL, EXON_REPORTER_ID NUMBER NULL, CYTOBAND_ID NUMBER NULL, MARKER_ID NUMBER NULL, CONSTRAINT LOC_TV_PK PRIMARY KEY (ID), CONSTRAINT LCHEXREPFK FOREIGN KEY (EXON_REPORTER_ID) REFERENCES EXON_REPORTER (ID), CONSTRAINT LCHXSCRIPTID FOREIGN KEY (TRANSCRIPT_ID) REFERENCES TRANSCRIPT (ID), CONSTRAINT LOCTVMKFK FOREIGN KEY (MARKER_ID) REFERENCES MARKER (ID), CONSTRAINT LTVSNPFK FOREIGN KEY (SNP_ID) REFERENCES SNP_TV (ID), CONSTRAINT LTV_GENE FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), CONSTRAINT LT_CHR FOREIGN KEY (CHROMOSOME_ID) REFERENCES CHROMOSOME (CHROMOSOME_ID), CONSTRAINT LT_NAS FOREIGN KEY (NUCLEIC_ACID_ID) REFERENCES NUCLEIC_ACID_SEQUENCE (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


