ALTER TABLE OLD_PROTOCOL_AGENTS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE OLD_PROTOCOL_AGENTS CASCADE CONSTRAINTS PURGE
/

--
-- OLD_PROTOCOL_AGENTS  (Table) 
--
CREATE TABLE OLD_PROTOCOL_AGENTS ( PRO_ID NUMBER(10) NOT NULL, AGENT_ID NUMBER NOT NULL, CONSTRAINT OPAPK PRIMARY KEY (AGENT_ID, PRO_ID) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


