ALTER TABLE PID_PARTICIPANT
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_PARTICIPANT CASCADE CONSTRAINTS PURGE
/

--
-- PID_PARTICIPANT  (Table) 
--
--  Dependencies: 
--   PID_INTERACTION (Table)
--   PID_PHYSICAL_ENTITY (Table)
--
CREATE TABLE PID_PARTICIPANT ( ID NUMBER NOT NULL, LOCATION VARCHAR2(2500 BYTE) NULL, PTM VARCHAR2(2500 BYTE) NULL, ACTIVITY_STATE VARCHAR2(2500 BYTE) NULL, CONDITION_NAME VARCHAR2(2500 BYTE) NULL, DISCRIMINATOR VARCHAR2(2500 BYTE) NOT NULL, INTERACTION_ID NUMBER NULL, COMPLEX_ENTITY_ID NUMBER NULL, PHYSICAL_ENTITY_ID NUMBER NULL, PID_INTERACTION_ID NUMBER NULL, PID_PHYSICALENTITY_ID NUMBER NULL, PID_COMPLEX_COMPONENT_ID NUMBER NULL, PID_COMPLEX_COMPONENT_ORDER NUMBER NULL, BIG_ID VARCHAR2(2500 BYTE) NULL, PID_FAMILY_ID NUMBER NULL, PID_MEMBER_ID NUMBER NULL, PID_COMPLEX_ENTITY_ID NUMBER NULL, PRIMARY KEY (ID), FOREIGN KEY (INTERACTION_ID) REFERENCES PID_INTERACTION (ID), FOREIGN KEY (COMPLEX_ENTITY_ID) REFERENCES PID_PHYSICAL_ENTITY (ID), FOREIGN KEY (PHYSICAL_ENTITY_ID) REFERENCES PID_PHYSICAL_ENTITY (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


