DROP TABLE SNPCYTOIDS CASCADE CONSTRAINTS PURGE
/

--
-- SNPCYTOIDS  (Table) 
--
CREATE TABLE SNPCYTOIDS ( DBSNP_RS_ID VARCHAR2(20 BYTE) NOT NULL, CYTOBAND VARCHAR2(20 BYTE) NOT NULL, ID NUMBER NOT NULL, CHROMOSOME_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


