DROP TABLE STG_KEYWORD CASCADE CONSTRAINTS PURGE
/

--
-- STG_KEYWORD  (Table) 
--
CREATE TABLE STG_KEYWORD ( SCORE NUMBER NULL, VALUE VARCHAR2(512 BYTE) NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


