ALTER TABLE TRANSCRIPT_ARRAY_REPORTER
 DROP PRIMARY KEY CASCADE
/
DROP TABLE TRANSCRIPT_ARRAY_REPORTER CASCADE CONSTRAINTS PURGE
/

--
-- TRANSCRIPT_ARRAY_REPORTER  (Table) 
--
--  Dependencies: 
--   MICROARRAY (Table)
--
CREATE TABLE TRANSCRIPT_ARRAY_REPORTER ( ID NUMBER NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, MICROARRAY_ID NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CHECK ("BIG_ID" IS NOT NULL) DISABLE, CONSTRAINT TRANSCRIPT_REPORTER_PK PRIMARY KEY (ID), UNIQUE (NAME, MICROARRAY_ID), CONSTRAINT XSCRIPTARRREP UNIQUE (BIG_ID) DISABLE, CONSTRAINT TARFK FOREIGN KEY (MICROARRAY_ID) REFERENCES MICROARRAY (ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


