DROP TABLE ZSTG_ENDCYTOIDS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_ENDCYTOIDS  (Table) 
--
CREATE TABLE ZSTG_ENDCYTOIDS ( GENE_ID NUMBER NOT NULL, END_CYTOBAND VARCHAR2(50 BYTE) NULL, ID NUMBER NOT NULL, CHROMOSOME_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


