DROP TABLE ZSTG_GENEALIAS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENEALIAS  (Table) 
--
CREATE TABLE ZSTG_GENEALIAS ( LOCUSLINKID VARCHAR2(30 BYTE) NULL, SYMBOL VARCHAR2(2500 BYTE) NOT NULL, SYNONYMS VARCHAR2(100 BYTE) NULL, TYPE VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


