DROP TABLE ZSTG_MISSING_AGENT_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MISSING_AGENT_CGID  (Table) 
--
CREATE TABLE ZSTG_MISSING_AGENT_CGID ( DRUG VARCHAR2(2500 BYTE) NOT NULL, MATCHING_CONCEPT VARCHAR2(2500 BYTE) NOT NULL, EVS_ID VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


