DROP TABLE ZSTG_PID_EVIDENCECODE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_EVIDENCECODE  (Table) 
--
CREATE TABLE ZSTG_PID_EVIDENCECODE ( PID_EVIDENCECODEID NUMBER NOT NULL, EVIDENCEKIND VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


