DROP TABLE ZSTG_OLD_PROTOCOL_DISEASES CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_OLD_PROTOCOL_DISEASES  (Table) 
--
CREATE TABLE ZSTG_OLD_PROTOCOL_DISEASES ( ID NUMBER(10) NOT NULL, PRO_ID NUMBER(10) NOT NULL, IMT_CODE NUMBER(8) NULL, CTEP_NAME VARCHAR2(100 BYTE) NOT NULL, DISEASE_SUB_CATEGORY VARCHAR2(255 BYTE) NOT NULL, DISEASE_CATEGORY VARCHAR2(255 BYTE) NOT NULL, HISTOLOGY_CODE NUMBER NULL, CONCEPT_ID VARCHAR2(10 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


