DROP TABLE ZSTG_BIO_PATHWAYS_TV CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_BIO_PATHWAYS_TV  (Table) 
--
CREATE TABLE ZSTG_BIO_PATHWAYS_TV ( PATHWAY_ID NUMBER NOT NULL, PATHWAY_NAME VARCHAR2(30 BYTE) NOT NULL, PATHWAY_DISPLAY VARCHAR2(200 BYTE) NOT NULL, TAXON NUMBER NOT NULL, PATHWAY_DIAGRAM_NAME VARCHAR2(50 BYTE) NULL, PATHWAY_DESC CLOB NULL, PATHWAY_DIAGRAM CLOB NULL, BIG_ID VARCHAR2(200 BYTE) NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS LOB (PATHWAY_DESC) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (PATHWAY_DIAGRAM) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


