DROP TABLE ZSTG_SNPCYTOIDS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_SNPCYTOIDS  (Table) 
--
CREATE TABLE ZSTG_SNPCYTOIDS ( DBSNP_RS_ID VARCHAR2(20 BYTE) NOT NULL, CYTOBAND VARCHAR2(20 BYTE) NOT NULL, ID NUMBER NOT NULL, CHROMOSOME_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


