DROP TABLE ZSTG_PID_GENEENTITY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_GENEENTITY  (Table) 
--
CREATE TABLE ZSTG_PID_GENEENTITY ( IDENTIFIER VARCHAR2(2500 BYTE) NOT NULL, PID_PE_ID VARCHAR2(4000 BYTE) NULL, LOCUSLINK VARCHAR2(4000 BYTE) NULL, UNIGENE_CLUSTER VARCHAR2(4000 BYTE) NULL ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


