
drop index AR_CHROM_TMP_GENECHIP_A;
drop index AR_CHROM_TMP_ASSEMBLY;
drop index AR_CHROM_TMP_TRIM_CHR;
drop index AR_CHROM_TMP_CYTO_STOP;
drop index AR_CHROM_TMP_CYTO_START;
drop index AR_CHROM_TMP_CHROMOSOME;
drop index AR_CHROM_TMP_CHROMOSOMA;
drop index AR_CHROM_TMP_PROBE_SET_;
drop index SYS_C0021041_IDX;

--EXIT;
