
create index AR_GO_CENENT_GENECHIP_A on AR_GO_CELLULAR_COMPONENT(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CENENT_EVIDENCE on AR_GO_CELLULAR_COMPONENT(EVIDENCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CENENT_DESCRIPTIO on AR_GO_CELLULAR_COMPONENT(DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CENENT_ACCESSION_ on AR_GO_CELLULAR_COMPONENT(ACCESSION_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CENENT_PROBE_SET_ on AR_GO_CELLULAR_COMPONENT(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
