
drop index BIOGENESENES_BC_ID_LWR;
drop index BIOGENESENES_BIOGENES_I;
drop index BIOGENESENES_ORGANISM;
drop index BIOGENESENES_BC_ID;
drop index BIOGENESENES_LOCUS_ID;
drop index BIOGENESENES_GENE_ID;

--EXIT;
