
create index HISTOPAT_TST_ORGAN_ID_lwr on HISTOPATHOLOGY_TST(lower(ORGAN_ID)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_AGEOFONSET_lwr on HISTOPATHOLOGY_TST(lower(AGEOFONSET)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_GROSSDESCR_lwr on HISTOPATHOLOGY_TST(lower(GROSSDESCRIPTION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_MICROSCOPI_lwr on HISTOPATHOLOGY_TST(lower(MICROSCOPICDESCRIPTION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_RELATIONAL_lwr on HISTOPATHOLOGY_TST(lower(RELATIONALOPERATION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_COMMENTS_lwr on HISTOPATHOLOGY_TST(lower(COMMENTS)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_SURVIVALIN_lwr on HISTOPATHOLOGY_TST(lower(SURVIVALINFO)) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
