
drop index SYS_C0021119_IDX;
drop index MARKERRKER_ACCNO_LWR;
drop index MARKERRKER_TYPE_LWR;
drop index MARKERRKER_MARKER_ID_LWR;
drop index MARKERRKER_NAME_LWR;
drop index MARKERRKER_ACCNO;
drop index MARKERRKER_TAXON_ID;
drop index MARKERRKER_TYPE;
drop index MARKERRKER_MARKER_ID;
drop index MARKERRKER_NAME;
drop index MARKERRKER_ID;
drop index MARKERKER_BIG_ID;
drop index MARKERKER_BIG_ID_LWR;

--EXIT;
