
drop index MARKER_ION_BIG_ID_LWR;
drop index MARKER_RTION_PROBE_SET__LWR;
drop index MARKER_RTION_DISTANCE_LWR;
drop index MARKER_RTION_ORIENTATIO_LWR;
drop index MARKER_RTION_TYPE_LWR;
drop index MARKER_RTION_PROBE_SET_;
drop index MARKER_RTION_SNP_ID;
drop index MARKER_RTION_DISTANCE;
drop index MARKER_RTION_ORIENTATIO;
drop index MARKER_RTION_TYPE;
drop index MARKER_RTION_ID;
drop index MARKER_ION_BIG_ID;

--EXIT;
