
drop index SYS_C0021124_IDX;
drop index MICROARRRRAY_LSID;
drop index MICROARRRRAY_ACCESSION;
drop index MICROARRRRAY_DESCRIPTIO;
drop index MICROARRRRAY_TYPE;
drop index MICROARRRRAY_PLATFORM;
drop index MICROARRRRAY_DBSNP_VERS;
drop index MICROARRRRAY_GENOME_VER;
drop index MICROARRRRAY_ANNOTATION;
drop index MICROARRRRAY_ARRAY_NAME;
drop index MICROARRRRAY_ID;
drop index MICROARRAY_BIG_ID;
drop index MICROARRAY_BIG_ID_LWR;

--EXIT;
