
drop index PID_INTETION_DISCRIMINA_LWR;
drop index PID_INTETION_SOURCE;
drop index PID_INTETION_ID;
drop index PID_INTETION_PID_INTERA;
drop index PID_INTETION_MACRO_NAME;
drop index PID_INTETION_DISCRIMINA;
drop index PID_INTETION_SOURCE_LWR;
drop index PID_INTETION_MACRO_NAME_LWR;
drop index PID_INTETION_REF_PATHWA;

--EXIT;
