/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index PID_PHYSTITY_PID_PHYSIC on PID_PHYSICAL_ENTITY(PID_PHYSICALENTITY_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PID_PHYSTITY_PROTEIN_EN on PID_PHYSICAL_ENTITY(PROTEIN_ENTITY_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PID_PHYSTITY_DISCRIMINA on PID_PHYSICAL_ENTITY(DISCRIMINATOR) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PID_PHYSTITY_PROT_SUBUN on PID_PHYSICAL_ENTITY(PROT_SUBUNIT_STOP) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PID_PHYSTITY_PROT_SUBUN on PID_PHYSICAL_ENTITY(PROT_SUBUNIT_START) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PID_PHYSTITY_ID on PID_PHYSICAL_ENTITY(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PID_PHYSTITY_ORDER_OF_C on PID_PHYSICAL_ENTITY(ORDER_OF_COMPONENT) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
