
drop index POPULATIENCY_TYPE_LWR;
drop index POPULATIENCY_ETHNICITY_LWR;
drop index POPULATIENCY_MAJOR_ALLE_LWR;
drop index POPULATIENCY_MINOR_ALLE_LWR;
drop index POPULATIENCY_SNP_PROBES_LWR;
drop index POPULATIENCY_ID;
drop index POPULATIENCY_TYPE;
drop index POPULATIENCY_ETHNICITY;
drop index POPULATIENCY_MAJOR_FREQ;
drop index POPULATIENCY_MINOR_FREQ;
drop index POPULATIENCY_HETEROZYGO;
drop index POPULATIENCY_SNP_ID;
drop index POPULATIENCY_MAJOR_ALLE;
drop index POPULATIENCY_MINOR_ALLE;
drop index POPULATIENCY_SNP_PROBES;
drop index POPULATNCY_BIG_ID_LWR;
drop index POPULATNCY_BIG_ID;

--EXIT;
