
drop index PABIGID;
drop index PROTEINOTEIN_ALIAS_BIG_ID_LWR;
drop index PROTEIN_LIAS_NAME;
drop index PROTEIN_LIAS_PROTEIN_ID;
drop index PROTEIN_LIAS_ID;
drop index PROTEIN_LIAS_NAME_LWR;

--EXIT;
