
drop index PROTEINIAS_BIG_ID_LWR;
drop index PROTEINIAS_BIG_ID;
drop index PROTEIN_LIAS_ID;
drop index PROTEIN_LIAS_PROTEIN_ID;
drop index PROTEIN_LIAS_NAME;
drop index PROTEIN_LIAS_NAME_LWR;

--EXIT;
