
drop index SYS_C0021171_IDX;
drop index PROTEIN_ENCE_ID;
drop index PROTEIN_ENCE_LENGTH;
drop index PROTEIN_ENCE_PROTEIN_ID;
drop index PROTEIN_ENCE_CHECKSUM;
drop index PROTEIN_ENCE_DALTONWEIG;
drop index PROTEIN_ENCE_CHECKSUM_LWR;
drop index PROTEINNCE_BIG_ID;
drop index PROTEINNCE_BIG_ID_LWR;
drop index SYS_IL0000012720C00004$$;

--EXIT;
