
drop index PROTEIN_MAIN_TYPE;
drop index PROTEIN_MAIN_DESCRIPTIO;
drop index PROTEIN_MAIN_ACCESSION_;
drop index PROTEIN_MAIN_ID;
drop index SYS_C0021167_IDX;
drop index PROTEIN_MAIN_TYPE_LWR;
drop index PROTEIN_MAIN_DESCRIPTIO_LWR;
drop index PROTEIN_MAIN_ACCESSION__LWR;
drop index PROTEINAIN_BIG_ID;
drop index PROTEINAIN_BIG_ID_LWR;

--EXIT;
