
drop index RELATIVEN_CH_TYPE_LWR;
drop index RELATIVEN_CH_PROBE_SET__LWR;
drop index RELATIVEN_CH_DISTANCE_LWR;
drop index RELATIVEN_CH_GENE_ID;
drop index RELATIVEN_CH_DISCRIMINA;
drop index RELATIVEN_CH_PROBE_SET_;
drop index RELATIVEN_CH_DISTANCE;
drop index RELATIVEN_CH_SNP_ID;
drop index RELATIVE_LOC_BIGID_LWR;
drop index RELATIVEN_CH_ORIENTATIO_LWR;
drop index RELATIVEN_CH_ORIENTATIO;
drop index RELATIVEN_CH_TYPE;
drop index RELATIVEN_CH_ID;
drop index RELATIVEN_CH_DISCRIMINA_LWR;
drop index RELATIV_CH_BIG_ID;

--EXIT;
