
drop index ZSTG_MISCGID_DRUG;
drop index ZSTG_MISCGID_MATCHING_C;
drop index ZSTG_MISCGID_EVS_ID;
drop index ZSTG_MISCGID_DRUG_LWR;
drop index ZSTG_MISCGID_MATCHING_C_LWR;
drop index ZSTG_MISCGID_EVS_ID_LWR;

--EXIT;
