
drop index ZSTG_INTTION_INTERACTIO_LWR;
drop index ZSTG_INTTION_SOURCE_ID_LWR;
drop index ZSTG_INTTION_CONDITION__LWR;
drop index ZSTG_INTTION_CONDITION_LWR;
drop index ZSTG_INTTION_INTERACTIO;
drop index ZSTG_INTTION_SOURCE_ID;
drop index ZSTG_INTTION_CONDITION_;
drop index ZSTG_INTTION_CONDITION;

--EXIT;
