
drop index ZSTG_SNPRTER_CYTO_STOP;
drop index ZSTG_SNPRTER_CYTO_START;
drop index ZSTG_SNPRTER_CHR_STOP;
drop index ZSTG_SNPRTER_CHR_START;
drop index ZSTG_SNPRTER_CHROMOSOME;
drop index ZSTG_SNPRTER_PHAST_CONS;
drop index ZSTG_SNPRTER_SNP_ID;
drop index ZSTG_SNPRTER_MICROARRAY;
drop index ZSTG_SNPRTER_NAME;
drop index ZSTG_SNPRTER_ID;

--EXIT;
