
drop index ZSTG_MAP_MAP_MAP_TYPE;
drop index ZSTG_MAP_MAP_MAP_ID;
drop index ZSTG_MAP_MAP_END_CYTOBA;
drop index ZSTG_MAP_MAP_START_CYTO;
drop index ZSTG_MAP_MAP_CHROMOSOME;
drop index ZSTG_MAP_MAP_CYTOBAND;
drop index ZSTG_MAP_MAP_TAXON_ID;
drop index ZSTG_MAP_MAP_MAP_LOCATI;

--EXIT;
