
drop index SYS_C0020836_IDX;
drop index ZSTG_GENFSEQ_TAX_ID;
drop index ZSTG_GENFSEQ_GENEID;
drop index ZSTG_GENFSEQ_STATUS;
drop index ZSTG_GENFSEQ_RNA_NUCLEO;
drop index ZSTG_GENFSEQ_PROTEIN_AC;
drop index ZSTG_GENFSEQ_PROTEIN_GI;
drop index ZSTG_GENFSEQ_GENOMIC_NU;
drop index ZSTG_GENFSEQ_START_POSI;
drop index ZSTG_GENFSEQ_END_POSITO;
drop index ZSTG_GENFSEQ_ORIENTATIO;
drop index ZSTG_GENFSEQ_PROTEIN_ID;
drop index ZSTG_GENFSEQ_ASSEMBLY;

--EXIT;
