
drop index ZSTG_GENGENE_START_CYTO;
drop index ZSTG_GENGENE_IDENTIFIER;
drop index ZSTG_GENGENE_DATA_SOURC;
drop index ZSTG_GENGENE_CYTOBAND;
drop index ZSTG_GENGENE_GENE_SYMBO;
drop index ZSTG_GENGENE_CHROMOSOME;
drop index ZSTG_GENGENE_TAXON_ID;
drop index ZSTG_GENGENE_GENE_ID;
drop index ZSTG_GENGENE_GENE_TITLE;
drop index ZSTG_GENGENE_END_CYTOBA;

--EXIT;
