
create index ZSTG_RNALENT_PROBE_SET_ on ZSTG_RNA_AGILENT(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_PRIMARY_AC on ZSTG_RNA_AGILENT(PRIMARY_ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_REF_SEQ_AC on ZSTG_RNA_AGILENT(REF_SEQ_ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_GENBANK_AC on ZSTG_RNA_AGILENT(GENBANK_ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_UNIGENE_ID on ZSTG_RNA_AGILENT(UNIGENE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_ENTREZ_GEN on ZSTG_RNA_AGILENT(ENTREZ_GENE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_GENE_SYMBO on ZSTG_RNA_AGILENT(GENE_SYMBOL) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_GENE_NAME on ZSTG_RNA_AGILENT(GENE_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_ENSEMBL_ID on ZSTG_RNA_AGILENT(ENSEMBL_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_TIGR_ID on ZSTG_RNA_AGILENT(TIGR_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_DESCRIPTIO on ZSTG_RNA_AGILENT(DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_COORDINATE on ZSTG_RNA_AGILENT(COORDINATES) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_CYTOBAND on ZSTG_RNA_AGILENT(CYTOBAND) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_CYTOLOC on ZSTG_RNA_AGILENT(CYTOLOC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_CYTO_START on ZSTG_RNA_AGILENT(CYTO_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_CYTO_STOP on ZSTG_RNA_AGILENT(CYTO_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_CHR_STOP on ZSTG_RNA_AGILENT(CHR_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_CHR_START on ZSTG_RNA_AGILENT(CHR_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNALENT_CHROMOSOME on ZSTG_RNA_AGILENT(CHROMOSOME_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
