
drop index ZSTG_MOLLIES_MEMBER_MOL;
drop index ZSTG_MOLLIES_FAMILY_MOL;
drop index ZSTG_MOLLIES_MTYPE;
drop index ZSTG_MOLLIES_MOLECULE_I;
drop index ZSTG_MOLLIES_SOURCE_ID;
drop index ZSTG_MOLLIES_MEMBER_MOL_LWR;
drop index ZSTG_MOLLIES_FAMILY_MOL_LWR;
drop index ZSTG_MOLLIES_MTYPE_LWR;
drop index ZSTG_MOLLIES_MOLECULE_I_LWR;
drop index ZSTG_MOLLIES_SOURCE_ID_LWR;

--EXIT;
