/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_SEQQSTS_WEIGHT on ZSTG_SEQSTS(WEIGHT) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_GROUP_LABE on ZSTG_SEQSTS(GROUP_LABEL) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_FEATURE_TY on ZSTG_SEQSTS(FEATURE_TYPE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_FEATURE_ID on ZSTG_SEQSTS(FEATURE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_FEATURE_NA on ZSTG_SEQSTS(FEATURE_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CTG_ORIENT on ZSTG_SEQSTS(CTG_ORIENT) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CTG_STOP on ZSTG_SEQSTS(CTG_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CTG_START on ZSTG_SEQSTS(CTG_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CONTIG on ZSTG_SEQSTS(CONTIG) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CHR_ORIENT on ZSTG_SEQSTS(CHR_ORIENT) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CHR_STOP on ZSTG_SEQSTS(CHR_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CHR_START on ZSTG_SEQSTS(CHR_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_CHROMOSOME on ZSTG_SEQSTS(CHROMOSOME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQQSTS_TAX_ID on ZSTG_SEQSTS(TAX_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
