/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_GENFSEQ_ASSEMBLY on ZSTG_GENE2REFSEQ(ASSEMBLY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_PROTEIN_ID on ZSTG_GENE2REFSEQ(PROTEIN_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_ORIENTATIO on ZSTG_GENE2REFSEQ(ORIENTATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_END_POSITO on ZSTG_GENE2REFSEQ(END_POSITON) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_START_POSI on ZSTG_GENE2REFSEQ(START_POSITION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_GENOMIC_NU on ZSTG_GENE2REFSEQ(GENOMIC_NUCLEOTIDE_GI) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_GENOMIC_NU on ZSTG_GENE2REFSEQ(GENOMIC_NUCLEOTIDE_ACC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_PROTEIN_GI on ZSTG_GENE2REFSEQ(PROTEIN_GI) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_PROTEIN_AC on ZSTG_GENE2REFSEQ(PROTEIN_ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_RNA_NUCLEO on ZSTG_GENE2REFSEQ(RNA_NUCLEOTIDE_GI) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_RNA_NUCLEO on ZSTG_GENE2REFSEQ(RNA_NUCLEOTIDE_ACC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_STATUS on ZSTG_GENE2REFSEQ(STATUS) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_GENEID on ZSTG_GENE2REFSEQ(GENEID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENFSEQ_TAX_ID on ZSTG_GENE2REFSEQ(TAX_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
