/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_MOLERMS_MODIFICATI_lwr on ZSTG_MOLECULECOMPPTMTERMS(lower(MODIFICATION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLERMS_AA_lwr on ZSTG_MOLECULECOMPPTMTERMS(lower(AA)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLERMS_POSITION_lwr on ZSTG_MOLECULECOMPPTMTERMS(lower(POSITION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLERMS_PROTEIN_lwr on ZSTG_MOLECULECOMPPTMTERMS(lower(PROTEIN)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLERMS_MOLECULE_I_lwr on ZSTG_MOLECULECOMPPTMTERMS(lower(MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLERMS_SOURCE_ID_lwr on ZSTG_MOLECULECOMPPTMTERMS(lower(SOURCE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLERMS_INTERACTIO_lwr on ZSTG_MOLECULECOMPPTMTERMS(lower(INTERACTION_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
