
drop index ZSTG_HUMBAND_CHROM;
drop index ZSTG_HUMBAND_CHROMSTART;
drop index ZSTG_HUMBAND_CYTONAME;
drop index ZSTG_HUMBAND_CHROMEND;
drop index ZSTG_HUMBAND_CHROMOSOME;
drop index ZSTG_HUMBAND_STAIN;
drop index ZSTG_HUMBAND_CYTOBAND;
drop index ZSTG_HUMBAND_ID;

--EXIT;
