/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_CGHLENT_CHROMOSOME_lwr on ZSTG_CGH_AGILENT(lower(CHROMOSOME_NUMBER)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_CGHLENT_DESCRIPTIO_lwr on ZSTG_CGH_AGILENT(lower(DESCRIPTION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_CGHLENT_ACCESSIONS_lwr on ZSTG_CGH_AGILENT(lower(ACCESSIONS)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_CGHLENT_GENE_NAME_lwr on ZSTG_CGH_AGILENT(lower(GENE_NAME)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_CGHLENT_GENE_SYMBO_lwr on ZSTG_CGH_AGILENT(lower(GENE_SYMBOL)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_CGHLENT_TARGET_ID_lwr on ZSTG_CGH_AGILENT(lower(TARGET_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_CGHLENT_PROBE_SET__lwr on ZSTG_CGH_AGILENT(lower(PROBE_SET_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
