
drop index ZSTG_GENSION_PROTEIN_AC;
drop index ZSTG_GENSION_PROTEIN_GI;
drop index ZSTG_GENSION_STATUS;
drop index ZSTG_GENSION_TAX_ID;
drop index ZSTG_GENSION_RNA_NUCLEO;
drop index ZSTG_GENSION_START_POSI;
drop index ZSTG_GENSION_GENOMIC_NU;
drop index ZSTG_GENSION_PROTEIN_ID;
drop index ZSTG_GENSION_ORIENTATIO;
drop index ZSTG_GENSION_END_POSITO;
drop index ZSTG_GENSION_GENEID;

--EXIT;
