
drop index ZSTG_SNPGENE_PROBESET_I;
drop index ZSTG_SNPGENE_ACCESSION;
drop index ZSTG_SNPGENE_ASSOCIATIO;
drop index ZSTG_SNPGENE_DISTANCE;
drop index ZSTG_SNPGENE_UNIGENE_ID;
drop index ZSTG_SNPGENE_ASSOCIATED;

--EXIT;
