
create index ZSTG_PID_LOC_PID_PHYSIC on ZSTG_PID_INTR_PARTPANT_LOC(PID_PHYSICALENTITY_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PID_LOC_LOCATION on ZSTG_PID_INTR_PARTPANT_LOC(LOCATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PID_LOC_ORDER_OF_I on ZSTG_PID_INTR_PARTPANT_LOC(ORDER_OF_INTERACTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PID_LOC_INTERACTIO on ZSTG_PID_INTR_PARTPANT_LOC(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
