/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_POPENCY_ALLELE_B on ZSTG_POP_FREQUENCY(ALLELE_B) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_POPENCY_ALLELE_A on ZSTG_POP_FREQUENCY(ALLELE_A) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_POPENCY_HETEROZYGO on ZSTG_POP_FREQUENCY(HETEROZYGOUS_FREQUENCY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_POPENCY_ALLELE_B_F on ZSTG_POP_FREQUENCY(ALLELE_B_FREQUENCY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_POPENCY_ALLELE_A_F on ZSTG_POP_FREQUENCY(ALLELE_A_FREQUENCY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_POPENCY_ETHNICITY on ZSTG_POP_FREQUENCY(ETHNICITY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_POPENCY_PROBE_SET_ on ZSTG_POP_FREQUENCY(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
