
create index ZSTG_PIDUNIT_WHOLE_PROT on ZSTG_PID_PROTEINSUBUNIT(WHOLE_PROTEIN_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDUNIT_SUBUNIT_PR on ZSTG_PID_PROTEINSUBUNIT(SUBUNIT_PROTEIN_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDUNIT_START_LOC on ZSTG_PID_PROTEINSUBUNIT(START_LOC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDUNIT_STOP_LOC on ZSTG_PID_PROTEINSUBUNIT(STOP_LOC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
