
drop index ZSTG_SNPMINA_PHAST_CONS;
drop index ZSTG_SNPMINA_ID_WITH_MO;
drop index ZSTG_SNPMINA_AMINO_ACID;
drop index ZSTG_SNPMINA_CODING_STA;
drop index ZSTG_SNPMINA_LOCATION_R;
drop index ZSTG_SNPMINA_LOCATION;
drop index ZSTG_SNPMINA_GENE_ACCES;
drop index ZSTG_SNPMINA_GENE_SYMBO;
drop index ZSTG_SNPMINA_GENOME_BUI;
drop index ZSTG_SNPMINA_COORDINATE;
drop index ZSTG_SNPMINA_CHROMOSOME;
drop index ZSTG_SNPMINA_DBSNP_RS_I;

--EXIT;
