				<!-- application hdr begins -->
				<tr>
					<td height="50">
						<table width="100%" height="50" border="0" cellspacing="0" cellpadding="0" class="subhdrBG">
							<tr>
								<td height="50" align="left"><a href="#"><img src="images/sdkLogoSmall.gif" alt="Application Logo" hspace="10" border="0"/></a></td>
								<td>&nbsp;</td>
								<!-- freestyle search -->
								<form method="post" action="searchService.jsp" name="form1">
							 		    <td width="30%" align=right valign="top">
							 			    <INPUT TYPE=TEXT SIZE="40px" name="searchString" value="" >
							 			</td><td width="20px" align="right" valign="top">							 							
										    <INPUT TYPE=SUBMIT NAME="search" VALUE="Search">										
										    <INPUT TYPE=HIDDEN NAME="FULL_TEXT_SEARCH" VALUE="FULL_TEXT_SEARCH">					
										</td>
								</form>
								<!-- freestyle search -->								
							</tr>
						</table>
					</td>
				</tr>
				<!-- application hdr ends -->