CREATE OR REPLACE FORCE VIEW CABIODEV.ANOMALY_TISSUE
(ANOMALY_ID, TARGET_ID, TISSUE_NAME)
AS 
SELECT
  a.anomaly_id,
  target_id,
  TISSUE_NAME
FROM
  CONTEXT c1,
  TISSUE_CLOSURE tc,
  TISSUE_CODE code,
  ANOMALY a
WHERE tc.TISSUE_CODE = code.TISSUE_CODE
  AND c1.TISSUE_CODE = tc.ancestor
  AND a.CONTEXT_CODE = c1.CONTEXT_CODE;


