CREATE OR REPLACE FORCE VIEW CABIODEV.GENE_HISTOPATHOLOGY_VIEW
(GENE_ID, TISSUE_NAME, HISTOLOGY_NAME)
AS 
SELECT gene_id, tissue_name, histology_name
FROM GENE_HISTOPATHOLOGY g, CONTEXT c,  HISTOLOGY_CODE h, TISSUE_CODE t
WHERE c.TISSUE_CODE = t.TISSUE_CODE
AND c.HISTOLOGY_CODE = h.HISTOLOGY_CODE
AND g.context_code = c.context_code;


