CREATE OR REPLACE FORCE VIEW CABIODEV.PARTY_ORGANIZATION_VIEW
(PARTY_ID, ORGANIZATION_ID, ORGANIZATION_NAME)
AS 
SELECT party.party_id, ORGANIZATION.organization_id, 
          ORGANIZATION.organization_name 
     FROM party, ORGANIZATION 
    WHERE party.party_id = ORGANIZATION.party_id;


