CREATE OR REPLACE FORCE VIEW CABIODEV.REPORTER
(REPORTER_ID, DESIGN_ELEMENT_GROUP_ID, REPORTER_NAME, FAIL_TYPE, WARNING_TYPE, 
 REPORTER_DESCRIPTION, DATABASE_REFERENCE_ID, REPLICATE_NUM, ACCESSION)
AS 
SELECT REPORTER_ID, DESIGN_ELEMENT_GROUP_ID, REPORTER_NAME, FAIL_TYPE,
 WARNING_TYPE, REPORTER_DESCRIPTION, DATABASE_REFERENCE_ID,
 REPLICATE_NUM, NULL
FROM dcop.reporter@todcop;


