CREATE OR REPLACE FORCE VIEW CABIODEV.SEQUENCE_OBJECT
(SEQUENCE_ID, ACCESSION_NUMBER, CLONE_ID, LENGTH, SEQUENCE_TYPE, 
 DESCRIPTION, IS_REF_SEQUENCE, ASCII_STRING, VERSION)
AS 
SELECT SEQUENCE.SEQUENCE_ID, 
SEQUENCE.ACCESSION_NUMBER, 
SEQUENCE.CLONE_ID, 
SEQUENCE.LENGTH, 
SEQUENCE.SEQUENCE_TYPE, 
DECODE(SEQUENCE_TYPE, 1, 'EST', 2, 'MRNA') DESCRIPTION, 
IS_REF_SEQUENCE, 
ASCII_STRING, 
VERSION 
FROM SEQUENCE;


