CREATE OR REPLACE FORCE VIEW CABIODEV.SNP_OBJECT
(LOCATION_ID, ACE_ID, CONTIG, OFFSET, SCORE, 
 BASE1, BASE2, GENE_ID)
AS 
SELECT A.LOCATION_ID, A.ACE_ID, CONTIG, OFFSET, SCORE, BASE1, BASE2,
 B.GENE_ID
FROM LOCATION A, ACE B
WHERE A.ACE_ID(+) = B.ACE_ID;


