DROP PUBLIC SYNONYM AR_GO_CELLULAR_COMPONENT_TMP
/

--
-- AR_GO_CELLULAR_COMPONENT_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_GO_CELLULAR_COMPONENT_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_GO_CELLULAR_COMPONENT_TMP FOR AR_GO_CELLULAR_COMPONENT_TMP
/


