DROP PUBLIC SYNONYM AR_REFSEQ_PROTEIN_TMP
/

--
-- AR_REFSEQ_PROTEIN_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_REFSEQ_PROTEIN_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_REFSEQ_PROTEIN_TMP FOR AR_REFSEQ_PROTEIN_TMP
/


