DROP PUBLIC SYNONYM GENE_ALIAS_OBJECT_TV
/

--
-- GENE_ALIAS_OBJECT_TV  (Synonym) 
--
--  Dependencies: 
--   GENE_ALIAS_OBJECT_TV (Table)
--
CREATE PUBLIC SYNONYM GENE_ALIAS_OBJECT_TV FOR GENE_ALIAS_OBJECT_TV
/


