DROP PUBLIC SYNONYM GENERIC_ARRAY_SNP_REPORTER
/

--
-- GENERIC_ARRAY_SNP_REPORTER  (Synonym) 
--
--  Dependencies: 
--   GENERIC_ARRAY_SNP_REPORTER (Table)
--
CREATE PUBLIC SYNONYM GENERIC_ARRAY_SNP_REPORTER FOR GENERIC_ARRAY_SNP_REPORTER
/


