DROP PUBLIC SYNONYM MARKER_MARKER_REL_LOCATION
/

--
-- MARKER_MARKER_REL_LOCATION  (Synonym) 
--
--  Dependencies: 
--   MARKER_MARKER_REL_LOCATION (Table)
--
CREATE PUBLIC SYNONYM MARKER_MARKER_REL_LOCATION FOR MARKER_MARKER_REL_LOCATION
/


