DROP PUBLIC SYNONYM ONTOLOGY_RELATIONSHIP
/

--
-- ONTOLOGY_RELATIONSHIP  (Synonym) 
--
--  Dependencies: 
--   ONTOLOGY_RELATIONSHIP (Table)
--
CREATE PUBLIC SYNONYM ONTOLOGY_RELATIONSHIP FOR ONTOLOGY_RELATIONSHIP
/


