DROP PUBLIC SYNONYM ORGANONTOLOGYRELATIONSHIP
/

--
-- ORGANONTOLOGYRELATIONSHIP  (Synonym) 
--
--  Dependencies: 
--   ORGANONTOLOGYRELATIONSHIP (Table)
--
CREATE PUBLIC SYNONYM ORGANONTOLOGYRELATIONSHIP FOR ORGANONTOLOGYRELATIONSHIP
/


