DROP PUBLIC SYNONYM PID_PATHWAY_INTERACTION
/

--
-- PID_PATHWAY_INTERACTION  (Synonym) 
--
--  Dependencies: 
--   PID_PATHWAY_INTERACTION (Table)
--
CREATE PUBLIC SYNONYM PID_PATHWAY_INTERACTION FOR PID_PATHWAY_INTERACTION
/


