DROP PUBLIC SYNONYM PID_INTERACTION_EC
/

--
-- PID_INTERACTION_EC  (Synonym) 
--
--  Dependencies: 
--   PID_INTERACTION_EC (Table)
--
CREATE PUBLIC SYNONYM PID_INTERACTION_EC FOR PID_INTERACTION_EC
/


