DROP PUBLIC SYNONYM PID_INTERACTION_EVIDENCE
/

--
-- PID_INTERACTION_EVIDENCE  (Synonym) 
--
--  Dependencies: 
--   PID_INTERACTION_EVIDENCE (Table)
--
CREATE PUBLIC SYNONYM PID_INTERACTION_EVIDENCE FOR PID_INTERACTION_EVIDENCE
/


