DROP PUBLIC SYNONYM PROTEIN_PROTEIN_ALIAS
/

--
-- PROTEIN_PROTEIN_ALIAS  (Synonym) 
--
--  Dependencies: 
--   PROTEIN_PROTEIN_ALIAS (Table)
--
CREATE PUBLIC SYNONYM PROTEIN_PROTEIN_ALIAS FOR PROTEIN_PROTEIN_ALIAS
/


