DROP PUBLIC SYNONYM TRANSCRIPT_ARRAY_REPORTER
/

--
-- TRANSCRIPT_ARRAY_REPORTER  (Synonym) 
--
--  Dependencies: 
--   TRANSCRIPT_ARRAY_REPORTER (Table)
--
CREATE PUBLIC SYNONYM TRANSCRIPT_ARRAY_REPORTER FOR TRANSCRIPT_ARRAY_REPORTER
/


