DROP PUBLIC SYNONYM ZSTG_EVS_CONCEPT_RELATIONSHIP
/

--
-- ZSTG_EVS_CONCEPT_RELATIONSHIP  (Synonym) 
--
--  Dependencies: 
--   ZSTG_EVS_CONCEPT_RELATIONSHIP (Table)
--
CREATE PUBLIC SYNONYM ZSTG_EVS_CONCEPT_RELATIONSHIP FOR ZSTG_EVS_CONCEPT_RELATIONSHIP
/


