DROP PUBLIC SYNONYM ZSTG_PID_GENEENTITY
/

--
-- ZSTG_PID_GENEENTITY  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_GENEENTITY (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_GENEENTITY FOR ZSTG_PID_GENEENTITY
/


