DROP PUBLIC SYNONYM ZSTG_PID_FAMILY_MEMBER
/

--
-- ZSTG_PID_FAMILY_MEMBER  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_FAMILY_MEMBER (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_FAMILY_MEMBER FOR ZSTG_PID_FAMILY_MEMBER
/


