DROP PUBLIC SYNONYM ZSTG_EXON_TRANS_GENES
/

--
-- ZSTG_EXON_TRANS_GENES  (Synonym) 
--
--  Dependencies: 
--   ZSTG_EXON_TRANS_GENES (Table)
--
CREATE PUBLIC SYNONYM ZSTG_EXON_TRANS_GENES FOR ZSTG_EXON_TRANS_GENES
/


