DROP PUBLIC SYNONYM ZSTG_INTERACTIONEVIDENCE
/

--
-- ZSTG_INTERACTIONEVIDENCE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_INTERACTIONEVIDENCE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_INTERACTIONEVIDENCE FOR ZSTG_INTERACTIONEVIDENCE
/


