DROP PUBLIC SYNONYM ZSTG_PID_INTR_PARTPANT_LOC
/

--
-- ZSTG_PID_INTR_PARTPANT_LOC  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_INTR_PARTPANT_LOC (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_INTR_PARTPANT_LOC FOR ZSTG_PID_INTR_PARTPANT_LOC
/


