DROP PUBLIC SYNONYM ZSTG_OLD_PROTOCOL_DISEASES
/

--
-- ZSTG_OLD_PROTOCOL_DISEASES  (Synonym) 
--
--  Dependencies: 
--   ZSTG_OLD_PROTOCOL_DISEASES (Table)
--
CREATE PUBLIC SYNONYM ZSTG_OLD_PROTOCOL_DISEASES FOR ZSTG_OLD_PROTOCOL_DISEASES
/


