DROP PUBLIC SYNONYM ZSTG_CMAP_TARGETAGENTS
/

--
-- ZSTG_CMAP_TARGETAGENTS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_CMAP_TARGETAGENTS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_CMAP_TARGETAGENTS FOR ZSTG_CMAP_TARGETAGENTS
/


