DROP PUBLIC SYNONYM ZSTG_PID_MACROPROCESS_TYPE
/

--
-- ZSTG_PID_MACROPROCESS_TYPE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_MACROPROCESS_TYPE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_MACROPROCESS_TYPE FOR ZSTG_PID_MACROPROCESS_TYPE
/


