DROP PUBLIC SYNONYM ZSTG_CGH_ACCESSIONS
/

--
-- ZSTG_CGH_ACCESSIONS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_CGH_ACCESSIONS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_CGH_ACCESSIONS FOR ZSTG_CGH_ACCESSIONS
/


