DROP PUBLIC SYNONYM ZSTG_GENE_ROLE_CGID
/

--
-- ZSTG_GENE_ROLE_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_ROLE_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_ROLE_CGID FOR ZSTG_GENE_ROLE_CGID
/


