DROP PUBLIC SYNONYM ZSTG_EXON_TRANS_AFFY
/

--
-- ZSTG_EXON_TRANS_AFFY  (Synonym) 
--
--  Dependencies: 
--   ZSTG_EXON_TRANS_AFFY (Table)
--
CREATE PUBLIC SYNONYM ZSTG_EXON_TRANS_AFFY FOR ZSTG_EXON_TRANS_AFFY
/


