DROP PUBLIC SYNONYM ZSTG_OLD_PROTOCOLS
/

--
-- ZSTG_OLD_PROTOCOLS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_OLD_PROTOCOLS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_OLD_PROTOCOLS FOR ZSTG_OLD_PROTOCOLS
/


