DROP PUBLIC SYNONYM ZSTG_MOLECULECOMPPTMTERMS
/

--
-- ZSTG_MOLECULECOMPPTMTERMS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MOLECULECOMPPTMTERMS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MOLECULECOMPPTMTERMS FOR ZSTG_MOLECULECOMPPTMTERMS
/


