DROP PUBLIC SYNONYM ZSTG_PID_ENTITYACCESSION
/

--
-- ZSTG_PID_ENTITYACCESSION  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_ENTITYACCESSION (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_ENTITYACCESSION FOR ZSTG_PID_ENTITYACCESSION
/


