DROP PUBLIC SYNONYM ZSTG_STARTEXPRARRAYREPCYTOIDS
/

--
-- ZSTG_STARTEXPRARRAYREPCYTOIDS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_STARTEXPRARRAYREPCYTOIDS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_STARTEXPRARRAYREPCYTOIDS FOR ZSTG_STARTEXPRARRAYREPCYTOIDS
/


