DROP PUBLIC SYNONYM ZSTG_GENE_DISEASEONTO_CGID
/

--
-- ZSTG_GENE_DISEASEONTO_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_DISEASEONTO_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_DISEASEONTO_CGID FOR ZSTG_GENE_DISEASEONTO_CGID
/


