DROP PUBLIC SYNONYM ZSTG_INTERACTIONCOMPONENTLABEL
/

--
-- ZSTG_INTERACTIONCOMPONENTLABEL  (Synonym) 
--
--  Dependencies: 
--   ZSTG_INTERACTIONCOMPONENTLABEL (Table)
--
CREATE PUBLIC SYNONYM ZSTG_INTERACTIONCOMPONENTLABEL FOR ZSTG_INTERACTIONCOMPONENTLABEL
/


