/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_SNP;
DROP TABLE GENE_STG31;
DROP TABLE SEQUENCE_STG31A;
DROP TABLE SEQUENCE_STG31B;
DROP TABLE SEQUENCE_STG31C;

CREATE TABLE ZSTG_SNP
(
  DBSNP_RS_ID        VARCHAR2(20),
  SPECIES_NAME       VARCHAR2(20),
  ALLELE_A           VARCHAR2(1),
  ALLELE_B           VARCHAR2(1),
  VALIDATION_STATUS  VARCHAR2(50),
  CHROMOSOME_NUMBER  VARCHAR2(2),
  LOCATION           NUMBER
);

CREATE TABLE GENE_STG31
(
  GENE_ID        NUMBER          NOT NULL,
  GENE_SYMBOL    VARCHAR2(50),
  GENE_TITLE     VARCHAR2(2000),
  CHROMOSOME_ID  NUMBER,
  TAXON_ID       NUMBER,
  CYTOBAND       VARCHAR2(100)
);

CREATE TABLE SEQUENCE_STG31A
(
  ACCESSION_NUMBER  VARCHAR2(50),
  SEQUENCE_TYPE     VARCHAR2(50),
  DESCRIPTION       VARCHAR2(1000),
  VALUE             VARCHAR2(4000),
  LENGTH            NUMBER
);

CREATE TABLE SEQUENCE_STG31B
(
  ACCESSION_NUMBER  VARCHAR2(50),
  SEQUENCE_TYPE     VARCHAR2(50),
  DESCRIPTION       VARCHAR2(1000),
  VALUE             CLOB,
  LENGTH            NUMBER
);

CREATE TABLE SEQUENCE_STG31C
(
  ACCESSION_NUMBER  VARCHAR2(50),
  SEQUENCE_TYPE     VARCHAR2(50),
  DESCRIPTION       VARCHAR2(1000),
  VALUE             CLOB,
  LENGTH            NUMBER
);

EXIT;