
create index BIO_PATHWAYS_PATHWAY_NA_lwr on BIO_PATHWAYS(lower(PATHWAY_NAME)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index BIO_PATHWAYS_PATHWAY_DI_lwr on BIO_PATHWAYS(lower(PATHWAY_DISPLAY)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index BIO_PATHWAYS_PATHWAY_DI_lwr on BIO_PATHWAYS(lower(PATHWAY_DIAGRAM)) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
