
create index EVIDENCECODE_EVIDENCE_C on EVIDENCE_CODE(EVIDENCE_CODE) PARALLEL NOLOGGING tablespace CABIO;
create index EVIDENCECODE_ID on EVIDENCE_CODE(ID) PARALLEL NOLOGGING tablespace CABIO;

--EXIT;
