
drop index GENERICNERIC_ARRAY_BIG_ID_LWR;
drop index GABIGID;
drop index GENERIC_RRAY_TYPE_LWR;
drop index GENERIC_RRAY_PLATFORM_LWR;
drop index GENERIC_RRAY_ARRAY_NAME_LWR;
drop index GENERICARRNODUPS;
drop index GENERIC_RRAY_ARRAY_NAME;
drop index GENERIC_RRAY_ID;
drop index GENERIC_RRAY_TYPE;
drop index GENERIC_RRAY_PLATFORM;

--EXIT;
