
drop index GORBIGID;
drop index GO_RELAHIP_BIG_ID_LWR;
drop index GO_RELATSHIP_ID;
drop index GO_RELATSHIP_RELATIONSH;
drop index GO_RELATSHIP_PARENT_ID;
drop index GO_RELATSHIP_CHILD_ID;
drop index GO_RELATSHIP_RELATIONSH_LWR;

--EXIT;
