
drop index HISTOLOGCODE_RELATIONSH_LWR;
drop index HISTOLOGCODE_CONCEPT_ID_LWR;
drop index HISTOLOGCODE_HISTOLOGY__LWR;
drop index HISTOLOGCODE_EVS_ID;
drop index HISTOLOGCODE_RELATIONSH;
drop index HISTOLOGCODE_EVS_ID_LWR;
drop index HISTOLOGCODE_CONCEPT_ID;
drop index HISTOLOGCODE_PARENT;
drop index HISTOLOSTOLOGY_CODE_BIG_ID;
drop index HISTOLOGCODE_HISTOLOGY_;
drop index PK_HISTOLOGY_CODE;
drop index HISTOLOSTOLOGY_CODE_BIG_ID_LWR;

--EXIT;
