
create index PROTEIN_ORDS_ID on PROTEIN_KEYWORDS(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTEIN_ORDS_KEYWORD on PROTEIN_KEYWORDS(KEYWORD) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTEIN_ORDS_PROTEIN_ID on PROTEIN_KEYWORDS(PROTEIN_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
