
drop index PDBIGID;
drop index PROTEIN_MAIN_TYPE_LWR;
drop index PROTEIN_MAIN_ACCESSION__LWR;
drop index PROTEIN_MAIN_DESCRIPTIO_LWR;
drop index PROTEIN_MAIN_TYPE;
drop index PROTEIN_MAIN_DESCRIPTIO;
drop index PROTEIN_MAIN_ACCESSION_;
drop index PROTEIN_MAIN_ID;
drop index PROTEINOTEIN_DOMAIN_BIG_ID_LWR;

--EXIT;
