
drop index ZSTG_GEN_MAP_FIRST_MARK;
drop index ZSTG_GEN_MAP_SECOND_MAR;
drop index ZSTG_GEN_MAP_DISTANCE;
drop index ZSTG_GEN_MAP_PROBE_SET_;
drop index ZSTG_GEN_MAP_TYPE;
drop index ZSTG_GEN_MAP_SECOND_SNP;
drop index ZSTG_GEN_MAP_FIRST_SNP_;

--EXIT;
