
drop index ZSTG_PATWERS_REVIEWER_N;
drop index ZSTG_PATWERS_SOURCE_ID;
drop index ZSTG_PATWERS_PATHWAY_ID;
drop index ZSTG_PATWERS_SOURCE_ID_LWR;
drop index ZSTG_PATWERS_PATHWAY_ID_LWR;
drop index ZSTG_PATWERS_REVIEWER_N_LWR;

--EXIT;
