/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ANOMALY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ANOMALY CASCADE CONSTRAINTS PURGE
/

--
-- ANOMALY  (Table) 
--
CREATE TABLE ANOMALY ( ANOMALY_ID NUMBER NOT NULL, TARGET_ID NUMBER NOT NULL, ANOMALY_TYPE VARCHAR2(100 BYTE) NULL, CONTEXT_CODE NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT PK_ANOMALY PRIMARY KEY (ANOMALY_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


