/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE AR_ENTREZ_GENE_TMP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE AR_ENTREZ_GENE_TMP CASCADE CONSTRAINTS PURGE
/

--
-- AR_ENTREZ_GENE_TMP  (Table) 
--
CREATE TABLE AR_ENTREZ_GENE_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, ENTREZ_GENE VARCHAR2(20 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL, PRIMARY KEY (PROBE_SET_ID, ENTREZ_GENE, GENECHIP_ARRAY) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


