/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE AR_GENE_TITLE CASCADE CONSTRAINTS PURGE
/

--
-- AR_GENE_TITLE  (Table) 
--
CREATE TABLE AR_GENE_TITLE ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, GENE_TITLE VARCHAR2(1000 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


