/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE AR_PATHWAY_TMP CASCADE CONSTRAINTS PURGE
/

--
-- AR_PATHWAY_TMP  (Table) 
--
CREATE TABLE AR_PATHWAY_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, PATHWAY VARCHAR2(100 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


