ALTER TABLE AR_REP_PUBLIC_ID_TMP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE AR_REP_PUBLIC_ID_TMP CASCADE CONSTRAINTS PURGE
/

--
-- AR_REP_PUBLIC_ID_TMP  (Table) 
--
CREATE TABLE AR_REP_PUBLIC_ID_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, REPRESENTATIVE_PUBLIC_ID VARCHAR2(100 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL, PRIMARY KEY (PROBE_SET_ID, REPRESENTATIVE_PUBLIC_ID, GENECHIP_ARRAY) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


