/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE CLONE_TRACE CASCADE CONSTRAINTS PURGE
/

--
-- CLONE_TRACE  (Table) 
--
CREATE TABLE CLONE_TRACE ( CLONE_TRACE_ID NUMBER NOT NULL, MAGE_CLONE_ID VARCHAR2(25 BYTE) NOT NULL, LIBRARY_NAME VARCHAR2(25 BYTE) NOT NULL, ACCESSION_NUMBER VARCHAR2(25 BYTE) NOT NULL, TRACE_NAME VARCHAR2(25 BYTE) NOT NULL, UNIQUE (CLONE_TRACE_ID, MAGE_CLONE_ID, LIBRARY_NAME, TRACE_NAME, ACCESSION_NUMBER) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


