/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE CLONE_TAXON
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CLONE_TAXON CASCADE CONSTRAINTS PURGE
/

--
-- CLONE_TAXON  (Table) 
--
--  Dependencies: 
--   TAXON (Table)
--
CREATE TABLE CLONE_TAXON ( CLONE_ID NUMBER NOT NULL, TAXON_ID NUMBER NOT NULL, CONSTRAINT PK_CLONE_TAXON PRIMARY KEY (CLONE_ID, TAXON_ID), CONSTRAINT CT_TAX FOREIGN KEY (TAXON_ID) REFERENCES TAXON (TAXON_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


