ALTER TABLE CONCEPT_TARGET
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CONCEPT_TARGET CASCADE CONSTRAINTS PURGE
/

--
-- CONCEPT_TARGET  (Table) 
--
CREATE TABLE CONCEPT_TARGET ( CONCEPT_ID NUMBER NOT NULL, TARGET_ID NUMBER NOT NULL, PRIMARY KEY (CONCEPT_ID, TARGET_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


