/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE CONCEPT CASCADE CONSTRAINTS PURGE
/

--
-- CONCEPT  (Table) 
--
CREATE TABLE CONCEPT ( CONCEPT_ID NUMBER NOT NULL, CONCEPT_TYPE_ID NUMBER NOT NULL, CONCEPT_NAME VARCHAR2(250 BYTE) NULL ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


