/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE DATABASE_CROSS_REFERENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE DATABASE_CROSS_REFERENCE CASCADE CONSTRAINTS PURGE
/

--
-- DATABASE_CROSS_REFERENCE  (Table) 
--
--  Dependencies: 
--   NEW_PROTEIN (Table)
--   NUCLEIC_ACID_SEQUENCE (Table)
--   GENE_TV (Table)
--   SNP_TV (Table)
--
CREATE TABLE DATABASE_CROSS_REFERENCE ( ID NUMBER NOT NULL, TYPE VARCHAR2(50 BYTE) NOT NULL, SOURCE_NAME VARCHAR2(50 BYTE) NOT NULL, CROSS_REFERENCE_ID VARCHAR2(50 BYTE) NOT NULL, SOURCE_TYPE VARCHAR2(50 BYTE) NOT NULL, SUMMARY VARCHAR2(50 BYTE) NULL, GENE_ID NUMBER NULL, SNP_ID NUMBER NULL, NUCLEIC_ACID_SEQ_ID NUMBER NULL, PROTEIN_ID NUMBER NULL, ENGINEEREDGENE_ID NUMBER NULL, PRIMARY KEY (ID), UNIQUE (TYPE, SOURCE_NAME, CROSS_REFERENCE_ID, SOURCE_TYPE, SUMMARY, GENE_ID, SNP_ID, NUCLEIC_ACID_SEQ_ID, PROTEIN_ID, ENGINEEREDGENE_ID), CONSTRAINT DBCROSSREFFK3 FOREIGN KEY (PROTEIN_ID) REFERENCES NEW_PROTEIN (PROTEIN_ID), CONSTRAINT DBCROSSREFFK4 FOREIGN KEY (NUCLEIC_ACID_SEQ_ID) REFERENCES NUCLEIC_ACID_SEQUENCE (ID), CONSTRAINT DBGENEFK FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), FOREIGN KEY (SNP_ID) REFERENCES SNP_TV (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


