/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE EVIDENCE_CODE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EVIDENCE_CODE CASCADE CONSTRAINTS PURGE
/

--
-- EVIDENCE_CODE  (Table) 
--
CREATE TABLE EVIDENCE_CODE ( EVIDENCE_CODE VARCHAR2(2500 BYTE) NOT NULL, ID NUMBER NOT NULL, BIG_ID VARCHAR2(1000 BYTE) NULL, PRIMARY KEY (ID), UNIQUE (EVIDENCE_CODE) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


