ALTER TABLE EXON
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EXON CASCADE CONSTRAINTS PURGE
/

--
-- EXON  (Table) 
--
--  Dependencies: 
--   TRANSCRIPT (Table)
--
CREATE TABLE EXON ( ID NUMBER NOT NULL, MANUFACTURER_ID VARCHAR2(20 BYTE) NOT NULL, SOURCE VARCHAR2(20 BYTE) NOT NULL, TRANSCRIPT_ID NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT EXON_PK PRIMARY KEY (ID), UNIQUE (MANUFACTURER_ID, SOURCE, TRANSCRIPT_ID), CONSTRAINT XONBIGID UNIQUE (BIG_ID), CONSTRAINT EXFK FOREIGN KEY (TRANSCRIPT_ID) REFERENCES TRANSCRIPT (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


