ALTER TABLE GENE_EXPRESSED_IN
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENE_EXPRESSED_IN CASCADE CONSTRAINTS PURGE
/

--
-- GENE_EXPRESSED_IN  (Table) 
--
CREATE TABLE GENE_EXPRESSED_IN ( GENE_ID NUMBER NULL, ORGAN_ID NUMBER NULL, CONSTRAINT PK_GENE_EXPRESSED_IN PRIMARY KEY (GENE_ID, ORGAN_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


