/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE GENE_PATHWAY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENE_PATHWAY CASCADE CONSTRAINTS PURGE
/

--
-- GENE_PATHWAY  (Table) 
--
CREATE TABLE GENE_PATHWAY ( BC_ID VARCHAR2(4000 BYTE) NOT NULL, PATHWAY_ID NUMBER NOT NULL, CONSTRAINT GENE_PATHWAY_PK PRIMARY KEY (BC_ID, PATHWAY_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


