/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE GO_CLOSURE CASCADE CONSTRAINTS PURGE
/

--
-- GO_CLOSURE  (Table) 
--
CREATE TABLE GO_CLOSURE ( GO_CODE NUMBER NOT NULL, ANCESTOR NUMBER NOT NULL ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


