/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE HISTOPATHOLOGY_DISEASE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE HISTOPATHOLOGY_DISEASE CASCADE CONSTRAINTS PURGE
/

--
-- HISTOPATHOLOGY_DISEASE  (Table) 
--
CREATE TABLE HISTOPATHOLOGY_DISEASE ( HISTOPATHOLOGY_ID NUMBER NOT NULL, DISEASE_ID NUMBER NOT NULL, DISEASE_ID_V VARCHAR2(50 BYTE) NULL, PRIMARY KEY (HISTOPATHOLOGY_ID, DISEASE_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


