/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE IMT_TO_HISTOLOGY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE IMT_TO_HISTOLOGY CASCADE CONSTRAINTS PURGE
/

--
-- IMT_TO_HISTOLOGY  (Table) 
--
CREATE TABLE IMT_TO_HISTOLOGY ( IMT_CODE NUMBER NULL, HISTOLOGY_CODE NUMBER NULL, CONSTRAINT IMTHIST PRIMARY KEY (IMT_CODE, HISTOLOGY_CODE) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


