/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE NUCLEIC_ACID_SEQUENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE NUCLEIC_ACID_SEQUENCE CASCADE CONSTRAINTS PURGE
/

--
-- NUCLEIC_ACID_SEQUENCE  (Table) 
--
CREATE TABLE NUCLEIC_ACID_SEQUENCE ( ID NUMBER NOT NULL, ACCESSION_NUMBER VARCHAR2(50 BYTE) NOT NULL, VERSION VARCHAR2(50 BYTE) NOT NULL, SEQUENCE_TYPE VARCHAR2(50 BYTE) NOT NULL, CLONE_ID NUMBER NULL, VALUE CLOB NOT NULL, LENGTH NUMBER NOT NULL, DESCRIPTION VARCHAR2(1000 BYTE) NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, DISCRIMINATOR VARCHAR2(100 BYTE) NOT NULL, CONSTRAINT NAS_PK PRIMARY KEY (ID), CONSTRAINT NASBIGID UNIQUE (BIG_ID), CONSTRAINT NASNODUPS UNIQUE (ACCESSION_NUMBER) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS LOB (VALUE) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


