ALTER TABLE PHYSICAL_LOCATION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PHYSICAL_LOCATION CASCADE CONSTRAINTS PURGE
/

--
-- PHYSICAL_LOCATION  (Table) 
--
--  Dependencies: 
--   NUCLEIC_ACID_SEQUENCE (Table)
--   MARKER (Table)
--   TRANSCRIPT (Table)
--   CHROMOSOME (Table)
--   GENE_TV (Table)
--   SNP_TV (Table)
--   EXON_REPORTER (Table)
--
CREATE TABLE PHYSICAL_LOCATION ( ID NUMBER NOT NULL, CHROMOSOMAL_START_POSITION NUMBER NOT NULL, CHROMOSOMAL_END_POSITION NUMBER NOT NULL, GENE_ID NUMBER NULL, NUCLEIC_ACID_ID NUMBER NULL, SNP_ID NUMBER NULL, CHROMOSOME_ID NUMBER NOT NULL, TRANSCRIPT_ID NUMBER NULL, EXON_REPORTER_ID NUMBER NULL, CYTOBAND_ID NUMBER NULL, MARKER_ID NUMBER NULL, CONSTRAINT PL_PK PRIMARY KEY (ID), CONSTRAINT PK_NAS FOREIGN KEY (NUCLEIC_ACID_ID) REFERENCES NUCLEIC_ACID_SEQUENCE (ID), CONSTRAINT PLMID FOREIGN KEY (MARKER_ID) REFERENCES MARKER (ID), CONSTRAINT PLXSCRPT FOREIGN KEY (TRANSCRIPT_ID) REFERENCES TRANSCRIPT (ID), CONSTRAINT PL_CHR FOREIGN KEY (CHROMOSOME_ID) REFERENCES CHROMOSOME (CHROMOSOME_ID), CONSTRAINT PL_G FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), FOREIGN KEY (SNP_ID) REFERENCES SNP_TV (ID), FOREIGN KEY (EXON_REPORTER_ID) REFERENCES EXON_REPORTER (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


