/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PID_PHYSICAL_ENTITY_ACCESSION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_PHYSICAL_ENTITY_ACCESSION CASCADE CONSTRAINTS PURGE
/

--
-- PID_PHYSICAL_ENTITY_ACCESSION  (Table) 
--
--  Dependencies: 
--   PID_PHYSICAL_ENTITY (Table)
--   PID_ENTITY_ACCESSION (Table)
--
CREATE TABLE PID_PHYSICAL_ENTITY_ACCESSION ( PHYSICAL_ENTITY_ID NUMBER NOT NULL, ENTITY_ACCESSION_ID NUMBER NOT NULL, PRIMARY KEY (PHYSICAL_ENTITY_ID, ENTITY_ACCESSION_ID), FOREIGN KEY (PHYSICAL_ENTITY_ID) REFERENCES PID_PHYSICAL_ENTITY (ID), FOREIGN KEY (ENTITY_ACCESSION_ID) REFERENCES PID_ENTITY_ACCESSION (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


