/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PID_INTERACTION_EVIDENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_INTERACTION_EVIDENCE CASCADE CONSTRAINTS PURGE
/

--
-- PID_INTERACTION_EVIDENCE  (Table) 
--
--  Dependencies: 
--   PID_INTERACTION (Table)
--   EVIDENCE (Table)
--
CREATE TABLE PID_INTERACTION_EVIDENCE ( INTERACTION_ID NUMBER NOT NULL, EVIDENCE_ID NUMBER NOT NULL, PRIMARY KEY (INTERACTION_ID, EVIDENCE_ID), FOREIGN KEY (INTERACTION_ID) REFERENCES PID_INTERACTION (ID), FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (ID) DISABLE ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


