/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PROTEIN_SECONDARY_ACCESSION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PROTEIN_SECONDARY_ACCESSION CASCADE CONSTRAINTS PURGE
/

--
-- PROTEIN_SECONDARY_ACCESSION  (Table) 
--
--  Dependencies: 
--   NEW_PROTEIN (Table)
--
CREATE TABLE PROTEIN_SECONDARY_ACCESSION ( PROTEIN_ID NUMBER NOT NULL, SECONDARY_ACCESSION VARCHAR2(50 BYTE) NOT NULL, ID NUMBER NOT NULL, CONSTRAINT PSA_PK PRIMARY KEY (ID), UNIQUE (SECONDARY_ACCESSION, PROTEIN_ID), CONSTRAINT PSAFK FOREIGN KEY (PROTEIN_ID) REFERENCES NEW_PROTEIN (PROTEIN_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


