/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE PROTOCOL_AGENTS CASCADE CONSTRAINTS PURGE
/

--
-- PROTOCOL_AGENTS  (Table) 
--
CREATE TABLE PROTOCOL_AGENTS ( PRO_ID NUMBER(10) NOT NULL, AGENT_ID NUMBER NOT NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


