/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PUBLICATION_SOURCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PUBLICATION_SOURCE CASCADE CONSTRAINTS PURGE
/

--
-- PUBLICATION_SOURCE  (Table) 
--
CREATE TABLE PUBLICATION_SOURCE ( ID NUMBER NOT NULL, NAME VARCHAR2(255 BYTE) NOT NULL, AUTHORS CLOB NOT NULL, YEAR NUMBER NOT NULL, VOLUME NUMBER NOT NULL, TITLE VARCHAR2(255 BYTE) NOT NULL, START_PAGE NUMBER NOT NULL, END_PAGE NUMBER NOT NULL, CONSTRAINT PK_PUBLICATION_SOURCE PRIMARY KEY (ID), UNIQUE (NAME, YEAR, VOLUME, TITLE, START_PAGE, END_PAGE) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS LOB (AUTHORS) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


