/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE RELATIVE_LOCATION_CH
 DROP PRIMARY KEY CASCADE
/
DROP TABLE RELATIVE_LOCATION_CH CASCADE CONSTRAINTS PURGE
/

--
-- RELATIVE_LOCATION_CH  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--   SNP_TV (Table)
--
CREATE TABLE RELATIVE_LOCATION_CH ( ID NUMBER NOT NULL, TYPE VARCHAR2(50 BYTE) NULL, ORIENTATION VARCHAR2(50 BYTE) NULL, DISTANCE VARCHAR2(50 BYTE) NOT NULL, SNP_ID NUMBER NOT NULL, PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, GENE_ID NUMBER NULL, BIG_ID VARCHAR2(200 BYTE) NULL, DISCRIMINATOR VARCHAR2(2500 BYTE) NOT NULL, CONSTRAINT REL_LOC_CH_PK PRIMARY KEY (ID), UNIQUE (TYPE, ORIENTATION, DISTANCE, SNP_ID, PROBE_SET_ID, GENE_ID, DISCRIMINATOR), CONSTRAINT RLOCFK1 FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), FOREIGN KEY (SNP_ID) REFERENCES SNP_TV (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


