ALTER TABLE SOURCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SOURCE CASCADE CONSTRAINTS PURGE
/

--
-- SOURCE  (Table) 
--
CREATE TABLE SOURCE ( ID NUMBER NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, CONSTRAINT PK_SOURCE PRIMARY KEY (ID), CONSTRAINT SRCUNIQ UNIQUE (NAME) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


