/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE SOURCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SOURCE CASCADE CONSTRAINTS PURGE
/

--
-- SOURCE  (Table) 
--
CREATE TABLE SOURCE ( ID NUMBER NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, CONSTRAINT PK_SOURCE PRIMARY KEY (ID), CONSTRAINT SRCUNIQ UNIQUE (NAME) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


