/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE TAXON
 DROP PRIMARY KEY CASCADE
/
DROP TABLE TAXON CASCADE CONSTRAINTS PURGE
/

--
-- TAXON  (Table) 
--
CREATE TABLE TAXON ( SCIENTIFIC_NAME VARCHAR2(255 BYTE) NOT NULL, ABBREVIATION VARCHAR2(10 BYTE) NULL, COMMON_NAME VARCHAR2(255 BYTE) NOT NULL, STRAIN_OR_ETHNICITY VARCHAR2(100 BYTE) NULL, TAXON_ID NUMBER NULL, PERFERED NUMBER DEFAULT 0 NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CHECK ("ABBREVIATION" IS NOT NULL), CHECK ("TAXON_ID" IS NOT NULL), CHECK ("PERFERED" IS NOT NULL), CHECK ("BIG_ID" IS NOT NULL), CONSTRAINT TAXON_PK PRIMARY KEY (TAXON_ID), CONSTRAINT TAXBIGID UNIQUE (BIG_ID), CONSTRAINT TAXNODUPS UNIQUE (STRAIN_OR_ETHNICITY, SCIENTIFIC_NAME) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


