/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE TRANSCRIPT_GENE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE TRANSCRIPT_GENE CASCADE CONSTRAINTS PURGE
/

--
-- TRANSCRIPT_GENE  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--   TRANSCRIPT (Table)
--
CREATE TABLE TRANSCRIPT_GENE ( TRANSCRIPT_ID NUMBER NOT NULL, GENE_ID NUMBER NOT NULL, CONSTRAINT TGPK PRIMARY KEY (TRANSCRIPT_ID, GENE_ID), CONSTRAINT TGFK1 FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), CONSTRAINT TGFK2 FOREIGN KEY (TRANSCRIPT_ID) REFERENCES TRANSCRIPT (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


