DROP TABLE URL_SOURCE_REFERENCE CASCADE CONSTRAINTS PURGE
/

--
-- URL_SOURCE_REFERENCE  (Table) 
--
CREATE TABLE URL_SOURCE_REFERENCE ( ID NUMBER NOT NULL, SOURCE_REFERENCE_TYPE VARCHAR2(50 BYTE) DEFAULT 'URL' NOT NULL, SOURCE_URL VARCHAR2(200 BYTE) NULL, REFERENCE CLOB NOT NULL, CHECK ("SOURCE_URL" IS NOT NULL) DISABLE ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS LOB (REFERENCE) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


