/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE VOCABULARY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE VOCABULARY CASCADE CONSTRAINTS PURGE
/

--
-- VOCABULARY  (Table) 
--
CREATE TABLE VOCABULARY ( GENERAL_TERM VARCHAR2(255 BYTE) NOT NULL, CORE_TERM VARCHAR2(255 BYTE) NOT NULL, VOCABULARY_ID NUMBER NULL, BIG_ID VARCHAR2(200 BYTE) NOT NULL, CONSTRAINT VOCABULARY_PK PRIMARY KEY (VOCABULARY_ID), CONSTRAINT BIGID UNIQUE (BIG_ID), UNIQUE (GENERAL_TERM, CORE_TERM, VOCABULARY_ID), CONSTRAINT VOCABUNIQ UNIQUE (GENERAL_TERM, CORE_TERM) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


