/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_PID_PROTEINSUBUNIT CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_PROTEINSUBUNIT  (Table) 
--
CREATE TABLE ZSTG_PID_PROTEINSUBUNIT ( WHOLE_PROTEIN_ID NUMBER NOT NULL, SUBUNIT_PROTEIN_ID NUMBER NOT NULL, START_LOC NUMBER NOT NULL, STOP_LOC NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


