/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_MISSING_AGENT_CGID_EVS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_MISSING_AGENT_CGID_EVS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MISSING_AGENT_CGID_EVS  (Table) 
--
CREATE TABLE ZSTG_MISSING_AGENT_CGID_EVS ( DRUG VARCHAR2(1000 BYTE) NOT NULL, NSC_NUMBER NUMBER NOT NULL, EVS_ID VARCHAR2(1000 BYTE) NOT NULL, PRIMARY KEY (DRUG, NSC_NUMBER, EVS_ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


