/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_PID_INTERACTIONREFERENCE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_INTERACTIONREFERENCE  (Table) 
--
CREATE TABLE ZSTG_PID_INTERACTIONREFERENCE ( INTERACTION_ID NUMBER NOT NULL, PUBMED_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


