DROP TABLE ZSTG_MOLECULENAMES CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MOLECULENAMES  (Table) 
--
CREATE TABLE ZSTG_MOLECULENAMES ( MOLECULE_ID VARCHAR2(2500 BYTE) NOT NULL, MTYPE VARCHAR2(2500 BYTE) NOT NULL, NAME_TYPE VARCHAR2(2500 BYTE) NOT NULL, LONG_NAME_TYPE VARCHAR2(2500 BYTE) NULL, VALUE VARCHAR2(2500 BYTE) NULL, SOURCE_ID VARCHAR2(20 BYTE) NOT NULL, PROTEIN_ID NUMBER NULL, GENE_ID NUMBER NULL, NAS_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


