/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_RNA_PROBESETS_TEXT CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_RNA_PROBESETS_TEXT  (Table) 
--
CREATE TABLE ZSTG_RNA_PROBESETS_TEXT ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL, SPECIES_SCIENTIFIC_NAME VARCHAR2(200 BYTE) NOT NULL, ANNOTATION_DATE VARCHAR2(20 BYTE) NOT NULL, SEQUENCE_TYPE VARCHAR2(20 BYTE) NOT NULL, SEQUENCE_SOURCE VARCHAR2(50 BYTE) NOT NULL, TRANSCRIPT_ID VARCHAR2(100 BYTE) NOT NULL, TARGET_DESCRIPTION VARCHAR2(2000 BYTE) NOT NULL, REPRESENTATIVE_PUBLIC_ID VARCHAR2(100 BYTE) NOT NULL, ARCHIVAL_UNIGENE_CLUSTER VARCHAR2(100 BYTE) NOT NULL, UNIGENE_ID VARCHAR2(100 BYTE) NOT NULL, GENOME_VERSION VARCHAR2(50 BYTE) NOT NULL, ALIGNMENTS VARCHAR2(2000 BYTE) NOT NULL, GENE_TITLE VARCHAR2(4000 BYTE) NOT NULL, GENE_SYMBOL VARCHAR2(4000 BYTE) NOT NULL, CHROMOSOMAL_LOCATION VARCHAR2(1000 BYTE) NOT NULL, UNIGENE_CLUSTER_TYPE VARCHAR2(50 BYTE) NOT NULL, ENSEMBL VARCHAR2(1000 BYTE) NOT NULL, ENTREZ_GENE VARCHAR2(500 BYTE) NOT NULL, SWISSPROT VARCHAR2(4000 BYTE) NOT NULL, EC VARCHAR2(200 BYTE) NOT NULL, OMIM VARCHAR2(500 BYTE) NOT NULL, REFSEQ_PROTEIN_ID VARCHAR2(4000 BYTE) NOT NULL, REFSEQ_TRANSCRIPT_ID VARCHAR2(4000 BYTE) NOT NULL, FLYBASE VARCHAR2(20 BYTE) NOT NULL, AGI VARCHAR2(20 BYTE) NOT NULL, WORMBASE VARCHAR2(20 BYTE) NOT NULL, MGI_NAME VARCHAR2(20 BYTE) NOT NULL, RGD_NAME VARCHAR2(20 BYTE) NOT NULL, SGD_ACCESSION_NUMBER VARCHAR2(20 BYTE) NOT NULL, GO_BIOLOGICAL_PROCESS VARCHAR2(4000 BYTE) NOT NULL, GO_CELLULAR_COMPONENT VARCHAR2(4000 BYTE) NOT NULL, GO_MOLECULAR_FUNCTION VARCHAR2(4000 BYTE) NOT NULL, PATHWAY VARCHAR2(4000 BYTE) NOT NULL, INTERPRO VARCHAR2(4000 BYTE) NOT NULL, TRANS_MEMBRANE VARCHAR2(4000 BYTE) NOT NULL, QTL VARCHAR2(100 BYTE) NOT NULL, ANNOTATION_DESCRIPTION VARCHAR2(4000 BYTE) NOT NULL, ANNOTATION_TRANSCRIPT_CLUSTER VARCHAR2(4000 BYTE) NULL, TRANSCRIPT_ASSIGNMENTS VARCHAR2(4000 BYTE) NULL, ANNOTATION_NOTES VARCHAR2(4000 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


