DROP TABLE ZSTG_MOLECULEFAMILIES CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MOLECULEFAMILIES  (Table) 
--
CREATE TABLE ZSTG_MOLECULEFAMILIES ( MOLECULE_ID VARCHAR2(2500 BYTE) NOT NULL, MTYPE VARCHAR2(2500 BYTE) NOT NULL, FAMILY_MOLECULE_ID VARCHAR2(2500 BYTE) NULL, MEMBER_MOLECULE_ID VARCHAR2(2500 BYTE) NOT NULL, SOURCE_ID VARCHAR2(20 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


