DROP TABLE ZSTG_AGENTS_NSC CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_AGENTS_NSC  (Table) 
--
CREATE TABLE ZSTG_AGENTS_NSC ( NSC_NUMBER NUMBER NOT NULL, AGENT_NAME VARCHAR2(500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


