/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_CLONE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_CLONE  (Table) 
--
CREATE TABLE ZSTG_CLONE ( TAXON_ID NUMBER NOT NULL, CLONE_ID NUMBER NOT NULL, CLONE_NAME VARCHAR2(50 BYTE) NOT NULL, UNIGENE_LIBRARY_ID NUMBER NULL, RELATIVE_TYPE VARCHAR2(10 BYTE) NULL, LIBRARY_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


