/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_POP_FREQUENCY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_POP_FREQUENCY  (Table) 
--
CREATE TABLE ZSTG_POP_FREQUENCY ( PROBE_SET_ID VARCHAR2(100 BYTE) NULL, ETHNICITY VARCHAR2(50 BYTE) NULL, ALLELE_A_FREQUENCY FLOAT(126) NULL, ALLELE_B_FREQUENCY FLOAT(126) NULL, HETEROZYGOUS_FREQUENCY FLOAT(126) NULL, ALLELE_A VARCHAR2(20 BYTE) NULL, ALLELE_B VARCHAR2(20 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


