/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_PID_PATHWAYREFERENCE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_PATHWAYREFERENCE  (Table) 
--
CREATE TABLE ZSTG_PID_PATHWAYREFERENCE ( PATHWAY_ID NUMBER NOT NULL, PUBMED_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


