DROP TABLE ZSTG_PID_FMLY_PRTPNT_ACTST CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_FMLY_PRTPNT_ACTST  (Table) 
--
CREATE TABLE ZSTG_PID_FMLY_PRTPNT_ACTST ( FAMILY_ID NUMBER NOT NULL, MEMBER_ID NUMBER NOT NULL, ACTIVITY_STATE VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


