DROP TABLE ZSTG_EXON_TRANS_GENES CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_EXON_TRANS_GENES  (Table) 
--
CREATE TABLE ZSTG_EXON_TRANS_GENES ( TRANSCRIPT_CLUSTER_ID VARCHAR2(8 BYTE) NOT NULL, UNIGENE_ID VARCHAR2(20 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


