/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_BIOGENES CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_BIOGENES  (Table) 
--
CREATE TABLE ZSTG_BIOGENES ( PATHWAY_NAME VARCHAR2(30 BYTE) NOT NULL, BC_ID VARCHAR2(60 BYTE) NOT NULL, LOCUS_ID VARCHAR2(40 BYTE) NOT NULL, TAXON_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


