/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_SNPREP_SNTV_IDS_MPNG CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_SNPREP_SNTV_IDS_MPNG  (Table) 
--
CREATE TABLE ZSTG_SNPREP_SNTV_IDS_MPNG ( SNPREPID NUMBER NOT NULL, ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


