/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_MICROSATELLITE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MICROSATELLITE  (Table) 
--
CREATE TABLE ZSTG_MICROSATELLITE ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, DISTANCE NUMBER NOT NULL, MARKER VARCHAR2(2500 BYTE) NOT NULL, RELATIVE_POSITION VARCHAR2(20 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


