/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_MOLECULECOMPONENTLABELS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MOLECULECOMPONENTLABELS  (Table) 
--
CREATE TABLE ZSTG_MOLECULECOMPONENTLABELS ( MOLECULE_ID VARCHAR2(2500 BYTE) NOT NULL, MTYPE VARCHAR2(2500 BYTE) NOT NULL, MOLECULE_ID_REF VARCHAR2(2500 BYTE) NOT NULL, LABEL_TYPE VARCHAR2(2500 BYTE) NOT NULL, VALUE VARCHAR2(2500 BYTE) NOT NULL, SOURCE_ID VARCHAR2(20 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


