ALTER TABLE ANIMALMODEL
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ANIMALMODEL CASCADE CONSTRAINTS PURGE
/

--
-- ANIMALMODEL  (Table) 
--
CREATE TABLE ANIMALMODEL ( ANIMALMODEL_ID NUMBER NOT NULL, EXPERIMENTDESIGN VARCHAR2(4000 BYTE) NULL, MODELDESCRIPTOR VARCHAR2(255 BYTE) NOT NULL, PHENOTYPE_ID NUMBER NULL, TAXON_ID NUMBER NOT NULL, AVAILABILITY_ID NUMBER NOT NULL, APPROVALSTATUS_ID NUMBER NOT NULL, JAXINFO_ID NUMBER NULL, REPOSITORYINFO_ID NUMBER NULL, URL VARCHAR2(200 BYTE) NULL, AVAILINVESTIGATOR NUMBER NULL, CONSTRAINT ANIMALMODEL_PK PRIMARY KEY (ANIMALMODEL_ID) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


