/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE AR_ALIGNMENTS CASCADE CONSTRAINTS PURGE
/

--
-- AR_ALIGNMENTS  (Table) 
--
CREATE TABLE AR_ALIGNMENTS ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, CHROMOSOME VARCHAR2(20 BYTE) NOT NULL, START_POSITION NUMBER NOT NULL, END_POSITION NUMBER NOT NULL, DIRECTION CHAR(1 BYTE) NOT NULL, TRIM_CHR VARCHAR2(50 BYTE) NOT NULL, ASSEMBLY VARCHAR2(50 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(100 BYTE) NOT NULL, CHROMOSOME_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


