DROP TABLE AR_ENSEMBL CASCADE CONSTRAINTS PURGE
/

--
-- AR_ENSEMBL  (Table) 
--
CREATE TABLE AR_ENSEMBL ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, ENSEMBL_ID VARCHAR2(20 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT ) MONITORING
/


