DROP TABLE AR_REFSEQ_PROTEIN CASCADE CONSTRAINTS PURGE
/

--
-- AR_REFSEQ_PROTEIN  (Table) 
--
CREATE TABLE AR_REFSEQ_PROTEIN ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, REFSEQ_PROTEIN_ID VARCHAR2(20 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


