ALTER TABLE AR_SWISSPROT_TMP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE AR_SWISSPROT_TMP CASCADE CONSTRAINTS PURGE
/

--
-- AR_SWISSPROT_TMP  (Table) 
--
CREATE TABLE AR_SWISSPROT_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, SWISSPROT_ID VARCHAR2(20 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL, PRIMARY KEY (PROBE_SET_ID, SWISSPROT_ID, GENECHIP_ARRAY) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


