/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE AR_SWISSPROT CASCADE CONSTRAINTS PURGE
/

--
-- AR_SWISSPROT  (Table) 
--
CREATE TABLE AR_SWISSPROT ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, SWISSPROT_ID VARCHAR2(20 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


