ALTER TABLE ARRAY_REPORTER
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ARRAY_REPORTER CASCADE CONSTRAINTS PURGE
/

--
-- ARRAY_REPORTER  (Table) 
--
--  Dependencies: 
--   MICROARRAY (Table)
--
CREATE TABLE ARRAY_REPORTER ( ID NUMBER NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, MICROARRAY_ID NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT REPORTER_PK PRIMARY KEY (ID), UNIQUE (NAME, MICROARRAY_ID), CONSTRAINT ARRREPMAFK FOREIGN KEY (MICROARRAY_ID) REFERENCES MICROARRAY (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


