/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE BIO_PATHWAYS_TV
 DROP PRIMARY KEY CASCADE
/
DROP TABLE BIO_PATHWAYS_TV CASCADE CONSTRAINTS PURGE
/

--
-- BIO_PATHWAYS_TV  (Table) 
--
--  Dependencies: 
--   TAXON (Table)
--
CREATE TABLE BIO_PATHWAYS_TV ( PATHWAY_ID NUMBER NOT NULL, PATHWAY_NAME VARCHAR2(2500 BYTE) NOT NULL, PATHWAY_DISPLAY VARCHAR2(2500 BYTE) NOT NULL, TAXON NUMBER NOT NULL, PATHWAY_DIAGRAM_NAME VARCHAR2(2500 BYTE) NULL, PATHWAY_DESC CLOB NULL, PATHWAY_DIAGRAM CLOB NULL, BIG_ID VARCHAR2(200 BYTE) NULL, LONG_NAME VARCHAR2(2500 BYTE) NULL, CURATOR VARCHAR2(2500 BYTE) NULL, REVIEWER VARCHAR2(2500 BYTE) NULL, SOURCE VARCHAR2(2500 BYTE) NOT NULL, PID_ID NUMBER NULL, CONSTRAINT PK_BIO_PATHWAYS_TV PRIMARY KEY (PATHWAY_ID), CONSTRAINT BPTBIGID UNIQUE (BIG_ID) DISABLE, CONSTRAINT PATHWAYS_UNIQ UNIQUE (TAXON, SOURCE, PATHWAY_NAME), CONSTRAINT BPTV FOREIGN KEY (TAXON) REFERENCES TAXON (TAXON_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS LOB (PATHWAY_DESC) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (PATHWAY_DIAGRAM) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


