ALTER TABLE CYTOBAND
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CYTOBAND CASCADE CONSTRAINTS PURGE
/

--
-- CYTOBAND  (Table) 
--
--  Dependencies: 
--   CHROMOSOME (Table)
--   PHYSICAL_LOCATION (Table)
--
CREATE TABLE CYTOBAND ( ID NUMBER NOT NULL, NAME VARCHAR2(50 BYTE) NOT NULL, PHYSICAL_LOCATION_ID NUMBER NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CHROMOSOME_ID NUMBER NOT NULL, CONSTRAINT CYTOPK PRIMARY KEY (ID), CONSTRAINT CYTOBIGID UNIQUE (BIG_ID), CONSTRAINT CYTOPL UNIQUE (PHYSICAL_LOCATION_ID), CONSTRAINT CYTOUNIQ UNIQUE (CHROMOSOME_ID, NAME), UNIQUE (NAME, PHYSICAL_LOCATION_ID, CHROMOSOME_ID), CONSTRAINT CYTOFK FOREIGN KEY (CHROMOSOME_ID) REFERENCES CHROMOSOME (CHROMOSOME_ID), FOREIGN KEY (PHYSICAL_LOCATION_ID) REFERENCES PHYSICAL_LOCATION (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


