/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE GENERIC_ARRAY_GENERIC_REPORTER
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENERIC_ARRAY_GENERIC_REPORTER CASCADE CONSTRAINTS PURGE
/

--
-- GENERIC_ARRAY_GENERIC_REPORTER  (Table) 
--
--  Dependencies: 
--   GENERIC_ARRAY (Table)
--   GENERIC_REPORTER (Table)
--
CREATE TABLE GENERIC_ARRAY_GENERIC_REPORTER ( GENERIC_ARRAY_ID NUMBER(8,2) NULL, GENERIC_REPORTER_ID NUMBER(8,2) NULL, CONSTRAINT GRGPPK PRIMARY KEY (GENERIC_ARRAY_ID, GENERIC_REPORTER_ID), CONSTRAINT GRFK1 FOREIGN KEY (GENERIC_ARRAY_ID) REFERENCES GENERIC_ARRAY (ID), CONSTRAINT GRGPFK FOREIGN KEY (GENERIC_REPORTER_ID) REFERENCES GENERIC_REPORTER (ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


