/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE GENE_HISTOPATHOLOGY CASCADE CONSTRAINTS PURGE
/

--
-- GENE_HISTOPATHOLOGY  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--
CREATE TABLE GENE_HISTOPATHOLOGY ( GENE_ID NUMBER NOT NULL, CONTEXT_CODE NUMBER NOT NULL, FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


