ALTER TABLE HOMOLOGOUS_ASSOCIATION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE HOMOLOGOUS_ASSOCIATION CASCADE CONSTRAINTS PURGE
/

--
-- HOMOLOGOUS_ASSOCIATION  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--
CREATE TABLE HOMOLOGOUS_ASSOCIATION ( ID NUMBER NOT NULL, SIMILARITY_PERCENTAGE FLOAT(126) NOT NULL, HOMOLOGOUS_ID NUMBER NOT NULL, HOMOLOGOUS_GENE_ID NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT HA_SP CHECK (SIMILARITY_PERCENTAGE <=100), CONSTRAINT PK_HOMOLOGOUS_ASSOCIATION PRIMARY KEY (ID), CONSTRAINT HABIGID UNIQUE (BIG_ID), UNIQUE (SIMILARITY_PERCENTAGE, HOMOLOGOUS_GENE_ID, HOMOLOGOUS_ID), CONSTRAINT HA_FK1 FOREIGN KEY (HOMOLOGOUS_GENE_ID) REFERENCES GENE_TV (GENE_ID), CONSTRAINT HA_FK2 FOREIGN KEY (HOMOLOGOUS_ID) REFERENCES GENE_TV (GENE_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


