/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE KEYWORD
 DROP PRIMARY KEY CASCADE
/
DROP TABLE KEYWORD CASCADE CONSTRAINTS PURGE
/

--
-- KEYWORD  (Table) 
--
CREATE TABLE KEYWORD ( ID NUMBER NOT NULL, SCORE NUMBER NOT NULL, VALUE VARCHAR2(512 BYTE) NOT NULL, CONSTRAINT PK_KEYWORD PRIMARY KEY (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


