/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE MARKER_MARKER_REL_LOCATION CASCADE CONSTRAINTS PURGE
/

--
-- MARKER_MARKER_REL_LOCATION  (Table) 
--
--  Dependencies: 
--   MARKER (Table)
--   MARKER_RELATIVE_LOCATION (Table)
--
CREATE TABLE MARKER_MARKER_REL_LOCATION ( MARKER_ID NUMBER NOT NULL, MARKER_REL_LOCATION_ID NUMBER NOT NULL, SORT_ORDER NUMBER NULL, UNIQUE (MARKER_REL_LOCATION_ID, SORT_ORDER, MARKER_ID), CONSTRAINT MMRL FOREIGN KEY (MARKER_ID) REFERENCES MARKER (ID), CONSTRAINT MMRLFK2 FOREIGN KEY (MARKER_REL_LOCATION_ID) REFERENCES MARKER_RELATIVE_LOCATION (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


