/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE MARKER_LOOKUP CASCADE CONSTRAINTS PURGE
/

--
-- MARKER_LOOKUP  (Table) 
--
CREATE TABLE MARKER_LOOKUP ( NAME VARCHAR2(100 BYTE) NOT NULL, ID NUMBER NOT NULL, TAXON_ID NUMBER NOT NULL, CONSTRAINT MR_LK UNIQUE (NAME, ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


