/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE MARKER_MARKER_ALIAS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE MARKER_MARKER_ALIAS CASCADE CONSTRAINTS PURGE
/

--
-- MARKER_MARKER_ALIAS  (Table) 
--
--  Dependencies: 
--   MARKER (Table)
--   MARKER_ALIAS (Table)
--
CREATE TABLE MARKER_MARKER_ALIAS ( MARKER_ID NUMBER NOT NULL, MARKER_ALIAS_ID NUMBER NOT NULL, CONSTRAINT PK_MARKER_MARKER_ALIAS PRIMARY KEY (MARKER_ALIAS_ID, MARKER_ID), CONSTRAINT MMAFK1 FOREIGN KEY (MARKER_ID) REFERENCES MARKER (ID), CONSTRAINT MMAFK2 FOREIGN KEY (MARKER_ALIAS_ID) REFERENCES MARKER_ALIAS (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


