/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE NOMENCLATURE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE NOMENCLATURE CASCADE CONSTRAINTS PURGE
/

--
-- NOMENCLATURE  (Table) 
--
CREATE TABLE NOMENCLATURE ( NOMENCLATURE_ID NUMBER NOT NULL, NAME VARCHAR2(100 BYTE) NOT NULL, CONSTRAINT NOMENPK PRIMARY KEY (NOMENCLATURE_ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


