DROP TABLE OBJECT_MAP CASCADE CONSTRAINTS PURGE
/

--
-- OBJECT_MAP  (Table) 
--
CREATE TABLE OBJECT_MAP ( OBJECT_NAME VARCHAR2(50 BYTE) NOT NULL, ATTRIBUTE_NAME VARCHAR2(50 BYTE) NOT NULL, CRITERIA_TYPE VARCHAR2(50 BYTE) NOT NULL, TABLE_NAME VARCHAR2(50 BYTE) NOT NULL, ASSOCIATED_TABLE_NAME VARCHAR2(50 BYTE) NULL, ID_COLUMN_NAME VARCHAR2(50 BYTE) NOT NULL, ASSOCIATED_ID_COLUMN_NAME VARCHAR2(50 BYTE) NULL, COLUMN_NAME VARCHAR2(50 BYTE) NOT NULL, ATTRIBUTE_DATA_TYPE VARCHAR2(50 BYTE) NOT NULL, OBJECT_SELECTION_COLUMN_NAME VARCHAR2(50 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


