/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ORGAN
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ORGAN CASCADE CONSTRAINTS PURGE
/

--
-- ORGAN  (Table) 
--
CREATE TABLE ORGAN ( ORGAN_ID NUMBER NOT NULL, DESCRIPTION VARCHAR2(150 BYTE) NOT NULL, PRIMARY KEY (ORGAN_ID, DESCRIPTION) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


