/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PARTY_CONTACTINFO
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PARTY_CONTACTINFO CASCADE CONSTRAINTS PURGE
/

--
-- PARTY_CONTACTINFO  (Table) 
--
CREATE TABLE PARTY_CONTACTINFO ( PARTY_ID NUMBER NULL, CONTACTINFO_ID NUMBER NULL, CONSTRAINT PCPK PRIMARY KEY (PARTY_ID, CONTACTINFO_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


