/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PID_ENTITY_ACCESSION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_ENTITY_ACCESSION CASCADE CONSTRAINTS PURGE
/

--
-- PID_ENTITY_ACCESSION  (Table) 
--
CREATE TABLE PID_ENTITY_ACCESSION ( ID NUMBER NOT NULL, ACCESSION VARCHAR2(2500 BYTE) NOT NULL, DATABASE VARCHAR2(2500 BYTE) NOT NULL, PID_PHYSICALENTITY_ID NUMBER NOT NULL, BIG_ID VARCHAR2(2500 BYTE) NULL, PRIMARY KEY (ID), UNIQUE (ACCESSION, DATABASE), UNIQUE (BIG_ID) DISABLE, UNIQUE (ACCESSION, DATABASE, PID_PHYSICALENTITY_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


