/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE PID_ENTITY_SEQUENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_ENTITY_SEQUENCE CASCADE CONSTRAINTS PURGE
/

--
-- PID_ENTITY_SEQUENCE  (Table) 
--
--  Dependencies: 
--   PID_PHYSICAL_ENTITY (Table)
--   NUCLEIC_ACID_SEQUENCE (Table)
--
CREATE TABLE PID_ENTITY_SEQUENCE ( PHYSICAL_ENTITY_ID NUMBER NOT NULL, NUCLEIC_ACID_SEQUENCE_ID NUMBER NOT NULL, PRIMARY KEY (PHYSICAL_ENTITY_ID, NUCLEIC_ACID_SEQUENCE_ID), FOREIGN KEY (PHYSICAL_ENTITY_ID) REFERENCES PID_PHYSICAL_ENTITY (ID), FOREIGN KEY (NUCLEIC_ACID_SEQUENCE_ID) REFERENCES NUCLEIC_ACID_SEQUENCE (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


