ALTER TABLE PROTEIN_SEQUENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PROTEIN_SEQUENCE CASCADE CONSTRAINTS PURGE
/

--
-- PROTEIN_SEQUENCE  (Table) 
--
--  Dependencies: 
--   NEW_PROTEIN (Table)
--
CREATE TABLE PROTEIN_SEQUENCE ( DALTONWEIGHT FLOAT(126) NOT NULL, CHECKSUM VARCHAR2(50 BYTE) NOT NULL, PROTEIN_ID NUMBER NOT NULL, VALUE CLOB NOT NULL, LENGTH NUMBER NOT NULL, ID NUMBER NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT PS_PK PRIMARY KEY (ID), CONSTRAINT PROTSEQ UNIQUE (BIG_ID), UNIQUE (DALTONWEIGHT, CHECKSUM, PROTEIN_ID, LENGTH), CONSTRAINT PSFK FOREIGN KEY (PROTEIN_ID) REFERENCES NEW_PROTEIN (PROTEIN_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS LOB (VALUE) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


