DROP TABLE PROTOCOL_DISEASES CASCADE CONSTRAINTS PURGE
/

--
-- PROTOCOL_DISEASES  (Table) 
--
CREATE TABLE PROTOCOL_DISEASES ( ID NUMBER(10) NOT NULL, PRO_ID NUMBER(10) NOT NULL, IMT_CODE NUMBER(8) NULL, CTEP_NAME VARCHAR2(100 BYTE) NULL, DISEASE_SUB_CATEGORY VARCHAR2(255 BYTE) NULL, DISEASE_CATEGORY VARCHAR2(255 BYTE) NULL, HISTOLOGY_CODE NUMBER NULL, CONCEPT_ID VARCHAR2(10 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


