/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE PROVENANCE CASCADE CONSTRAINTS PURGE
/

--
-- PROVENANCE  (Table) 
--
CREATE TABLE PROVENANCE ( ID NUMBER NOT NULL, EVIDENCE_CODE VARCHAR2(50 BYTE) NOT NULL, TRANSFORMATION CLOB NULL, SOURCE_REFERENCE_ID NUMBER NULL, IMMEDIATE_SOURCE_ID NUMBER NOT NULL, SUPPLYING_SOURCE_ID NUMBER NOT NULL, ORIGINAL_SOURCE_ID NUMBER NOT NULL, FULLY_QUALIFIED_CLASS_NAME VARCHAR2(75 BYTE) NOT NULL, OBJECT_IDENTIFIER VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS LOB (TRANSFORMATION) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


