DROP TABLE PUBLICATION CASCADE CONSTRAINTS PURGE
/

--
-- PUBLICATION  (Table) 
--
CREATE TABLE PUBLICATION ( PUBLICATION_ID NUMBER NULL, JOURNAL VARCHAR2(100 BYTE) NULL, PUBLICATIONSTATUS_ID NUMBER NULL, VOLUME VARCHAR2(100 BYTE) NULL, STARTPAGE NUMBER NULL, PMID NUMBER NULL, YEAR VARCHAR2(4 BYTE) NULL, AUTHORS VARCHAR2(255 BYTE) NULL, TITLE VARCHAR2(500 BYTE) NULL, ENDPAGE NUMBER NULL, THERAPY_ID NUMBER NULL, CELLLINE_ID NUMBER NULL, ANIMALMODEL_ID NUMBER NULL, YEASTMODEL_ID NUMBER NULL, XENOGRAFT_ID NUMBER NULL, ABSTRACTCANCERMODEL_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


