/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE RELATIVE_LOCATION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE RELATIVE_LOCATION CASCADE CONSTRAINTS PURGE
/

--
-- RELATIVE_LOCATION  (Table) 
--
CREATE TABLE RELATIVE_LOCATION ( ID NUMBER NOT NULL, ORIENTATION VARCHAR2(50 BYTE) NULL, DISTANCE VARCHAR2(50 BYTE) NOT NULL, SNP_ID NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT REL_LOCATION_PK PRIMARY KEY (ID), CONSTRAINT RCHBIGID UNIQUE (BIG_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


