/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE SAMPLE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SAMPLE CASCADE CONSTRAINTS PURGE
/

--
-- SAMPLE  (Table) 
--
CREATE TABLE SAMPLE ( SAMPLE_ID NUMBER NOT NULL, TAXON_ID NUMBER NOT NULL, CONSTRAINT SAMPK PRIMARY KEY (SAMPLE_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


