/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE STG_KEYWORD CASCADE CONSTRAINTS PURGE
/

--
-- STG_KEYWORD  (Table) 
--
CREATE TABLE STG_KEYWORD ( SCORE NUMBER NULL, VALUE VARCHAR2(512 BYTE) NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


