/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE STG_KEYWORD_AGG CASCADE CONSTRAINTS PURGE
/

--
-- STG_KEYWORD_AGG  (Table) 
--
CREATE TABLE STG_KEYWORD_AGG ( SCORE NUMBER NOT NULL, VALUE VARCHAR2(512 BYTE) NOT NULL, TYPE VARCHAR2(255 BYTE) NOT NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


