/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_GENE_GENEALIAS_CGID
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE_GENEALIAS_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE_GENEALIAS_CGID  (Table) 
--
CREATE TABLE ZSTG_GENE_GENEALIAS_CGID ( GENE_ID NUMBER NOT NULL, ALIAS NVARCHAR2(1000) NULL, CHECK ("ALIAS" IS NOT NULL) DISABLE, PRIMARY KEY (GENE_ID, ALIAS) DISABLE ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


