/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_CMAP_NAMES CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_CMAP_NAMES  (Table) 
--
CREATE TABLE ZSTG_CMAP_NAMES ( CMAP_ID NUMBER NOT NULL, CMAP_NAME VARCHAR2(250 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


