/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_GENE_DISEASE_EVID_CGID
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE_DISEASE_EVID_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE_DISEASE_EVID_CGID  (Table) 
--
CREATE TABLE ZSTG_GENE_DISEASE_EVID_CGID ( GENE_ID NUMBER NULL, DISEASE_ID NUMBER NULL, EVIDENCE_ID NUMBER NULL, ROLE_ID VARCHAR2(1000 BYTE) NULL, CONSTRAINT GDER PRIMARY KEY (GENE_ID, DISEASE_ID, EVIDENCE_ID, ROLE_ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


