/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

ALTER TABLE ZSTG_MARKER_ALIAS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_MARKER_ALIAS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MARKER_ALIAS  (Table) 
--
CREATE TABLE ZSTG_MARKER_ALIAS ( ID NUMBER NOT NULL, NAME VARCHAR2(500 BYTE) NOT NULL, MARKER_ID VARCHAR2(500 BYTE) NOT NULL, CONSTRAINT PK_ZSTG_MARKER_ALIAS PRIMARY KEY (ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


