/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_ROLECODE_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_ROLECODE_CGID  (Table) 
--
CREATE TABLE ZSTG_ROLECODE_CGID ( ROLECODE NVARCHAR2(1000) NOT NULL, ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


