/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_TARGET CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_TARGET  (Table) 
--
CREATE TABLE ZSTG_TARGET ( TARGET_ID NUMBER NOT NULL, TARGET_TYPE CHAR(100 BYTE) NOT NULL, TARGET_NAME VARCHAR2(100 BYTE) NOT NULL, LOCUS_ID NUMBER NULL, BIG_ID VARCHAR2(200 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


