/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_EXON_TRANS_AFFY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_EXON_TRANS_AFFY  (Table) 
--
CREATE TABLE ZSTG_EXON_TRANS_AFFY ( TRANSCRIPT_CLUSTER_ID VARCHAR2(8 BYTE) NOT NULL, PROBE_SET_ID VARCHAR2(8 BYTE) NOT NULL, SEQNAME VARCHAR2(20 BYTE) NULL, STRAND VARCHAR2(1 BYTE) NULL, START_LOCATION VARCHAR2(10 BYTE) NULL, STOP_LOCATION VARCHAR2(10 BYTE) NULL, TOTAL_PROBES VARCHAR2(10 BYTE) NULL, GENE_ASSIGNMENT CLOB NULL, MRNA_ASSIGNMENT CLOB NULL, SWISSPROT CLOB NULL, UNIGENE CLOB NULL, GO_BIOPROCESS CLOB NULL, GO_CELLULAR_COMPONENT CLOB NULL, GO_MOLECULAR_FUNCTION CLOB NULL, PATHWAY CLOB NULL, PROTEIN_DOMAINS CLOB NULL, CATEGORY VARCHAR2(50 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS LOB (GENE_ASSIGNMENT) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (MRNA_ASSIGNMENT) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (SWISSPROT) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (UNIGENE) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (GO_BIOPROCESS) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (GO_CELLULAR_COMPONENT) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (GO_MOLECULAR_FUNCTION) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (PATHWAY) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (PROTEIN_DOMAINS) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


