/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_INTERPRO CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_INTERPRO  (Table) 
--
CREATE TABLE ZSTG_INTERPRO ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, ACCESSION_NUMBER VARCHAR2(20 BYTE) NOT NULL, DESCRIPTION VARCHAR2(2000 BYTE) NULL, SCORE FLOAT(126) NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


