/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_HSMM_SEQ CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_HSMM_SEQ  (Table) 
--
CREATE TABLE ZSTG_HSMM_SEQ ( ID NUMBER NOT NULL, ACCESSION_NUMBER VARCHAR2(50 BYTE) NOT NULL, VERSION VARCHAR2(50 BYTE) NOT NULL, SEQUENCE_TYPE VARCHAR2(50 BYTE) NOT NULL, CLONE_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


