ALTER TABLE ZSTG_MAP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_MAP CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_MAP  (Table) 
--
CREATE TABLE ZSTG_MAP ( MAP_ID NUMBER NOT NULL, MAP_TYPE VARCHAR2(2 BYTE) NOT NULL, MAP_LOCATION VARCHAR2(200 BYTE) NOT NULL, CHROMOSOME_ID NUMBER NOT NULL, TAXON_ID NUMBER NOT NULL, CYTOBAND VARCHAR2(50 BYTE) NOT NULL, CHROMOSOME_NUMBER VARCHAR2(10 BYTE) NOT NULL, START_CYTOBAND VARCHAR2(50 BYTE) NOT NULL, END_CYTOBAND VARCHAR2(50 BYTE) NOT NULL, PRIMARY KEY (MAP_ID, MAP_TYPE, MAP_LOCATION, CHROMOSOME_ID, TAXON_ID, CYTOBAND, CHROMOSOME_NUMBER, START_CYTOBAND, END_CYTOBAND) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


