ALTER TABLE ZSTG_OLD_PROTOCOLS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_OLD_PROTOCOLS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_OLD_PROTOCOLS  (Table) 
--
CREATE TABLE ZSTG_OLD_PROTOCOLS ( ID NUMBER(10) NOT NULL, DOCUMENT_NUMBER VARCHAR2(35 BYTE) NOT NULL, TITLE VARCHAR2(2000 BYTE) NOT NULL, PHASE VARCHAR2(10 BYTE) NULL, PARTICIPATION_TYPE VARCHAR2(35 BYTE) NOT NULL, TREATMENT_FLAG VARCHAR2(5 BYTE) NULL, NIH_ADMIN_CODE VARCHAR2(10 BYTE) NULL, CURRENT_STATUS VARCHAR2(40 BYTE) NOT NULL, CURRENT_STATUS_DATE DATE NOT NULL, LEAD_ORGANIZATION_CTEP_ID VARCHAR2(6 BYTE) NOT NULL, LEAD_ORGANIZATION_NAME VARCHAR2(100 BYTE) NOT NULL, PI_NAME VARCHAR2(85 BYTE) NULL, REVIEWER_NAME VARCHAR2(85 BYTE) NULL, PDQ_PROTOCOL_CODE VARCHAR2(50 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NOT NULL, CONSTRAINT PK_PROTOCOLS PRIMARY KEY (ID) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


