DROP TABLE ZSTG_PID_INTERACTION CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_INTERACTION  (Table) 
--
CREATE TABLE ZSTG_PID_INTERACTION ( INTERACTION_ID NUMBER NOT NULL, SOURCE VARCHAR2(2500 BYTE) NOT NULL, TYPE VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


