DROP TABLE ZSTG_INTERPRO_TMP CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_INTERPRO_TMP  (Table) 
--
CREATE TABLE ZSTG_INTERPRO_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, ACCESSION_NUMBER VARCHAR2(20 BYTE) NOT NULL, DESCRIPTION VARCHAR2(2000 BYTE) NOT NULL, SCORE FLOAT(22) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


