/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP TABLE ZSTG_PID_PHYSICALENTITY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_PHYSICALENTITY  (Table) 
--
CREATE TABLE ZSTG_PID_PHYSICALENTITY ( PHYSICALENTITY_ID NUMBER NOT NULL, TYPE VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


