DROP TABLE ZSTG_PID_INTERACTIONREFERENCE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_INTERACTIONREFERENCE  (Table) 
--
CREATE TABLE ZSTG_PID_INTERACTIONREFERENCE ( INTERACTION_ID NUMBER NOT NULL, PUBMED_ID NUMBER NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


