ALTER TABLE ZSTG_OMIM2GENE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_OMIM2GENE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_OMIM2GENE  (Table) 
--
CREATE TABLE ZSTG_OMIM2GENE ( OMIM_NUMBER NUMBER NOT NULL, GENEID NUMBER NOT NULL, TYPE VARCHAR2(10 BYTE) NOT NULL, PRIMARY KEY (OMIM_NUMBER, GENEID, TYPE) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


