package gov.nih.nci.maservice.service;

import gov.nih.nci.cagrid.introduce.servicetools.ServiceConfiguration;

import org.globus.wsrf.config.ContainerConfig;
import java.io.File;
import javax.naming.InitialContext;

import org.apache.axis.MessageContext;
import org.globus.wsrf.Constants;


/** 
 * DO NOT EDIT:  This class is autogenerated!
 * 
 * This class holds all service properties which were defined for the service to have
 * access to.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class MaGridServiceConfiguration implements ServiceConfiguration {

	public static MaGridServiceConfiguration  configuration = null;
    public String etcDirectoryPath;
    	
	public static MaGridServiceConfiguration getConfiguration() throws Exception {
		if (MaGridServiceConfiguration.configuration != null) {
			return MaGridServiceConfiguration.configuration;
		}
		MessageContext ctx = MessageContext.getCurrentContext();

		String servicePath = ctx.getTargetService();

		String jndiName = Constants.JNDI_SERVICES_BASE_NAME + servicePath + "/serviceconfiguration";
		try {
			javax.naming.Context initialContext = new InitialContext();
			MaGridServiceConfiguration.configuration = (MaGridServiceConfiguration) initialContext.lookup(jndiName);
		} catch (Exception e) {
			throw new Exception("Unable to instantiate service configuration.", e);
		}

		return MaGridServiceConfiguration.configuration;
	}
	

	
	private String queryProcessorClass;
	
	private String dataService_domainModelValidatorClass;
	
	private String cqlQueryProcessorConfig_applicationName;
	
	private String cqlQueryProcessorConfig_useLocalApiFlag;
	
	private String cqlQueryProcessorConfig_applicationHostName;
	
	private String cqlQueryProcessorConfig_applicationHostPort;
	
	private String cqlQueryProcessorConfig_useHttpsUrl;
	
	private String cqlQueryProcessorConfig_useStaticLogin;
	
	private String cqlQueryProcessorConfig_useGridIdentityLogin;
	
	private String cqlQueryProcessorConfig_staticLoginPass;
	
	private String cqlQueryProcessorConfig_staticLoginUser;
	
	private String serverConfigLocation;
	
	private String dataService_cqlValidatorClass;
	
	private String dataService_validateCqlFlag;
	
	private String dataService_validateDomainModelFlag;
	
	private String dataService_classMappingsFilename;
	
	
    public String getEtcDirectoryPath() {
		return ContainerConfig.getBaseDirectory() + File.separator + etcDirectoryPath;
	}
	
	public void setEtcDirectoryPath(String etcDirectoryPath) {
		this.etcDirectoryPath = etcDirectoryPath;
	}


	
	public String getQueryProcessorClass() {
		return queryProcessorClass;
	}
	
	
	public void setQueryProcessorClass(String queryProcessorClass) {
		this.queryProcessorClass = queryProcessorClass;
	}

	
	public String getDataService_domainModelValidatorClass() {
		return dataService_domainModelValidatorClass;
	}
	
	
	public void setDataService_domainModelValidatorClass(String dataService_domainModelValidatorClass) {
		this.dataService_domainModelValidatorClass = dataService_domainModelValidatorClass;
	}

	
	public String getCqlQueryProcessorConfig_applicationName() {
		return cqlQueryProcessorConfig_applicationName;
	}
	
	
	public void setCqlQueryProcessorConfig_applicationName(String cqlQueryProcessorConfig_applicationName) {
		this.cqlQueryProcessorConfig_applicationName = cqlQueryProcessorConfig_applicationName;
	}

	
	public String getCqlQueryProcessorConfig_useLocalApiFlag() {
		return cqlQueryProcessorConfig_useLocalApiFlag;
	}
	
	
	public void setCqlQueryProcessorConfig_useLocalApiFlag(String cqlQueryProcessorConfig_useLocalApiFlag) {
		this.cqlQueryProcessorConfig_useLocalApiFlag = cqlQueryProcessorConfig_useLocalApiFlag;
	}

	
	public String getCqlQueryProcessorConfig_applicationHostName() {
		return cqlQueryProcessorConfig_applicationHostName;
	}
	
	
	public void setCqlQueryProcessorConfig_applicationHostName(String cqlQueryProcessorConfig_applicationHostName) {
		this.cqlQueryProcessorConfig_applicationHostName = cqlQueryProcessorConfig_applicationHostName;
	}

	
	public String getCqlQueryProcessorConfig_applicationHostPort() {
		return cqlQueryProcessorConfig_applicationHostPort;
	}
	
	
	public void setCqlQueryProcessorConfig_applicationHostPort(String cqlQueryProcessorConfig_applicationHostPort) {
		this.cqlQueryProcessorConfig_applicationHostPort = cqlQueryProcessorConfig_applicationHostPort;
	}

	
	public String getCqlQueryProcessorConfig_useHttpsUrl() {
		return cqlQueryProcessorConfig_useHttpsUrl;
	}
	
	
	public void setCqlQueryProcessorConfig_useHttpsUrl(String cqlQueryProcessorConfig_useHttpsUrl) {
		this.cqlQueryProcessorConfig_useHttpsUrl = cqlQueryProcessorConfig_useHttpsUrl;
	}

	
	public String getCqlQueryProcessorConfig_useStaticLogin() {
		return cqlQueryProcessorConfig_useStaticLogin;
	}
	
	
	public void setCqlQueryProcessorConfig_useStaticLogin(String cqlQueryProcessorConfig_useStaticLogin) {
		this.cqlQueryProcessorConfig_useStaticLogin = cqlQueryProcessorConfig_useStaticLogin;
	}

	
	public String getCqlQueryProcessorConfig_useGridIdentityLogin() {
		return cqlQueryProcessorConfig_useGridIdentityLogin;
	}
	
	
	public void setCqlQueryProcessorConfig_useGridIdentityLogin(String cqlQueryProcessorConfig_useGridIdentityLogin) {
		this.cqlQueryProcessorConfig_useGridIdentityLogin = cqlQueryProcessorConfig_useGridIdentityLogin;
	}

	
	public String getCqlQueryProcessorConfig_staticLoginPass() {
		return cqlQueryProcessorConfig_staticLoginPass;
	}
	
	
	public void setCqlQueryProcessorConfig_staticLoginPass(String cqlQueryProcessorConfig_staticLoginPass) {
		this.cqlQueryProcessorConfig_staticLoginPass = cqlQueryProcessorConfig_staticLoginPass;
	}

	
	public String getCqlQueryProcessorConfig_staticLoginUser() {
		return cqlQueryProcessorConfig_staticLoginUser;
	}
	
	
	public void setCqlQueryProcessorConfig_staticLoginUser(String cqlQueryProcessorConfig_staticLoginUser) {
		this.cqlQueryProcessorConfig_staticLoginUser = cqlQueryProcessorConfig_staticLoginUser;
	}

	
	public String getServerConfigLocation() {
		return ContainerConfig.getBaseDirectory() + File.separator + serverConfigLocation;
	}
	
	
	public void setServerConfigLocation(String serverConfigLocation) {
		this.serverConfigLocation = serverConfigLocation;
	}

	
	public String getDataService_cqlValidatorClass() {
		return dataService_cqlValidatorClass;
	}
	
	
	public void setDataService_cqlValidatorClass(String dataService_cqlValidatorClass) {
		this.dataService_cqlValidatorClass = dataService_cqlValidatorClass;
	}

	
	public String getDataService_validateCqlFlag() {
		return dataService_validateCqlFlag;
	}
	
	
	public void setDataService_validateCqlFlag(String dataService_validateCqlFlag) {
		this.dataService_validateCqlFlag = dataService_validateCqlFlag;
	}

	
	public String getDataService_validateDomainModelFlag() {
		return dataService_validateDomainModelFlag;
	}
	
	
	public void setDataService_validateDomainModelFlag(String dataService_validateDomainModelFlag) {
		this.dataService_validateDomainModelFlag = dataService_validateDomainModelFlag;
	}

	
	public String getDataService_classMappingsFilename() {
		return ContainerConfig.getBaseDirectory() + File.separator + dataService_classMappingsFilename;
	}
	
	
	public void setDataService_classMappingsFilename(String dataService_classMappingsFilename) {
		this.dataService_classMappingsFilename = dataService_classMappingsFilename;
	}

	
}
