function FileData_Pairs(x)
{
x.t("searching","cabio");
x.t("columns","perform");
x.t("build","custom");
x.t("advanced","search");
x.t("custom","target");
x.t("custom","queries");
x.t("custom","attributes");
x.t("perform","advanced");
x.t("search","advanced");
x.t("search","cabio");
x.t("search","powerful");
x.t("search","performing");
x.t("search","using");
x.t("search","tab");
x.t("portlet","searching");
x.t("portlet","click");
x.t("allows","build");
x.t("target","class");
x.t("cabio","portlet");
x.t("cabio","data");
x.t("queries","selecting");
x.t("powerful","tool");
x.t("performing","advanced");
x.t("click","advanced");
x.t("selecting","custom");
x.t("data","performing");
x.t("tool","allows");
x.t("classes","custom");
x.t("using","cabio");
x.t("class","associated");
x.t("associated","classes");
x.t("attributes","columns");
}
