function FileData_Pairs(x)
{
x.t("hugo","symbol");
x.t("field","reporter");
x.t("down","list");
x.t("reporter","name");
x.t("reporter","lookup");
x.t("dbsnp","string");
x.t("list","reporter");
x.t("snp","dbsnp");
x.t("gene","gene");
x.t("gene","symbol");
x.t("creating","reports");
x.t("name","string");
x.t("name","microarray");
x.t("name","drop");
x.t("portlet","creating");
x.t("string","input");
x.t("input","field");
x.t("cabio","portlet");
x.t("cabio","data");
x.t("annotations","reporter");
x.t("annotations","microarray");
x.t("annotations","using");
x.t("reports","cabio");
x.t("microarray","name");
x.t("microarray","annotations");
x.t("drop","down");
x.t("data","microarray");
x.t("using","cabio");
x.t("lookup","snp");
x.t("lookup","gene");
x.t("lookup","name");
x.t("symbol","hugo");
x.t("symbol","string");
}
