function FileData_Pairs(x)
{
x.t("available","pathways");
x.t("description","gene/hugo");
x.t("description","pathway");
x.t("hugo","symbol");
x.t("want","include");
x.t("gene","hugo");
x.t("gene","report");
x.t("creating","reports");
x.t("name","want");
x.t("name","report");
x.t("name","enter");
x.t("gene/hugo","symbol");
x.t("portlet","creating");
x.t("cabio","portlet");
x.t("cabio","data");
x.t("report","option");
x.t("report","pathway");
x.t("reports","available");
x.t("reports","cabio");
x.t("pathways","pathways");
x.t("pathways","following");
x.t("pathways","using");
x.t("pathways","category");
x.t("option","description");
x.t("enter","gene");
x.t("enter","pathway");
x.t("include","report");
x.t("data","pathways");
x.t("following","reports");
x.t("using","cabio");
x.t("symbol","want");
x.t("symbol","enter");
x.t("category","pathway");
x.t("pathway","gene");
x.t("pathway","name");
}
