function FileData_Pairs(x)
{
x.t("hugo","symbol");
x.t("field","gene");
x.t("field","agent");
x.t("diseases","agents");
x.t("disease","gene");
x.t("disease","name");
x.t("agents","gene");
x.t("gene","diseases");
x.t("gene","disease");
x.t("gene","index");
x.t("gene","agent");
x.t("gene","symbol");
x.t("creating","reports");
x.t("name","evs");
x.t("portlet","creating");
x.t("string","input");
x.t("cancer","gene");
x.t("concept","code");
x.t("input","field");
x.t("cabio","portlet");
x.t("cabio","data");
x.t("evs","concept");
x.t("index","disease");
x.t("index","cancer");
x.t("index","using");
x.t("reports","cabio");
x.t("code","string");
x.t("data","cancer");
x.t("agent","gene");
x.t("agent","name");
x.t("using","cabio");
x.t("symbol","hugo");
x.t("symbol","string");
}
