function FileData_Pairs(x)
{
x.t("provide","pre-configured");
x.t("available","within");
x.t("available","options");
x.t("within","select");
x.t("categories","range");
x.t("gene","index");
x.t("creating","report");
x.t("creating","reports");
x.t("functionality","categories");
x.t("range","query");
x.t("searches","categorized");
x.t("portlet","creating");
x.t("cancer","gene");
x.t("categorized","functionality");
x.t("cabio","portlet");
x.t("cabio","data");
x.t("select","report");
x.t("select","category");
x.t("options","creating");
x.t("annotations","pathways");
x.t("annotations","genomic");
x.t("index","select");
x.t("report","available");
x.t("reports","provide");
x.t("reports","available");
x.t("reports","cabio");
x.t("microarray","annotations");
x.t("pathways","cancer");
x.t("data","creating");
x.t("data","reports");
x.t("data","using");
x.t("query","microarray");
x.t("pre-configured","searches");
x.t("using","cabio");
x.t("genomic","annotations");
x.t("category","reports");
}
