function FileData_Pairs(x)
{
x.t("available","genomic");
x.t("description","gene");
x.t("want","include");
x.t("gene","lookup");
x.t("gene","symbol");
x.t("creating","reports");
x.t("portlet","creating");
x.t("cabio","portlet");
x.t("cabio","data");
x.t("annotations","following");
x.t("annotations","using");
x.t("annotations","genomic");
x.t("annotations","category");
x.t("report","available");
x.t("report","option");
x.t("reports","cabio");
x.t("option","description");
x.t("enter","gene");
x.t("include","report");
x.t("data","genomic");
x.t("following","report");
x.t("using","cabio");
x.t("lookup","symbol");
x.t("symbol","want");
x.t("symbol","report");
x.t("symbol","enter");
x.t("genomic","annotations");
x.t("category","gene");
}
