CREATE OR REPLACE FORCE VIEW CABIODEV.ARRAY_REPORTER_MAP_V
(REPORTER_ID, ARRAY_DESIGN_ID, DESIGN_ELEMENT_GROUP_ID)
AS 
SELECT a.REPORTER_ID, b.ARRAY_DESIGN_ID, b.DESIGN_ELEMENT_GROUP_ID
  FROM REPORTER a, EXP_MEASUREMENT_ARRAY_VIEW b
 WHERE a.DESIGN_ELEMENT_GROUP_ID = b.DESIGN_ELEMENT_GROUP_ID;


