CREATE OR REPLACE FORCE VIEW CABIODEV.CONCEPT_GENE
(GENE_ID, CONCEPT_ID)
AS 
SELECT GENE_TARGET.gene_id, CONCEPT_TARGET.concept_id
FROM GENE_TARGET, CONCEPT_TARGET
WHERE GENE_TARGET.TARGET_ID = CONCEPT_TARGET.TARGET_ID;


