CREATE OR REPLACE FORCE VIEW CABIODEV.EXP_MEASUREMENT_ARRAY_VIEW
(DESIGN_ELEMENT_GROUP_ID, ARRAY_DESIGN_ID, ARRAY_NAME)
AS 
SELECT DESIGN_ELEMENT_GROUP_ID, A.ARRAY_DESIGN_ID, ARRAY_NAME
FROM DCop.ARRAY_DESIGN@todcop A, DCop.DESIGN_ELEMENT_GROUP@todcop D
WHERE D.ARRAY_DESIGN_ID = A.ARRAY_DESIGN_ID;


