CREATE OR REPLACE FORCE VIEW CABIODEV.EXPRESSION_MEASUREMENT_VIEW
(DESIGN_ELEMENT_GROUP_ID, REPORTER_ID, ACCESSION, REPORTER_NAME)
AS 
SELECT DESIGN_ELEMENT_GROUP_ID, REPORTER_ID, UPPER(DECODE(INSTR(ACCESSION, '.'),
 0, accession, SUBSTR(accession, 0, INSTR(ACCESSION, '.')-1))),
 REPORTER_NAME
FROM DCop.REPORTER@todcop R, DCop.DATABASE_REFERENCE@todcop D
WHERE D.DATABASE_REFERENCE_ID(+) = R.DATABASE_REFERENCE_ID;


