CREATE OR REPLACE FORCE VIEW CABIODEV.GENE_ACCESSION_VIEW
(GENE_ID, ACCESSION_NUMBER)
AS 
SELECT GS.gene_id, S.ACCESSION_NUMBER
	       FROM	 GENE_SEQUENCE GS,
                SEQUENCE S
		  WHERE GS.SEQUENCE_ID = S.SEQUENCE_ID;


