CREATE OR REPLACE FORCE VIEW CABIODEV.GENE_LOCUS_VIEW
(GENE_ID, TAXON_ID, IDENTIFIER)
AS 
SELECT G.gene_id, G.TAXON_ID,  GI.IDENTIFIER
	       FROM GENE_IDENTIFIERS GI,
				GENE G
		  WHERE GI.DATA_SOURCE = 2
			AND GI.GENE_ID = G.GENE_ID;


