CREATE OR REPLACE FORCE VIEW CABIODEV.LIB_GENE
(LIBRARY_ID, GENE_ID)
AS 
SELECT /*+ CHOOSE */ C.LIBRARY_ID, GS.GENE_ID 
FROM CLONE C, SEQUENCE s, GENE_SEQUENCE gs 
WHERE S.CLONE_ID = C.CLONE_ID 
  AND S.SEQUENCE_ID = GS.SEQUENCE_ID;


