CREATE OR REPLACE FORCE VIEW CABIODEV.PROTOCOL_HISTOPATHOLOGY
(PRO_ID, CONTEXT_CODE)
AS 
SELECT PRO_ID, IMT_TO_CONTEXT.context_CODE FROM
PROTOCOL_DISEASES, IMT_TO_CONTEXT
WHERE PROTOCOL_DISEASES.IMT_CODE = IMT_TO_CONTEXT.IMT_CODE;


