CREATE OR REPLACE FORCE VIEW CABIODEV.REPORTER_VIEW
(ID, NAME, MICROARRAY_ID, BIG_ID)
AS 
select ID, NAME, MICROARRAY_ID, BIG_ID from EXPRESSION_REPORTER
UNION
select ID, NAME, MICROARRAY_ID, BIG_ID from SNP_REPORTER
UNION
select ID, NAME, MICROARRAY_ID, BIG_ID from EXON_REPORTER;


