ALTER TABLE CGAP_GENE_ALIAS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CGAP_GENE_ALIAS CASCADE CONSTRAINTS PURGE
/

--
-- CGAP_GENE_ALIAS  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--
CREATE TABLE CGAP_GENE_ALIAS ( GENE_ID NUMBER NOT NULL, ALIAS VARCHAR2(100 BYTE) NOT NULL, CONSTRAINT CGAPK PRIMARY KEY (GENE_ID, ALIAS), CONSTRAINT CGFK FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


