ALTER TABLE CONCEPT_CLOSURE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CONCEPT_CLOSURE CASCADE CONSTRAINTS PURGE
/

--
-- CONCEPT_CLOSURE  (Table) 
--
CREATE TABLE CONCEPT_CLOSURE ( CONCEPT_ID NUMBER NULL, ANCESTOR NUMBER NULL, CONSTRAINT CONCPK PRIMARY KEY (CONCEPT_ID, ANCESTOR) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


