ALTER TABLE CYTOGENIC_LOCATION_CYTOBAND
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CYTOGENIC_LOCATION_CYTOBAND CASCADE CONSTRAINTS PURGE
/

--
-- CYTOGENIC_LOCATION_CYTOBAND  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--   NUCLEIC_ACID_SEQUENCE (Table)
--   CHROMOSOME (Table)
--   SNP_TV (Table)
--
CREATE TABLE CYTOGENIC_LOCATION_CYTOBAND ( CYTOGENIC_LOCATION_ID NUMBER NOT NULL, GENE_ID NUMBER NULL, NUCLEIC_ACID_SEQUENCE_ID NUMBER NULL, SNP_ID NUMBER NULL, CHROMOSOME_ID NUMBER NOT NULL, START_CYTOBAND_LOC_ID NUMBER NOT NULL, END_CYTOBAND_LOC_ID NUMBER NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT SYTO_LOC_SYTO_PK PRIMARY KEY (CYTOGENIC_LOCATION_ID), CONSTRAINT CCCBIGID UNIQUE (BIG_ID), UNIQUE (GENE_ID, NUCLEIC_ACID_SEQUENCE_ID, SNP_ID, CHROMOSOME_ID, START_CYTOBAND_LOC_ID, END_CYTOBAND_LOC_ID), CONSTRAINT CCBANDGENEFK FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID), CONSTRAINT CCBANDNASFK FOREIGN KEY (NUCLEIC_ACID_SEQUENCE_ID) REFERENCES NUCLEIC_ACID_SEQUENCE (ID), CONSTRAINT CYTOCBANDFK FOREIGN KEY (CHROMOSOME_ID) REFERENCES CHROMOSOME (CHROMOSOME_ID), FOREIGN KEY (SNP_ID) REFERENCES SNP_TV (ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


