ALTER TABLE GENERIC_REPORTER
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENERIC_REPORTER CASCADE CONSTRAINTS PURGE
/

--
-- GENERIC_REPORTER  (Table) 
--
--  Dependencies: 
--   GENE_TV (Table)
--
CREATE TABLE GENERIC_REPORTER ( ID NUMBER(8,2) NULL, NAME VARCHAR2(50 BYTE) NOT NULL, TYPE VARCHAR2(50 BYTE) NOT NULL, GENE_ID NUMBER(8,2) NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CLUSTER_ID VARCHAR2(50 BYTE) NULL, CONSTRAINT GENERIC_REPORTER_PK PRIMARY KEY (ID), CONSTRAINT GREP UNIQUE (BIG_ID), UNIQUE (NAME, TYPE, GENE_ID, CLUSTER_ID), CONSTRAINT GRFK FOREIGN KEY (GENE_ID) REFERENCES GENE_TV (GENE_ID) ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


