DROP TABLE HANDLES CASCADE CONSTRAINTS PURGE
/

--
-- HANDLES  (Table) 
--
CREATE TABLE HANDLES ( PREFIX RAW(255) NULL, HANDLE RAW(255) NULL, IDX NUMBER NULL, TYPE RAW(255) NULL, DATA RAW(345) NULL, TTL_TYPE NUMBER NULL, TTL NUMBER NULL, TIMESTAMP NUMBER NULL, REFS VARCHAR2(254 BYTE) NULL, ADMIN_READ VARCHAR2(5 BYTE) NULL, ADMIN_WRITE VARCHAR2(5 BYTE) NULL, PUB_READ VARCHAR2(5 BYTE) NULL, PUB_WRITE VARCHAR2(5 BYTE) NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


