ALTER TABLE KEYWORD
 DROP PRIMARY KEY CASCADE
/
DROP TABLE KEYWORD CASCADE CONSTRAINTS PURGE
/

--
-- KEYWORD  (Table) 
--
CREATE TABLE KEYWORD ( ID NUMBER NOT NULL, SCORE NUMBER NOT NULL, VALUE VARCHAR2(512 BYTE) NOT NULL, CONSTRAINT PK_KEYWORD PRIMARY KEY (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


