DROP TABLE OBJECT_TO_OBJECT_MAP CASCADE CONSTRAINTS PURGE
/

--
-- OBJECT_TO_OBJECT_MAP  (Table) 
--
CREATE TABLE OBJECT_TO_OBJECT_MAP ( FROM_OBJECT_NAME VARCHAR2(50 BYTE) NOT NULL, TO_OBJECT_NAME VARCHAR2(50 BYTE) NOT NULL, ID NUMBER NULL, TO_OBJECT_CRITERIA VARCHAR2(50 BYTE) NOT NULL, CORRELATION_TABLE_NAME VARCHAR2(50 BYTE) NULL, CORR_TABLE_OBJECT_ID VARCHAR2(50 BYTE) NULL, CORR_TABLE_ASSOCIATION_ID VARCHAR2(50 BYTE) NULL, SEARCH_TABLE_ID VARCHAR2(50 BYTE) NOT NULL, FROM_OBJECT_ID VARCHAR2(50 BYTE) NOT NULL, RELATION_TYPE VARCHAR2(50 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


