DROP TABLE PROTOCOLS CASCADE CONSTRAINTS PURGE
/

--
-- PROTOCOLS  (Table) 
--
CREATE TABLE PROTOCOLS ( ID NUMBER(10) NOT NULL, DOCUMENT_NUMBER VARCHAR2(35 BYTE) NULL, TITLE VARCHAR2(2000 BYTE) NULL, PHASE VARCHAR2(10 BYTE) NULL, PARTICIPATION_TYPE VARCHAR2(35 BYTE) NULL, TREATMENT_FLAG VARCHAR2(5 BYTE) NULL, NIH_ADMIN_CODE VARCHAR2(10 BYTE) NULL, CURRENT_STATUS VARCHAR2(40 BYTE) NULL, CURRENT_STATUS_DATE DATE NULL, LEAD_ORGANIZATION_CTEP_ID VARCHAR2(6 BYTE) NULL, LEAD_ORGANIZATION_NAME VARCHAR2(100 BYTE) NULL, PI_NAME VARCHAR2(85 BYTE) NULL, REVIEWER_NAME VARCHAR2(85 BYTE) NULL, PDQ_PROTOCOL_CODE VARCHAR2(50 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


