DROP TABLE QUEST_SL_TEMP_EXPLAIN1 CASCADE CONSTRAINTS PURGE
/

--
-- QUEST_SL_TEMP_EXPLAIN1  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE QUEST_SL_TEMP_EXPLAIN1 ( STATEMENT_ID VARCHAR2(30 BYTE) NULL, TIMESTAMP DATE NULL, REMARKS VARCHAR2(80 BYTE) NULL, OPERATION VARCHAR2(30 BYTE) NULL, OPTIONS VARCHAR2(255 BYTE) NULL, OBJECT_NODE VARCHAR2(128 BYTE) NULL, OBJECT_OWNER VARCHAR2(30 BYTE) NULL, OBJECT_NAME VARCHAR2(30 BYTE) NULL, OBJECT_INSTANCE NUMBER NULL, OBJECT_TYPE VARCHAR2(30 BYTE) NULL, OPTIMIZER VARCHAR2(255 BYTE) NULL, SEARCH_COLUMNS NUMBER NULL, ID NUMBER NULL, PARENT_ID NUMBER NULL, POSITION NUMBER NULL, COST NUMBER NULL, CARDINALITY NUMBER NULL, BYTES NUMBER NULL, OTHER_TAG VARCHAR2(255 BYTE) NULL, PARTITION_START VARCHAR2(255 BYTE) NULL, PARTITION_STOP VARCHAR2(255 BYTE) NULL, PARTITION_ID NUMBER NULL, OTHER LONG NULL, DISTRIBUTION VARCHAR2(30 BYTE) NULL, CPU_COST NUMBER(38) NULL, IO_COST NUMBER(38) NULL, TEMP_SPACE NUMBER(38) NULL, ACCESS_PREDICATES VARCHAR2(4000 BYTE) NULL, FILTER_PREDICATES VARCHAR2(4000 BYTE) NULL ) ON COMMIT PRESERVE ROWS NOCACHE
/


