ALTER TABLE ZSTG_CLONE_DIM
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_CLONE_DIM CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_CLONE_DIM  (Table) 
--
CREATE TABLE ZSTG_CLONE_DIM ( CLONE_ID NUMBER NOT NULL, CLONE_NAME VARCHAR2(200 BYTE) NOT NULL, CLONE_DESC VARCHAR2(4000 BYTE) NOT NULL, UTR NUMBER(1) NULL, UNIGENE_LIBRARY VARCHAR2(50 BYTE) NULL, UNIGENE_ID VARCHAR2(50 BYTE) NULL, CLONE_TYPE VARCHAR2(20 BYTE) NULL, CYTOBAND VARCHAR2(50 BYTE) NULL, CHROMOSOME VARCHAR2(20 BYTE) NULL, START_CYTOBAND VARCHAR2(50 BYTE) NULL, END_CYTOBAND VARCHAR2(50 BYTE) NULL, PRIMARY KEY (CLONE_ID) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


