DROP TABLE ZSTG_PID_PATHWAY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PID_PATHWAY  (Table) 
--
CREATE TABLE ZSTG_PID_PATHWAY ( PATHWAY_ID NUMBER NOT NULL, SOURCE VARCHAR2(2500 BYTE) NOT NULL, SHORTNAME VARCHAR2(2500 BYTE) NOT NULL, LONGNAME VARCHAR2(2500 BYTE) NOT NULL, IS_SUBNET VARCHAR2(2500 BYTE) NULL, CURATOR_STRING VARCHAR2(2500 BYTE) NULL, REVIEWER_STRING VARCHAR2(2500 BYTE) NULL, DIAGRAM CLOB NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS LOB (DIAGRAM) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 0 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


