DROP TABLE ZSTG_STARTSNPARRAYREPCYTOIDS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_STARTSNPARRAYREPCYTOIDS  (Table) 
--
CREATE TABLE ZSTG_STARTSNPARRAYREPCYTOIDS ( ID NUMBER NOT NULL, CYTO_START VARCHAR2(255 BYTE) NULL, CYTOBANDID NUMBER NOT NULL, CHROMOSOME_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


