DROP TABLE ZSTG_INTERACTIONREFERENCE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_INTERACTIONREFERENCE  (Table) 
--
CREATE TABLE ZSTG_INTERACTIONREFERENCE ( INTERACTION_ID VARCHAR2(2500 BYTE) NOT NULL, SOURCE_ID VARCHAR2(2500 BYTE) NOT NULL, REFERENCE VARCHAR2(2500 BYTE) NOT NULL, PMID VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


