ALTER TABLE ZSTG_EXPRESSION_REPORTER
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_EXPRESSION_REPORTER CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_EXPRESSION_REPORTER  (Table) 
--
CREATE TABLE ZSTG_EXPRESSION_REPORTER ( ID NUMBER NOT NULL, NAME VARCHAR2(4000 BYTE) NOT NULL, MICROARRAY_ID NUMBER NOT NULL, SEQUENCE_TYPE VARCHAR2(20 BYTE) NULL, SEQUENCE_SOURCE VARCHAR2(50 BYTE) NULL, TRANSCRIPT_ID VARCHAR2(100 BYTE) NULL, TARGET_DESCRIPTION VARCHAR2(2000 BYTE) NULL, GENE_ID NUMBER NULL, NAS_ID NUMBER NULL, CHROMOSOME_ID NUMBER NULL, CHR_START NUMBER NULL, CHR_STOP NUMBER NULL, CYTO_START VARCHAR2(250 BYTE) NULL, CYTO_STOP VARCHAR2(250 BYTE) NULL, ASSEMBLY VARCHAR2(250 BYTE) DEFAULT 'reference' NULL, CONSTRAINT PK_ZSTG_EXPRESSION_REPORTER PRIMARY KEY (ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


