DROP TABLE ZSTG_SNP_AFFY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_SNP_AFFY  (Table) 
--
CREATE TABLE ZSTG_SNP_AFFY ( ARRAY_NAME VARCHAR2(50 BYTE) NOT NULL, PROBE_SET_ID VARCHAR2(20 BYTE) NOT NULL, AFFY_SNP_ID VARCHAR2(20 BYTE) NOT NULL, DBSNP_RS_ID VARCHAR2(20 BYTE) NOT NULL, CHROMOSOME VARCHAR2(20 BYTE) NOT NULL, GENOME_VERSION VARCHAR2(200 BYTE) NULL, DB_SNP_VERSION VARCHAR2(200 BYTE) NULL, PHYSICAL_POSITION VARCHAR2(20 BYTE) NOT NULL, STRAND VARCHAR2(10 BYTE) NOT NULL, CHRX_PSEUDO_AUTOSOMAL_REGION VARCHAR2(50 BYTE) NOT NULL, CYTOBAND VARCHAR2(20 BYTE) NOT NULL, FLANK VARCHAR2(500 BYTE) NOT NULL, ALLELE_A VARCHAR2(10 BYTE) NOT NULL, ALLELE_B VARCHAR2(10 BYTE) NOT NULL, ASSOCIATED_GENE LONG NOT NULL, GENETIC_MAP VARCHAR2(1000 BYTE) NOT NULL, MICROSATELLITE VARCHAR2(200 BYTE) NOT NULL, FRAGMENT_LENGTH_START_STOP VARCHAR2(100 BYTE) NOT NULL, ALLELE_FREQ VARCHAR2(1000 BYTE) NOT NULL, HET_FREQ VARCHAR2(1000 BYTE) NOT NULL, NUM_CHRM VARCHAR2(1000 BYTE) NOT NULL, IN_HAPMAP VARCHAR2(10 BYTE) NOT NULL, STRAND_VS_DBSNP VARCHAR2(50 BYTE) NOT NULL, COPY_NUM_VARIATION VARCHAR2(4000 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


