CREATE OR REPLACE procedure CYTOBAND_02_LD as

  V_MAXROW NUMBER :=0;

 CURSOR PHYCUR IS
  (SELECT ROWNUM, CYTOBAND FROM (
	SELECT CHROMOSOME || CYTOBAND  CYTOBAND FROM SNP_PROBESET_ANNO
	MINUS
	SELECT NAME CYTOBAND FROM CYTOBAND));

  aID number:=0;

BEGIN

   SELECT MAX(ID) INTO V_MAXROW FROM CYTOBAND;

   FOR aRec in PHYCUR LOOP
      aID := aID + 1;

      INSERT INTO CYTOBAND (ID,
                          NAME)
      VALUES
     (aRec.ROWNUM + V_MAXROW,
      aRec.CYTOBAND);

      IF MOD(aID, 500) = 0 THEN
         COMMIT;
      END IF;

   END LOOP;

COMMIT;

END; 
/

