
CREATE INDEX CABIODEV.RANGE_QUERY_IDX ON CABIODEV.LOCATION_CH_43
(CHROMOSOME_ID, LOWER("ASSEMBLY"), CHROMOSOMAL_START_POSITION, CHROMOSOMAL_END_POSITION)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE BITMAP INDEX CABIODEV.LCHNP_ASSEMBLY ON CABIODEV.LOCATION_CH_43
(ASSEMBLY)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE BITMAP INDEX CABIODEV.LCHNP_ASSEMBLY_LWR ON CABIODEV.LOCATION_CH_43
(LOWER("ASSEMBLY"))
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE BITMAP INDEX CABIODEV.LCHNP_CHROMOSOME ON CABIODEV.LOCATION_CH_43
(CHROMOSOME_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX CABIODEV.LCHNP_DISCRIMINATOR ON CABIODEV.LOCATION_CH_43
(DISCRIMINATOR)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE BITMAP INDEX CABIODEV.LCHNP_DISCRIMINATOR_LWR ON CABIODEV.LOCATION_CH_43
(LOWER("DISCRIMINATOR"))
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE BITMAP INDEX CABIODEV.LCHNP_FEATURE_TYPE ON CABIODEV.LOCATION_CH_43
(FEATURE_TYPE)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE BITMAP INDEX CABIODEV.LCHNP_FEATURE_TYPE_LWR ON CABIODEV.LOCATION_CH_43
(LOWER("FEATURE_TYPE"))
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;













