/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

--
-- CYTOGENIC_LOC_CYTOID  (Trigger) 
--
--  Dependencies: 
--   CYTOGENIC_LOCATION_CYTOBAND (Table)
--
CREATE OR REPLACE TRIGGER CYTOGENIC_LOC_CYTOID
BEFORE INSERT
ON CYTOGENIC_LOCATION_CYTOBAND
FOR EACH ROW
BEGIN
  SELECT CYTO_LOC_CYTOID.NEXTVAL
  INTO :NEW.CYTOGENIC_LOCATION_ID
  FROM DUAL;
END;
/
SHOW ERRORS;

ALTER TRIGGER CYTOGENIC_LOC_CYTOID DISABLE
/



