
drop index AR_ALIGNENTS_PROBE_SET_;
drop index AR_ALIGNENTS_START_POSI;
drop index AR_ALIGNENTS_END_POSITI;
drop index AR_ALIGNENTS_DIRECTION;
drop index AR_ALIGNENTS_TRIM_CHR;
drop index AR_ALIGNENTS_ASSEMBLY;
drop index AR_ALIGNENTS_GENECHIP_A;
drop index AR_ALIGNENTS_CHROMOSOME;

--EXIT;
