
create index AR_GO_MO_TMP_GENECHIP_A_lwr on AR_GO_MOLECULAR_FUNCTION_TMP(lower(GENECHIP_ARRAY)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_MO_TMP_EVIDENCE_lwr on AR_GO_MOLECULAR_FUNCTION_TMP(lower(EVIDENCE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_MO_TMP_DESCRIPTIO_lwr on AR_GO_MOLECULAR_FUNCTION_TMP(lower(DESCRIPTION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_MO_TMP_PROBE_SET__lwr on AR_GO_MOLECULAR_FUNCTION_TMP(lower(PROBE_SET_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
