
drop index NEW_PROTTEIN_NAME;
drop index NEW_PROTTEIN_PRIMARY_AC_LWR;
drop index NEW_PROTTEIN_SECONDARY__LWR;
drop index NEW_PROTTEIN_UNIPROTCOD_LWR;
drop index NEW_PROTTEIN_KEYWORD_LWR;
drop index NEW_PROTTEIN_NAME_LWR;
drop index NEW_PROTTEIN_COPYRIGHTS_LWR;
drop index NEW_PROEIN_BIG_ID_LWR;
drop index NEW_PROEIN_BIG_ID;
drop index SYS_C0021126_IDX;
drop index NEW_PROTTEIN_PROTEIN_ID;
drop index NEW_PROTTEIN_PRIMARY_AC;
drop index NEW_PROTTEIN_SECONDARY_;
drop index NEW_PROTTEIN_UNIPROTCOD;
drop index NEW_PROTTEIN_KEYWORD;
drop index NEW_PROTTEIN_COPYRIGHTS;

--EXIT;
