
drop index PID_INTION_BIG_ID_LWR;
drop index PID_INTION_BIG_ID;
drop index SYS_C0021154_IDX;
drop index PID_INTETION_SOURCE_LWR;
drop index PID_INTETION_MACRO_NAME_LWR;
drop index PID_INTETION_DISCRIMINA_LWR;
drop index PID_INTETION_ID;
drop index PID_INTETION_SOURCE;
drop index PID_INTETION_MACRO_NAME;
drop index PID_INTETION_DISCRIMINA;
drop index PID_INTETION_REF_PATHWA;
drop index PID_INTETION_PID_INTERA;

--EXIT;
