
drop index PID_PARANT_BIG_ID_LWR;
drop index PID_PARANT_BIG_ID;
drop index PID_PARTPANT_LOCATION_LWR;
drop index PID_PARTPANT_PTM_LWR;
drop index PID_PARTPANT_ACTIVITY_S_LWR;
drop index PID_PARTPANT_CONDITION__LWR;
drop index PID_PARTPANT_DISCRIMINA_LWR;
drop index PID_PARTPANT_ID;
drop index PID_PARTPANT_LOCATION;
drop index PID_PARTPANT_PTM;
drop index PID_PARTPANT_ACTIVITY_S;
drop index PID_PARTPANT_CONDITION_;
drop index PID_PARTPANT_DISCRIMINA;
drop index PID_PARTPANT_INTERACTIO;
drop index PID_PARTPANT_COMPLEX_EN;
drop index PID_PARTPANT_PHYSICAL_E;
drop index PID_PARTPANT_PID_INTERA;
drop index PID_PARTPANT_PID_PHYSIC;
drop index PID_PARTPANT_PID_COMPLE;
drop index PID_PARTPANT_PID_FAMILY;
drop index PID_PARTPANT_PID_MEMBER;

--EXIT;
