
create index ZSTG_MOLLIES_MEMBER_MOL_lwr on ZSTG_MOLECULEFAMILIES(lower(MEMBER_MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLLIES_FAMILY_MOL_lwr on ZSTG_MOLECULEFAMILIES(lower(FAMILY_MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLLIES_MTYPE_lwr on ZSTG_MOLECULEFAMILIES(lower(MTYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLLIES_MOLECULE_I_lwr on ZSTG_MOLECULEFAMILIES(lower(MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLLIES_SOURCE_ID_lwr on ZSTG_MOLECULEFAMILIES(lower(SOURCE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
