#!/usr/bin/sh
rm caBioDataRefresh.log
perl getVersionInformation.pl ftp://hgdownload.cse.ucsc.edu/goldenPath/hg17/database/chr1_est.txt.gz "EST Annotations for Humans from UCSC" 
perl getVersionInformation.pl ftp://hgdownload.cse.ucsc.edu/goldenPath/mm7/database/chr1_est.txt.gz "EST Annotations for Mouse from UCSC" 
perl getVersionInformation.pl ftp://hgdownload.cse.ucsc.edu/goldenPath/hg17/database/all_mrna.txt.gz "MRNA Annotations for Human from UCSC" 
perl getVersionInformation.pl ftp://hgdownload.cse.ucsc.edu/goldenPath/mm17/database/all_mrna.txt.gz "MRNA Annotations for Mouse from UCSC" 
perl getVersionInformation.pl ftp://ftpctep.nci.nih.gov/cmapexp.dmp "CTEP Data" 
perl getVersionInformation.pl ftp://image.llnl.gov/image/outgoing/arrayed_plate_data/cumulative/cumu* "IMAGE Clone Data" 
perl getVersionInformation.pl ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2unigene "Gene to Unigene Ids Mapping" 
perl getVersionInformation.pl ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/omim2gene "Omim to Gene Ids Mapping" 
perl getVersionInformation.pl ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2accession.gz "Gene Ids to GI Accession Mapping" 
perl getVersionInformation.pl ftp://hgdownload.cse.ucsc.edu/goldenPath/hg17/database/cytoBand.txt.gz "Human Cytoband Data from UCSC" 
perl getVersionInformation.pl ftp://hgdownload.cse.ucsc.edu/goldenPath/mm7/database/cytoBand.txt.gz "Mouse Cytoband Data from UCSC" 
perl getVersionInformation.pl ftp://ftp.uniprot.org/pub/databases/uniprot_datafiles_by_format/flatfile/uniprot_sprot.dat.gz "Swissprot Annotations from Uniprot"
perl getVersionInformation.pl ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/ASN1_flat/ds_flat_ch1.flat.gz "SNP Annotations from NCBI"
perl getVersionInformation.pl  ftp://hapmap.org/tscsnp-data/snps/tabsep/snps_chrom1_tabsep.txt.gz "SNP Annotations from TSC"
