CREATE OR REPLACE FORCE VIEW CABIODEV.CLONE_SNP
(CLONE_ID, LOCATION_ID)
AS 
SELECT seq.CLONE_id, loc.location_id FROM
SEQUENCE seq, LOCATION loc, ACE
WHERE seq.accession_number = ACE.accession
AND ACE.ACE_ID = loc.ACE_ID
AND clone_id IS NOT NULL;


