CREATE OR REPLACE FORCE VIEW CABIODEV.IMT_TO_HISTO_TISSUE_VIEW
(IMT_CODE, HISTOLOGY_CODE, TISSUE_CODE)
AS 
SELECT IMT_TO_HISTOLOGY.IMT_CODE, HISTOLOGY_CODE, NVL(TISSUE_CODE, 0) TISSUE_CODE FROM IMT_TO_HISTOLOGY, IMT_TO_TISSUE
WHERE  IMT_TO_HISTOLOGY.IMT_CODE = IMT_TO_TISSUE.IMT_CODE(+);


