ALTER TABLE AR_GENE_TITLE_TMP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE AR_GENE_TITLE_TMP CASCADE CONSTRAINTS PURGE
/

--
-- AR_GENE_TITLE_TMP  (Table) 
--
CREATE TABLE AR_GENE_TITLE_TMP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, GENE_TITLE VARCHAR2(1000 BYTE) NOT NULL, GENECHIP_ARRAY VARCHAR2(50 BYTE) NOT NULL, PRIMARY KEY (PROBE_SET_ID, GENE_TITLE, GENECHIP_ARRAY) DISABLE ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


