DROP TABLE CLONE_DIFF CASCADE CONSTRAINTS PURGE
/

--
-- CLONE_DIFF  (Table) 
--
CREATE TABLE CLONE_DIFF ( CLONE_NAME VARCHAR2(200 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


