ALTER TABLE CONCEPT_TYPE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE CONCEPT_TYPE CASCADE CONSTRAINTS PURGE
/

--
-- CONCEPT_TYPE  (Table) 
--
CREATE TABLE CONCEPT_TYPE ( CONCEPT_TYPE_ID NUMBER NOT NULL, CONCEPT_TYPE_NAME VARCHAR2(250 BYTE) NOT NULL, CONSTRAINT CONCEPT_TYPE PRIMARY KEY (CONCEPT_TYPE_ID, CONCEPT_TYPE_NAME) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


