ALTER TABLE DATA_SOURCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE DATA_SOURCE CASCADE CONSTRAINTS PURGE
/

--
-- DATA_SOURCE  (Table) 
--
CREATE TABLE DATA_SOURCE ( DATA_SOURCE_ID NUMBER NULL, DATA_SOURCE_NAME VARCHAR2(255 BYTE) NOT NULL, CONSTRAINT DSPK PRIMARY KEY (DATA_SOURCE_ID), UNIQUE (DATA_SOURCE_NAME) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


