ALTER TABLE EVIDENCE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EVIDENCE CASCADE CONSTRAINTS PURGE
/

--
-- EVIDENCE  (Table) 
--
CREATE TABLE EVIDENCE ( ID NUMBER NOT NULL, PUBMED_ID NUMBER NOT NULL, NEGATION_STATUS NVARCHAR2(50) NULL, CELLLINE_STATUS NVARCHAR2(50) NULL, COMMENTS VARCHAR2(4000 BYTE) NULL, SENTENCE_STATUS NVARCHAR2(50) NULL, SENTENCE CLOB NOT NULL, BIG_ID VARCHAR2(1000 BYTE) NULL, SENTENCE_SUBSTR VARCHAR2(4000 BYTE) NULL, CONSTRAINT EVIDENCE_PK_1 PRIMARY KEY (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS LOB (SENTENCE) STORE AS ( TABLESPACE CABIO_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


