ALTER TABLE GENE_ALIAS_OBJECT_TV
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENE_ALIAS_OBJECT_TV CASCADE CONSTRAINTS PURGE
/

--
-- GENE_ALIAS_OBJECT_TV  (Table) 
--
CREATE TABLE GENE_ALIAS_OBJECT_TV ( GENE_ALIAS_ID NUMBER NOT NULL, ALIAS_TYPE VARCHAR2(50 BYTE) NOT NULL, NAME VARCHAR2(2500 BYTE) NOT NULL, GENE_ID NUMBER NULL, BIG_ID VARCHAR2(200 BYTE) NULL, CONSTRAINT GAOPK PRIMARY KEY (GENE_ALIAS_ID), CONSTRAINT GAOBIGID UNIQUE (BIG_ID), UNIQUE (GENE_ALIAS_ID, ALIAS_TYPE, NAME, GENE_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


