ALTER TABLE GENERIC_ARRAY_SNP_REPORTER
 DROP PRIMARY KEY CASCADE
/
DROP TABLE GENERIC_ARRAY_SNP_REPORTER CASCADE CONSTRAINTS PURGE
/

--
-- GENERIC_ARRAY_SNP_REPORTER  (Table) 
--
--  Dependencies: 
--   GENERIC_ARRAY (Table)
--   SNP_REPORTER (Table)
--
CREATE TABLE GENERIC_ARRAY_SNP_REPORTER ( GENERIC_ARRAY_ID NUMBER(8,2) NULL, SNP_REPORTER_ID NUMBER(8,2) NULL, CONSTRAINT GASRPK PRIMARY KEY (GENERIC_ARRAY_ID, SNP_REPORTER_ID), CONSTRAINT GASRFK1 FOREIGN KEY (GENERIC_ARRAY_ID) REFERENCES GENERIC_ARRAY (ID), CONSTRAINT GASRFK2 FOREIGN KEY (SNP_REPORTER_ID) REFERENCES SNP_REPORTER (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


