DROP TABLE GO_CLOSURE CASCADE CONSTRAINTS PURGE
/

--
-- GO_CLOSURE  (Table) 
--
CREATE TABLE GO_CLOSURE ( GO_CODE NUMBER NOT NULL, ANCESTOR NUMBER NOT NULL ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


