ALTER TABLE LIBRARY_HISTOPATHOLOGY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE LIBRARY_HISTOPATHOLOGY CASCADE CONSTRAINTS PURGE
/

--
-- LIBRARY_HISTOPATHOLOGY  (Table) 
--
--  Dependencies: 
--   HISTOPATHOLOGY_TST (Table)
--   LIBRARY (Table)
--
CREATE TABLE LIBRARY_HISTOPATHOLOGY ( LIBRARY_ID NUMBER NOT NULL, CONTEXT_CODE NUMBER NOT NULL, CONSTRAINT LIB_HIST_PK PRIMARY KEY (LIBRARY_ID, CONTEXT_CODE) DISABLE, CONSTRAINT LHFK FOREIGN KEY (CONTEXT_CODE) REFERENCES HISTOPATHOLOGY_TST (HISTOPATHOLOGY_ID), CONSTRAINT LHFK2 FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (LIBRARY_ID) DISABLE ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


