ALTER TABLE LIBRARY_KEYWORD
 DROP PRIMARY KEY CASCADE
/
DROP TABLE LIBRARY_KEYWORD CASCADE CONSTRAINTS PURGE
/

--
-- LIBRARY_KEYWORD  (Table) 
--
CREATE TABLE LIBRARY_KEYWORD ( KEYWORD VARCHAR2(255 BYTE) NOT NULL, LIBRARY_ID NUMBER NOT NULL, CONSTRAINT LIB_KEY_PK PRIMARY KEY (LIBRARY_ID, KEYWORD) DISABLE ) TABLESPACE CABIO_FUT LOGGING NOCOMPRESS NOCACHE PARALLEL ( DEGREE 4 INSTANCES 1 ) MONITORING
/


