ALTER TABLE PID_PHYSICAL_ENTITY_NAME
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_PHYSICAL_ENTITY_NAME CASCADE CONSTRAINTS PURGE
/

--
-- PID_PHYSICAL_ENTITY_NAME  (Table) 
--
--  Dependencies: 
--   PID_PHYSICAL_ENTITY (Table)
--   PID_ENTITY_NAME (Table)
--
CREATE TABLE PID_PHYSICAL_ENTITY_NAME ( PHYSICAL_ENTITY_ID NUMBER NOT NULL, ENTITY_NAME_ID NUMBER NOT NULL, PRIMARY KEY (PHYSICAL_ENTITY_ID, ENTITY_NAME_ID), FOREIGN KEY (PHYSICAL_ENTITY_ID) REFERENCES PID_PHYSICAL_ENTITY (ID), FOREIGN KEY (ENTITY_NAME_ID) REFERENCES PID_ENTITY_NAME (ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


