ALTER TABLE PID_INTERACTION
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_INTERACTION CASCADE CONSTRAINTS PURGE
/

--
-- PID_INTERACTION  (Table) 
--
CREATE TABLE PID_INTERACTION ( ID NUMBER NOT NULL, SOURCE VARCHAR2(2500 BYTE) NOT NULL, MACRO_NAME VARCHAR2(2500 BYTE) NULL, DISCRIMINATOR VARCHAR2(2500 BYTE) NOT NULL, REF_PATHWAY_ID NUMBER NULL, PID_INTERACTION_ID NUMBER NOT NULL, BIG_ID VARCHAR2(2500 BYTE) NULL, PRIMARY KEY (ID), UNIQUE (SOURCE, MACRO_NAME, REF_PATHWAY_ID, PID_INTERACTION_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


