ALTER TABLE PID_FAMILY_PARTICIPANT
 DROP PRIMARY KEY CASCADE
/
DROP TABLE PID_FAMILY_PARTICIPANT CASCADE CONSTRAINTS PURGE
/

--
-- PID_FAMILY_PARTICIPANT  (Table) 
--
CREATE TABLE PID_FAMILY_PARTICIPANT ( PHYSICAL_ENTITY_ID NUMBER NOT NULL, PARTICIPANT_ID NUMBER NOT NULL, PRIMARY KEY (PARTICIPANT_ID, PHYSICAL_ENTITY_ID) ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


