ALTER TABLE SEQUENCE_TYPE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SEQUENCE_TYPE CASCADE CONSTRAINTS PURGE
/

--
-- SEQUENCE_TYPE  (Table) 
--
CREATE TABLE SEQUENCE_TYPE ( SEQUENCE_TYPE_ID NUMBER NOT NULL, DESCRIPTION VARCHAR2(20 BYTE) NOT NULL, PRIMARY KEY (SEQUENCE_TYPE_ID, DESCRIPTION) ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


