DROP TABLE ZSTG_PATHWAYCURATORS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_PATHWAYCURATORS  (Table) 
--
CREATE TABLE ZSTG_PATHWAYCURATORS ( PATHWAY_ID VARCHAR2(2500 BYTE) NOT NULL, SOURCE_ID VARCHAR2(2500 BYTE) NOT NULL, CURATOR_NAME VARCHAR2(2500 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


