DROP TABLE ZSTG_AGENT CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_AGENT  (Table) 
--
CREATE TABLE ZSTG_AGENT ( AGENT_ID NUMBER NOT NULL, AGENT_TYPE VARCHAR2(100 BYTE) NULL, AGENT_NAME VARCHAR2(2500 BYTE) NULL, AGENT_SOURCE VARCHAR2(400 BYTE) NULL, AGENT_COMMENT VARCHAR2(400 BYTE) NULL, CMAP_AGENT NUMBER NULL, NSC_NUMBER NUMBER NULL, EVS_ID VARCHAR2(50 BYTE) NULL, BIG_ID VARCHAR2(200 BYTE) NULL ) TABLESPACE CABIO_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


