DROP TABLE ZSTG_GENETIC_MAP CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENETIC_MAP  (Table) 
--
CREATE TABLE ZSTG_GENETIC_MAP ( PROBE_SET_ID VARCHAR2(100 BYTE) NOT NULL, DISTANCE NUMBER NOT NULL, FIRST_MARKER_ID VARCHAR2(20 BYTE) NULL, FIRST_MARKER_NAME VARCHAR2(50 BYTE) NULL, SECOND_MARKER_ID VARCHAR2(20 BYTE) NULL, SECOND_MARKER_NAME VARCHAR2(50 BYTE) NULL, FIRST_SNP_TSC_ID VARCHAR2(20 BYTE) NULL, SECOND_SNP_TSC_ID VARCHAR2(50 BYTE) NULL, TYPE VARCHAR2(100 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


