DROP TABLE ZSTG_IMAGE_CLONE CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_IMAGE_CLONE  (Table) 
--
CREATE TABLE ZSTG_IMAGE_CLONE ( ID NUMBER NULL, IMAGE_CLONEID NUMBER NULL, IMAGE_LIBRARYID NUMBER NULL, SPECIES VARCHAR2(100 BYTE) NULL, GENBANK_ACCESSION_NUMBER VARCHAR2(20 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


