DROP TABLE ZSTG_EXON_AFFY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_EXON_AFFY  (Table) 
--
CREATE TABLE ZSTG_EXON_AFFY ( PROBE_SET_ID VARCHAR2(8 BYTE) NULL, SEQNAME VARCHAR2(20 BYTE) NULL, STRAND VARCHAR2(1 BYTE) NULL, START_LOCATION VARCHAR2(10 BYTE) NULL, STOP_LOCATION VARCHAR2(10 BYTE) NULL, PROBE_COUNT VARCHAR2(10 BYTE) NULL, TRANSCRIPT_CLUSTER_ID VARCHAR2(10 BYTE) NULL, EXON_ID VARCHAR2(10 BYTE) NULL, PSR_ID VARCHAR2(10 BYTE) NULL, GENE_ASSIGNMENT CLOB NULL, MRNA_ASSIGNMENT CLOB NULL, CROSSHYB_TYPE VARCHAR2(10 BYTE) NULL, NUM_INDEPENDENT_PROBES VARCHAR2(10 BYTE) NULL, NUM_CROSS_HYB_PROBES VARCHAR2(10 BYTE) NULL, NUM_NONOVERLAP_PROBES VARCHAR2(10 BYTE) NULL, BOUNDED VARCHAR2(10 BYTE) NULL, NO_BOUNDED_EVIDENCE VARCHAR2(10 BYTE) NULL, HAS_CDS VARCHAR2(10 BYTE) NULL, FL VARCHAR2(10 BYTE) NULL, MRNA VARCHAR2(10 BYTE) NULL, EST VARCHAR2(10 BYTE) NULL, VEGA_GENE VARCHAR2(10 BYTE) NULL, VEGA_PSEUDO_GENE VARCHAR2(10 BYTE) NULL, ENS_GENE VARCHAR2(10 BYTE) NULL, SGP_GENE VARCHAR2(10 BYTE) NULL, EXONIPHY VARCHAR2(10 BYTE) NULL, TWINSCAN VARCHAR2(10 BYTE) NULL, GENEID VARCHAR2(10 BYTE) NULL, GENSCAN VARCHAR2(10 BYTE) NULL, GENSCAN_SUBOPT VARCHAR2(10 BYTE) NULL, MOUSE_FL VARCHAR2(10 BYTE) NULL, MOUSE_MRNA VARCHAR2(10 BYTE) NULL, RAT_FL VARCHAR2(10 BYTE) NULL, RAT_MRNA VARCHAR2(10 BYTE) NULL, MICRO_RNA_REGISTRY VARCHAR2(10 BYTE) NULL, RNA_GENE VARCHAR2(10 BYTE) NULL, MITOMAP VARCHAR2(10 BYTE) NULL, PROBESET_TYPE VARCHAR2(20 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS LOB (GENE_ASSIGNMENT) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) LOB (MRNA_ASSIGNMENT) STORE AS ( TABLESPACE CABIO_MAP_FUT ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING ) NOCACHE NOPARALLEL MONITORING
/


