DROP TABLE ZSTG_ENDSNPARRAYREPCYTOIDS CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_ENDSNPARRAYREPCYTOIDS  (Table) 
--
CREATE TABLE ZSTG_ENDSNPARRAYREPCYTOIDS ( ID NUMBER NOT NULL, CYTO_STOP VARCHAR2(255 BYTE) NULL, CYTOBANDID NUMBER NOT NULL, CHROMOSOME_ID NUMBER NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


