DROP TABLE ZSTG_SNP_ILLUMINA CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_SNP_ILLUMINA  (Table) 
--
CREATE TABLE ZSTG_SNP_ILLUMINA ( DBSNP_RS_ID VARCHAR2(20 BYTE) NOT NULL, CHROMOSOME VARCHAR2(2 BYTE) NOT NULL, COORDINATE VARCHAR2(20 BYTE) NOT NULL, GENOME_BUILD VARCHAR2(20 BYTE) NOT NULL, GENE_SYMBOL VARCHAR2(20 BYTE) NOT NULL, GENE_ACCESSION VARCHAR2(20 BYTE) NOT NULL, LOCATION VARCHAR2(20 BYTE) NOT NULL, LOCATION_RELATIVE_TO_GENE VARCHAR2(20 BYTE) NOT NULL, CODING_STATUS VARCHAR2(30 BYTE) NULL, AMINO_ACID_CHANGE VARCHAR2(30 BYTE) NULL, ID_WITH_MOUSE VARCHAR2(30 BYTE) NULL, PHAST_CONSERVATION VARCHAR2(30 BYTE) NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


