DROP TABLE ZSTG_POPULATION_FREQUENCY CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_POPULATION_FREQUENCY  (Table) 
--
CREATE TABLE ZSTG_POPULATION_FREQUENCY ( ID NUMBER NOT NULL, TYPE VARCHAR2(50 BYTE) NOT NULL, ETHNICITY VARCHAR2(50 BYTE) NOT NULL, MAJOR_FREQUENCY NUMBER NOT NULL, MINOR_FREQUENCY NUMBER NOT NULL, HETEROZYGOUS_FREQUENCY NUMBER NOT NULL, SNP_ID NUMBER NULL, MAJOR_ALLELE VARCHAR2(30 BYTE) NOT NULL, MINOR_ALLELE VARCHAR2(30 BYTE) NOT NULL, BIG_ID VARCHAR2(200 BYTE) NULL, SNP_PROBESET_AFFY_ID VARCHAR2(100 BYTE) NOT NULL ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


