ALTER TABLE ZSTG_GENE_AGENT_EVIDENCE_CGID
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ZSTG_GENE_AGENT_EVIDENCE_CGID CASCADE CONSTRAINTS PURGE
/

--
-- ZSTG_GENE_AGENT_EVIDENCE_CGID  (Table) 
--
CREATE TABLE ZSTG_GENE_AGENT_EVIDENCE_CGID ( GENE_ID NUMBER NULL, AGENT_ID NUMBER NULL, EVIDENCE_ID NUMBER NULL, ROLE_ID VARCHAR2(1000 BYTE) NULL, CONSTRAINT GAER_PK PRIMARY KEY (GENE_ID, EVIDENCE_ID, AGENT_ID, ROLE_ID) ) TABLESPACE CABIO_MAP_FUT NOLOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/


