
alter table ZSTG_INTERACTIONCOMPONENTLABEL disable constraint SYS_C0020851;
alter table ZSTG_INTERACTIONCOMPONENTLABEL disable constraint SYS_C0020852;
alter table ZSTG_INTERACTIONCOMPONENTLABEL disable constraint SYS_C0020853;
alter table ZSTG_INTERACTIONCOMPONENTLABEL disable constraint SYS_C0020854;
alter table ZSTG_INTERACTIONCOMPONENTLABEL disable constraint SYS_C0020855;
alter table ZSTG_INTERACTIONCOMPONENTLABEL disable constraint SYS_C0020856;

--EXIT;
