DROP PUBLIC SYNONYM AR_CHROMOSOMAL_LOCATION_TMP
/

--
-- AR_CHROMOSOMAL_LOCATION_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_CHROMOSOMAL_LOCATION_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_CHROMOSOMAL_LOCATION_TMP FOR AR_CHROMOSOMAL_LOCATION_TMP
/


