DROP PUBLIC SYNONYM CLONE_RELATIVE_LOCATION
/

--
-- CLONE_RELATIVE_LOCATION  (Synonym) 
--
--  Dependencies: 
--   CLONE_RELATIVE_LOCATION (Table)
--
CREATE PUBLIC SYNONYM CLONE_RELATIVE_LOCATION FOR CLONE_RELATIVE_LOCATION
/


