DROP PUBLIC SYNONYM DAS_DATA_SOURCE_BUILD
/

--
-- DAS_DATA_SOURCE_BUILD  (Synonym) 
--
--  Dependencies: 
--   DAS_DATA_SOURCE_BUILD (Table)
--
CREATE PUBLIC SYNONYM DAS_DATA_SOURCE_BUILD FOR DAS_DATA_SOURCE_BUILD
/


