DROP PUBLIC SYNONYM HISTOPATHOLOGY_TST
/

--
-- HISTOPATHOLOGY_TST  (Synonym) 
--
--  Dependencies: 
--   HISTOPATHOLOGY_TST (Table)
--
CREATE PUBLIC SYNONYM HISTOPATHOLOGY_TST FOR HISTOPATHOLOGY_TST
/


