DROP PUBLIC SYNONYM PID_FAMILY_PARTICIPANT
/

--
-- PID_FAMILY_PARTICIPANT  (Synonym) 
--
--  Dependencies: 
--   PID_FAMILY_PARTICIPANT (Table)
--
CREATE PUBLIC SYNONYM PID_FAMILY_PARTICIPANT FOR PID_FAMILY_PARTICIPANT
/


