DROP PUBLIC SYNONYM PID_ENTITY_PROTEIN
/

--
-- PID_ENTITY_PROTEIN  (Synonym) 
--
--  Dependencies: 
--   PID_ENTITY_PROTEIN (Table)
--
CREATE PUBLIC SYNONYM PID_ENTITY_PROTEIN FOR PID_ENTITY_PROTEIN
/


