DROP PUBLIC SYNONYM PID_ENTITY_ACCESSION
/

--
-- PID_ENTITY_ACCESSION  (Synonym) 
--
--  Dependencies: 
--   PID_ENTITY_ACCESSION (Table)
--
CREATE PUBLIC SYNONYM PID_ENTITY_ACCESSION FOR PID_ENTITY_ACCESSION
/


