DROP PUBLIC SYNONYM WEB_SERV_SOURCE_REFERENCE
/

--
-- WEB_SERV_SOURCE_REFERENCE  (Synonym) 
--
--  Dependencies: 
--   WEB_SERV_SOURCE_REFERENCE (Table)
--
CREATE PUBLIC SYNONYM WEB_SERV_SOURCE_REFERENCE FOR WEB_SERV_SOURCE_REFERENCE
/


