DROP PUBLIC SYNONYM ZSTG_PID_COMP_PARTCIPANT_PTM
/

--
-- ZSTG_PID_COMP_PARTCIPANT_PTM  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_COMP_PARTCIPANT_PTM (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_COMP_PARTCIPANT_PTM FOR ZSTG_PID_COMP_PARTCIPANT_PTM
/


