DROP PUBLIC SYNONYM ZSTG_PID_COMP_PARTCIPANT_ACTST
/

--
-- ZSTG_PID_COMP_PARTCIPANT_ACTST  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_COMP_PARTCIPANT_ACTST (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_COMP_PARTCIPANT_ACTST FOR ZSTG_PID_COMP_PARTCIPANT_ACTST
/


