DROP PUBLIC SYNONYM ZSTG_SNP_ASSOCIATED_GENE
/

--
-- ZSTG_SNP_ASSOCIATED_GENE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_SNP_ASSOCIATED_GENE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_SNP_ASSOCIATED_GENE FOR ZSTG_SNP_ASSOCIATED_GENE
/


