DROP PUBLIC SYNONYM ZSTG_GENE_EVIDENCE_CGID
/

--
-- ZSTG_GENE_EVIDENCE_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_EVIDENCE_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_EVIDENCE_CGID FOR ZSTG_GENE_EVIDENCE_CGID
/


