DROP PUBLIC SYNONYM ZSTG_GENE_EXPRESSED_IN
/

--
-- ZSTG_GENE_EXPRESSED_IN  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_EXPRESSED_IN (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_EXPRESSED_IN FOR ZSTG_GENE_EXPRESSED_IN
/


