DROP PUBLIC SYNONYM ZSTG_EXON_REPORTER
/

--
-- ZSTG_EXON_REPORTER  (Synonym) 
--
--  Dependencies: 
--   ZSTG_EXON_REPORTER (Table)
--
CREATE PUBLIC SYNONYM ZSTG_EXON_REPORTER FOR ZSTG_EXON_REPORTER
/


