DROP PUBLIC SYNONYM ZSTG_MOLECULEFAMILIES
/

--
-- ZSTG_MOLECULEFAMILIES  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MOLECULEFAMILIES (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MOLECULEFAMILIES FOR ZSTG_MOLECULEFAMILIES
/


