DROP PUBLIC SYNONYM ZSTG_PID_PROTEINSUBUNIT
/

--
-- ZSTG_PID_PROTEINSUBUNIT  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_PROTEINSUBUNIT (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_PROTEINSUBUNIT FOR ZSTG_PID_PROTEINSUBUNIT
/


