DROP PUBLIC SYNONYM ZSTG_GENE_GENEALIAS_CGID
/

--
-- ZSTG_GENE_GENEALIAS_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_GENEALIAS_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_GENEALIAS_CGID FOR ZSTG_GENE_GENEALIAS_CGID
/


