DROP PUBLIC SYNONYM AR_GO_MOLECULAR_FUNCTION
/

--
-- AR_GO_MOLECULAR_FUNCTION  (Synonym) 
--
--  Dependencies: 
--   AR_GO_MOLECULAR_FUNCTION (Table)
--
CREATE PUBLIC SYNONYM AR_GO_MOLECULAR_FUNCTION FOR AR_GO_MOLECULAR_FUNCTION
/


