DROP PUBLIC SYNONYM AR_RNA_PROBESETS_AFFY_TMP
/

--
-- AR_RNA_PROBESETS_AFFY_TMP  (Synonym) 
--
--  Dependencies: 
--   AR_RNA_PROBESETS_AFFY_TMP (Table)
--
CREATE PUBLIC SYNONYM AR_RNA_PROBESETS_AFFY_TMP FOR AR_RNA_PROBESETS_AFFY_TMP
/


