DROP PUBLIC SYNONYM CGAP_TISSUE_SELECTION
/

--
-- CGAP_TISSUE_SELECTION  (Synonym) 
--
--  Dependencies: 
--   CGAP_TISSUE_SELECTION (Table)
--
CREATE PUBLIC SYNONYM CGAP_TISSUE_SELECTION FOR CGAP_TISSUE_SELECTION
/


