DROP PUBLIC SYNONYM EVIDENCE_EVIDENCE_CODE
/

--
-- EVIDENCE_EVIDENCE_CODE  (Synonym) 
--
--  Dependencies: 
--   EVIDENCE_EVIDENCE_CODE (Table)
--
CREATE PUBLIC SYNONYM EVIDENCE_EVIDENCE_CODE FOR EVIDENCE_EVIDENCE_CODE
/


