DROP PUBLIC SYNONYM EXPRESSION_REPORTER
/

--
-- EXPRESSION_REPORTER  (Synonym) 
--
--  Dependencies: 
--   EXPRESSION_REPORTER (Table)
--
CREATE PUBLIC SYNONYM EXPRESSION_REPORTER FOR EXPRESSION_REPORTER
/


