DROP PUBLIC SYNONYM GENERIC_ARRAY_GENERIC_REPORTER
/

--
-- GENERIC_ARRAY_GENERIC_REPORTER  (Synonym) 
--
--  Dependencies: 
--   GENERIC_ARRAY_GENERIC_REPORTER (Table)
--
CREATE PUBLIC SYNONYM GENERIC_ARRAY_GENERIC_REPORTER FOR GENERIC_ARRAY_GENERIC_REPORTER
/


