DROP PUBLIC SYNONYM GENE_NUCLEIC_ACID_SEQUENCE
/

--
-- GENE_NUCLEIC_ACID_SEQUENCE  (Synonym) 
--
--  Dependencies: 
--   GENE_NUCLEIC_ACID_SEQUENCE (Table)
--
CREATE PUBLIC SYNONYM GENE_NUCLEIC_ACID_SEQUENCE FOR GENE_NUCLEIC_ACID_SEQUENCE
/


