DROP PUBLIC SYNONYM MARKER_MARKER_ALIAS
/

--
-- MARKER_MARKER_ALIAS  (Synonym) 
--
--  Dependencies: 
--   MARKER_MARKER_ALIAS (Table)
--
CREATE PUBLIC SYNONYM MARKER_MARKER_ALIAS FOR MARKER_MARKER_ALIAS
/


