DROP PUBLIC SYNONYM MARKER_RELATIVE_LOCATION
/

--
-- MARKER_RELATIVE_LOCATION  (Synonym) 
--
--  Dependencies: 
--   MARKER_RELATIVE_LOCATION (Table)
--
CREATE PUBLIC SYNONYM MARKER_RELATIVE_LOCATION FOR MARKER_RELATIVE_LOCATION
/


