DROP PUBLIC SYNONYM PID_PHYSICAL_ENTITY_NAME
/

--
-- PID_PHYSICAL_ENTITY_NAME  (Synonym) 
--
--  Dependencies: 
--   PID_PHYSICAL_ENTITY_NAME (Table)
--
CREATE PUBLIC SYNONYM PID_PHYSICAL_ENTITY_NAME FOR PID_PHYSICAL_ENTITY_NAME
/


