DROP PUBLIC SYNONYM POPULATION_FREQUENCY
/

--
-- POPULATION_FREQUENCY  (Synonym) 
--
--  Dependencies: 
--   POPULATION_FREQUENCY (Table)
--
CREATE PUBLIC SYNONYM POPULATION_FREQUENCY FOR POPULATION_FREQUENCY
/


