DROP PUBLIC SYNONYM PROTEIN_SECONDARY_ACCESSION
/

--
-- PROTEIN_SECONDARY_ACCESSION  (Synonym) 
--
--  Dependencies: 
--   PROTEIN_SECONDARY_ACCESSION (Table)
--
CREATE PUBLIC SYNONYM PROTEIN_SECONDARY_ACCESSION FOR PROTEIN_SECONDARY_ACCESSION
/


