DROP PUBLIC SYNONYM RELATIVE_LOCATION_CH
/

--
-- RELATIVE_LOCATION_CH  (Synonym) 
--
--  Dependencies: 
--   RELATIVE_LOCATION_CH (Table)
--
CREATE PUBLIC SYNONYM RELATIVE_LOCATION_CH FOR RELATIVE_LOCATION_CH
/


