DROP PUBLIC SYNONYM RESEARCH_INSTITUTION_SOURCE
/

--
-- RESEARCH_INSTITUTION_SOURCE  (Synonym) 
--
--  Dependencies: 
--   RESEARCH_INSTITUTION_SOURCE (Table)
--
CREATE PUBLIC SYNONYM RESEARCH_INSTITUTION_SOURCE FOR RESEARCH_INSTITUTION_SOURCE
/


