DROP PUBLIC SYNONYM ZSTG_MOLECULECOMPONENTLABELS
/

--
-- ZSTG_MOLECULECOMPONENTLABELS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MOLECULECOMPONENTLABELS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MOLECULECOMPONENTLABELS FOR ZSTG_MOLECULECOMPONENTLABELS
/


