DROP PUBLIC SYNONYM ZSTG_BIOPATHWAY_DESCR
/

--
-- ZSTG_BIOPATHWAY_DESCR  (Synonym) 
--
--  Dependencies: 
--   ZSTG_BIOPATHWAY_DESCR (Table)
--
CREATE PUBLIC SYNONYM ZSTG_BIOPATHWAY_DESCR FOR ZSTG_BIOPATHWAY_DESCR
/


