DROP PUBLIC SYNONYM ZSTG_INTERACTIONCOMPPTMTERMS
/

--
-- ZSTG_INTERACTIONCOMPPTMTERMS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_INTERACTIONCOMPPTMTERMS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_INTERACTIONCOMPPTMTERMS FOR ZSTG_INTERACTIONCOMPPTMTERMS
/


