DROP PUBLIC SYNONYM ZSTG_MOUSE_CYTOBAND
/

--
-- ZSTG_MOUSE_CYTOBAND  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MOUSE_CYTOBAND (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MOUSE_CYTOBAND FOR ZSTG_MOUSE_CYTOBAND
/


