DROP PUBLIC SYNONYM ZSTG_EXPRESSION_REPORTER
/

--
-- ZSTG_EXPRESSION_REPORTER  (Synonym) 
--
--  Dependencies: 
--   ZSTG_EXPRESSION_REPORTER (Table)
--
CREATE PUBLIC SYNONYM ZSTG_EXPRESSION_REPORTER FOR ZSTG_EXPRESSION_REPORTER
/


