/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP PUBLIC SYNONYM ZSTG_STARTSNPARRAYREPCYTOIDS
/

--
-- ZSTG_STARTSNPARRAYREPCYTOIDS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_STARTSNPARRAYREPCYTOIDS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_STARTSNPARRAYREPCYTOIDS FOR ZSTG_STARTSNPARRAYREPCYTOIDS
/


