/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

DROP PUBLIC SYNONYM ZSTG_INTERACTIONCOMPONENTLABEL
/

--
-- ZSTG_INTERACTIONCOMPONENTLABEL  (Synonym) 
--
--  Dependencies: 
--   ZSTG_INTERACTIONCOMPONENTLABEL (Table)
--
CREATE PUBLIC SYNONYM ZSTG_INTERACTIONCOMPONENTLABEL FOR ZSTG_INTERACTIONCOMPONENTLABEL
/


