DROP PUBLIC SYNONYM ZSTG_PID_INTERACTIONREFERENCE
/

--
-- ZSTG_PID_INTERACTIONREFERENCE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_INTERACTIONREFERENCE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_INTERACTIONREFERENCE FOR ZSTG_PID_INTERACTIONREFERENCE
/


