DROP PUBLIC SYNONYM ZSTG_PID_INTERACTIONEVIDENCE
/

--
-- ZSTG_PID_INTERACTIONEVIDENCE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_INTERACTIONEVIDENCE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_INTERACTIONEVIDENCE FOR ZSTG_PID_INTERACTIONEVIDENCE
/


