DROP PUBLIC SYNONYM ZSTG_MERGED_SNP_RSIDS_MAPPING
/

--
-- ZSTG_MERGED_SNP_RSIDS_MAPPING  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MERGED_SNP_RSIDS_MAPPING (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MERGED_SNP_RSIDS_MAPPING FOR ZSTG_MERGED_SNP_RSIDS_MAPPING
/


