DROP PUBLIC SYNONYM ZSTG_GENE_AGENT_CGID
/

--
-- ZSTG_GENE_AGENT_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_AGENT_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_AGENT_CGID FOR ZSTG_GENE_AGENT_CGID
/


