DROP PUBLIC SYNONYM ZSTG_GENE_ONTOLOGY
/

--
-- ZSTG_GENE_ONTOLOGY  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_ONTOLOGY (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_ONTOLOGY FOR ZSTG_GENE_ONTOLOGY
/


