DROP PUBLIC SYNONYM ZSTG_MOLECULEPARTS
/

--
-- ZSTG_MOLECULEPARTS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MOLECULEPARTS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MOLECULEPARTS FOR ZSTG_MOLECULEPARTS
/


