DROP PUBLIC SYNONYM ZSTG_PID_PATHWAYREFERENCE
/

--
-- ZSTG_PID_PATHWAYREFERENCE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_PATHWAYREFERENCE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_PATHWAYREFERENCE FOR ZSTG_PID_PATHWAYREFERENCE
/


