DROP PUBLIC SYNONYM ZSTG_MISSING_DISEASEONTOL_CGID
/

--
-- ZSTG_MISSING_DISEASEONTOL_CGID  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MISSING_DISEASEONTOL_CGID (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MISSING_DISEASEONTOL_CGID FOR ZSTG_MISSING_DISEASEONTOL_CGID
/


