
create index HOMOLOGOTION_HOMOLOGOUS on HOMOLOGOUS_ASSOCIATION(HOMOLOGOUS_GENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HOMOLOGOTION_HOMOLOGOUS on HOMOLOGOUS_ASSOCIATION(HOMOLOGOUS_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HOMOLOGOTION_SIMILARITY on HOMOLOGOUS_ASSOCIATION(SIMILARITY_PERCENTAGE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HOMOLOGOTION_ID on HOMOLOGOUS_ASSOCIATION(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
