
drop index ZSTG_PATWAYS_ORGANISM_LWR;
drop index ZSTG_PATWAYS_PATHWAY_ID_LWR;
drop index ZSTG_PATWAYS_SUBNET_LWR;
drop index ZSTG_PATWAYS_LONGNAME_LWR;
drop index ZSTG_PATWAYS_SHORTNAME_LWR;
drop index ZSTG_PATWAYS_SOURCE_ID_LWR;
drop index ZSTG_PATWAYS_ORGANISM;
drop index ZSTG_PATWAYS_PATHWAY_ID;
drop index ZSTG_PATWAYS_SUBNET;
drop index ZSTG_PATWAYS_LONGNAME;
drop index ZSTG_PATWAYS_SHORTNAME;
drop index ZSTG_PATWAYS_SOURCE_ID;

--EXIT;
