
drop index ZSTG_MERGED_SNP_RSIDS_MAP_PK;
drop index ZSTG_MERPING_OLD_RS_ID_LWR;
drop index ZSTG_MERPING_NEW_RS_ID_LWR;
drop index ZSTG_MERPING_BUILD_ID_LWR;
drop index ZSTG_MERPING_ORIENTATIO_LWR;
drop index ZSTG_MERPING_CREATE_TIM_LWR;
drop index ZSTG_MERPING_LAST_UPDAT_LWR;
drop index ZSTG_MERPING_CURRENT_RS_LWR;
drop index ZSTG_MERPING_ORIEN2CURR_LWR;
drop index ZSTG_MERPING_NEW_RS_ID;
drop index ZSTG_MERPING_BUILD_ID;
drop index ZSTG_MERPING_ORIENTATIO;
drop index ZSTG_MERPING_CREATE_TIM;
drop index ZSTG_MERPING_LAST_UPDAT;
drop index ZSTG_MERPING_CURRENT_RS;
drop index ZSTG_MERPING_ORIEN2CURR;

--EXIT;
