
create index ZSTG_INTENCE_PMID on ZSTG_INTERACTIONREFERENCE(PMID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTENCE_REFERENCE on ZSTG_INTERACTIONREFERENCE(REFERENCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTENCE_SOURCE_ID on ZSTG_INTERACTIONREFERENCE(SOURCE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTENCE_INTERACTIO on ZSTG_INTERACTIONREFERENCE(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
