LOAD DATA 
 
INFILE '$CABIO_DATA_DIR/temp/arrays/Affymetrix/HuEx10ST/HuEx-1_0-st-v2.probeset.dat'

APPEND
 
INTO TABLE ZSTG_EXON_AFFY
 
REENABLE DISABLED_CONSTRAINTS 
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
 
(
PROBE_SET_ID,
SEQNAME,
STRAND,
START_LOCATION,
STOP_LOCATION,
PROBE_COUNT,
TRANSCRIPT_CLUSTER_ID,
EXON_ID,
PSR_ID,
GENE_ASSIGNMENT char(100000),
MRNA_ASSIGNMENT char(100000),
CROSSHYB_TYPE,
NUM_INDEPENDENT_PROBES,
NUM_CROSS_HYB_PROBES,
NUM_NONOVERLAP_PROBES,
BOUNDED,
NO_BOUNDED_EVIDENCE,
HAS_CDS,
FL,
MRNA,
EST,
VEGA_GENE,
VEGA_PSEUDO_GENE,
ENS_GENE,
SGP_GENE,
EXONIPHY,
TWINSCAN,
GENEID,
GENSCAN,
GENSCAN_SUBOPT,
MOUSE_FL,
MOUSE_MRNA,
RAT_FL,
RAT_MRNA,
MICRO_RNA_REGISTRY,
RNA_GENE,
MITOMAP,
PROBESET_TYPE
)
