CREATE OR REPLACE FORCE VIEW CABIODEV.EXPRESSION_MEASUREMENT_GO_VIEW
(REPORTER_ID, GO_ID)
AS 
SELECT /*+ ORDERED */ REPORTER_ID, GG.GO_ID
FROM GO_GENES GG, GENE_SEQUENCE GS, SEQUENCE S, EXPRESSION_MEASUREMENT_VIEW E
WHERE GS.GENE_ID = GG.GENE_ID
AND S.SEQUENCE_ID = GS.SEQUENCE_ID
AND S.ACCESSION_NUMBER = E.ACCESSION;


