CREATE OR REPLACE FORCE VIEW CABIODEV.MAP_OBJECT
(MAP_ID, MAP_TYPE, MAP_LOCATION, DESCRIPTION, MAP_DESCRIPTION)
AS 
SELECT MAP.MAP_ID, MAP.MAP_TYPE,
MAP.map_location, MAP_TYPE.map_Description , MAP_TYPE.map_Description
FROM MAP, MAP_TYPE WHERE MAP.MAP_TYPE = MAP_TYPE.MAP_TYPE;


