CREATE OR REPLACE FORCE VIEW CABIODEV.PATHWAY_CONTEXT_OBJECT
(CONTEXT_ID, PATHWAY_ID)
AS 
SELECT DISTINCT CONTEXT_CODE, gp.pathway_id FROM 
GENE_PATHWAY gp, BIOGENES bg, GENE_HISTOPATHOLOGY GH 
WHERE gp.bc_id = bg.bc_id 
AND GH.GENE_ID = BG.GENE_ID;


