@$LOAD/triggers.sql ar_ec
@$LOAD/triggers.sql ar_ensembl
@$LOAD/triggers.sql ar_omim
@$LOAD/triggers.sql ar_rna_probesets_affy
@$LOAD/triggers.sql ar_alignments
@$LOAD/triggers.sql ar_chromosomal_location
@$LOAD/triggers.sql ar_entrez_gene
@$LOAD/triggers.sql ar_gene_symbol
@$LOAD/triggers.sql ar_gene_title
@$LOAD/triggers.sql ar_go_biological_process
@$LOAD/triggers.sql ar_go_cellular_component
@$LOAD/triggers.sql ar_go_molecular_function
@$LOAD/triggers.sql ar_pathway
@$LOAD/triggers.sql ar_refseq_protein
@$LOAD/triggers.sql ar_refseq_transcripts
@$LOAD/triggers.sql ar_representative_public_id
@$LOAD/triggers.sql ar_swissprot
@$LOAD/triggers.sql ar_unigene_id
@$LOAD/triggers.sql zstg_interpro
@$LOAD/triggers.sql zstg_rna_probesets
@$LOAD/triggers.sql zstg_geneTIC_MAP
@$LOAD/triggers.sql zstg_microsatellite
@$LOAD/triggers.sql zstg_pop_frequency
@$LOAD/triggers.sql zstg_snp_affy
@$LOAD/triggers.sql zstg_snp_associated_gene
@$LOAD/triggers.sql zstg_exon_affy
@$LOAD/triggers.sql zstg_exon_trans_affy
@$LOAD/triggers.sql zstg_exon_trans_genes
@$LOAD/triggers.sql ar_ensembl
@$LOAD/triggers.sql ar_ec
@$LOAD/triggers.sql ar_omim
@$LOAD/triggers.sql ar_chromosomal_location
@$LOAD/triggers.sql ar_rna_probesets_affy
@$LOAD/triggers.sql ar_alignments
@$LOAD/triggers.sql ar_refseq_transcripts
@$LOAD/triggers.sql ar_entrez_gene
@$LOAD/triggers.sql ar_gene_symbol
@$LOAD/triggers.sql ar_gene_title
@$LOAD/triggers.sql ar_pathway
@$LOAD/triggers.sql ar_go_biological_process
@$LOAD/triggers.sql ar_go_cellular_component
@$LOAD/triggers.sql ar_go_molecular_function
@$LOAD/triggers.sql ar_refseq_protein
@$LOAD/triggers.sql ar_representative_public_id
@$LOAD/triggers.sql ar_swissprot
@$LOAD/triggers.sql ar_unigene_id
@$LOAD/triggers.sql zstg_interpro
@$LOAD/triggers.sql zstg_rna_probesets
@$LOAD/triggers.sql zstg_rna_agilent
@$LOAD/triggers.sql zstg_cgh_accessions
@$LOAD/triggers.sql zstg_cgh_agilent
@$LOAD/triggers.sql zstg_snp_illumina
