/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index AGENTGENT_EVS_ID_lwr on AGENT(lower(EVS_ID)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_COMM_lwr on AGENT(lower(AGENT_COMMENT)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_SOUR_lwr on AGENT(lower(AGENT_SOURCE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_NAME_lwr on AGENT(lower(AGENT_NAME)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_TYPE_lwr on AGENT(lower(AGENT_TYPE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_DRUGBANK_A_lwr on AGENT(lower(DRUGBANK_ACCESSION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_TOXICITY_lwr on AGENT(lower(TOXICITY)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_SMILES_COD_lwr on AGENT(lower(SMILES_CODE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_PROTEIN_BI_lwr on AGENT(lower(PROTEIN_BINDING)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_PHARMACOLO_lwr on AGENT(lower(PHARMACOLOGY)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_MECHANISM__lwr on AGENT(lower(MECHANISM_OF_ACTION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_IUPAC_NAME_lwr on AGENT(lower(IUPAC_NAME)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_INDICATION_lwr on AGENT(lower(INDICATION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_HALF_LIFE_lwr on AGENT(lower(HALF_LIFE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_CHEMICAL_F_lwr on AGENT(lower(CHEMICAL_FORMULA)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_CAS_NUMBER_lwr on AGENT(lower(CAS_NUMBER)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_BIOTRANSFO_lwr on AGENT(lower(BIOTRANSFORMATION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_ABSORPTION_lwr on AGENT(lower(ABSORPTION)) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
