
drop index PK_ANOMALY;
drop index ANOMALYALY_BIG_ID_LWR;
drop index ANOMALYALY_BIG_ID;
drop index ANOMALYMALY_ANOMALY_TY_LWR;
drop index ANOMALYMALY_TARGET_ID;
drop index ANOMALYMALY_ANOMALY_TY;
drop index ANOMALYMALY_CONTEXT_CO;

--EXIT;
