
create index AR_ALIGNENTS_CHROMOSOME on AR_ALIGNMENTS(CHROMOSOME_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_GENECHIP_A on AR_ALIGNMENTS(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_ASSEMBLY on AR_ALIGNMENTS(ASSEMBLY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_TRIM_CHR on AR_ALIGNMENTS(TRIM_CHR) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_DIRECTION on AR_ALIGNMENTS(DIRECTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_END_POSITI on AR_ALIGNMENTS(END_POSITION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_START_POSI on AR_ALIGNMENTS(START_POSITION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_CHROMOSOME on AR_ALIGNMENTS(CHROMOSOME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_ALIGNENTS_PROBE_SET_ on AR_ALIGNMENTS(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
