
create index AR_CHROMTION_CHROMOSOME on AR_CHROMOSOMAL_LOCATION(CHROMOSOME_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_GENECHIP_A on AR_CHROMOSOMAL_LOCATION(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_ASSEMBLY on AR_CHROMOSOMAL_LOCATION(ASSEMBLY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_TRIM_CHR on AR_CHROMOSOMAL_LOCATION(TRIM_CHR) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_CYTO_STOP on AR_CHROMOSOMAL_LOCATION(CYTO_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_CYTO_START on AR_CHROMOSOMAL_LOCATION(CYTO_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_CHROMOSOME on AR_CHROMOSOMAL_LOCATION(CHROMOSOME_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_CHROMOSOMA on AR_CHROMOSOMAL_LOCATION(CHROMOSOMAL_LOCATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROMTION_PROBE_SET_ on AR_CHROMOSOMAL_LOCATION(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
