
create index AR_GO_BI_TMP_GENECHIP_A on AR_GO_BIOLOGICAL_PROCESS_TMP(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_BI_TMP_EVIDENCE on AR_GO_BIOLOGICAL_PROCESS_TMP(EVIDENCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_BI_TMP_DESCRIPTIO on AR_GO_BIOLOGICAL_PROCESS_TMP(DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_BI_TMP_ACCESSION_ on AR_GO_BIOLOGICAL_PROCESS_TMP(ACCESSION_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_BI_TMP_PROBE_SET_ on AR_GO_BIOLOGICAL_PROCESS_TMP(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
