/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index AR_GO_CE_TMP_GENECHIP_A on AR_GO_CELLULAR_COMPONENT_TMP(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CE_TMP_EVIDENCE on AR_GO_CELLULAR_COMPONENT_TMP(EVIDENCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CE_TMP_DESCRIPTIO on AR_GO_CELLULAR_COMPONENT_TMP(DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CE_TMP_ACCESSION_ on AR_GO_CELLULAR_COMPONENT_TMP(ACCESSION_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_CE_TMP_PROBE_SET_ on AR_GO_CELLULAR_COMPONENT_TMP(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
