/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index AR_RNA_PAFFY_GENOME_VER on AR_RNA_PROBESETS_AFFY(GENOME_VERSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_RNA_PAFFY_ANNOTATION on AR_RNA_PROBESETS_AFFY(ANNOTATION_DATA) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_RNA_PAFFY_SPECIES_SC on AR_RNA_PROBESETS_AFFY(SPECIES_SCIENTIFIC_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_RNA_PAFFY_GENECHIP_A on AR_RNA_PROBESETS_AFFY(GENECHIP_ARRAY_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_RNA_PAFFY_PROBE_SET_ on AR_RNA_PROBESETS_AFFY(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_RNA_PAFFY_ID on AR_RNA_PROBESETS_AFFY(ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
