/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ARRAY_RER_CH_EXON_ID on ARRAY_REPORTER_CH(EXON_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_TRANSCRIPT on ARRAY_REPORTER_CH(TRANSCRIPT_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_GENE_ID on ARRAY_REPORTER_CH(GENE_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_NAS_ID on ARRAY_REPORTER_CH(NAS_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_SNP_ID on ARRAY_REPORTER_CH(SNP_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_STRAND on ARRAY_REPORTER_CH(STRAND) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_PROBE_COUN on ARRAY_REPORTER_CH(PROBE_COUNT) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_MANUFACTUR on ARRAY_REPORTER_CH(MANUFACTURER_PSR_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_PHAST_CONS on ARRAY_REPORTER_CH(PHAST_CONSERVATION) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_TARGET_DES on ARRAY_REPORTER_CH(TARGET_DESCRIPTION) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_TARGET_ID on ARRAY_REPORTER_CH(TARGET_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_SEQUENCE_S on ARRAY_REPORTER_CH(SEQUENCE_SOURCE) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_SEQUENCE_T on ARRAY_REPORTER_CH(SEQUENCE_TYPE) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_DISCRIMINA on ARRAY_REPORTER_CH(DISCRIMINATOR) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_MICROARRAY on ARRAY_REPORTER_CH(MICROARRAY_ID) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_NAME on ARRAY_REPORTER_CH(NAME) PARALLEL NOLOGGING tablespace cabio_fut;
create index ARRAY_RER_CH_ID on ARRAY_REPORTER_CH(ID) PARALLEL NOLOGGING tablespace cabio_fut;

--EXIT;
