
create index CLONE_TAAXON_TAXON_ID on CLONE_TAXON(TAXON_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index CLONE_TAAXON_CLONE_ID on CLONE_TAXON(CLONE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
