
drop index EXPRESSTER_BIG_ID_LWR;
drop index EXPRESSTER_BIG_ID;
drop index SYS_C0021093_IDX;
drop index EXPRESSIRTER_NAME_LWR;
drop index EXPRESSIRTER_SEQUENCE_T_LWR;
drop index EXPRESSIRTER_SEQUENCE_S_LWR;
drop index EXPRESSIRTER_TRANSCRIPT_LWR;
drop index EXPRESSIRTER_TARGET_DES_LWR;
drop index EXPRESSIRTER_ID;
drop index EXPRESSIRTER_NAME;
drop index EXPRESSIRTER_MICROARRAY;
drop index EXPRESSIRTER_SEQUENCE_T;
drop index EXPRESSIRTER_SEQUENCE_S;
drop index EXPRESSIRTER_TRANSCRIPT;
drop index EXPRESSIRTER_TARGET_DES;
drop index EXPRESSIRTER_GENE_ID;
drop index EXPRESSIRTER_NAS_ID;

--EXIT;
