
create index GENE_RELTION_TYPE on GENE_RELATIVE_LOCATION(TYPE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_RELTION_PROBE_SET_ on GENE_RELATIVE_LOCATION(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_RELTION_SNP_ID on GENE_RELATIVE_LOCATION(SNP_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_RELTION_GENE_ID on GENE_RELATIVE_LOCATION(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_RELTION_DISTANCE on GENE_RELATIVE_LOCATION(DISTANCE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_RELTION_ORIENTATIO on GENE_RELATIVE_LOCATION(ORIENTATION) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_RELTION_ID on GENE_RELATIVE_LOCATION(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
