
create index GENE_FUNTION_DISCRIMINA on GENE_FUNCTION_ASSOCIATION(DISCRIMINATOR) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_FUNTION_ID on GENE_FUNCTION_ASSOCIATION(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_FUNTION_EVIDENCE_I on GENE_FUNCTION_ASSOCIATION(EVIDENCE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_FUNTION_HISTOLOGYC on GENE_FUNCTION_ASSOCIATION(HISTOLOGYCODE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_FUNTION_AGENT_ID on GENE_FUNCTION_ASSOCIATION(AGENT_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_FUNTION_ROLE_ID on GENE_FUNCTION_ASSOCIATION(ROLE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_FUNTION_GENE_ID on GENE_FUNCTION_ASSOCIATION(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
