/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index HISTOLOGCODE_MIMID on HISTOLOGY_CODE(MIMID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOLOGCODE_EVS_ID on HISTOLOGY_CODE(EVS_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOLOGCODE_RELATIONSH on HISTOLOGY_CODE(RELATIONSHIP) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOLOGCODE_CONCEPT_ID on HISTOLOGY_CODE(CONCEPT_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOLOGCODE_PARENT on HISTOLOGY_CODE(PARENT) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOLOGCODE_HISTOLOGY_ on HISTOLOGY_CODE(HISTOLOGY_NAME) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOLOGCODE_HISTOLOGY_ on HISTOLOGY_CODE(HISTOLOGY_CODE) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
