
create index HISTOPAT_TST_ANIMALMODE on HISTOPATHOLOGY_TST(ANIMALMODEL_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_METASTASIS on HISTOPATHOLOGY_TST(METASTASISOF) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_ORGAN_ID on HISTOPATHOLOGY_TST(ORGAN_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_AGEOFONSET on HISTOPATHOLOGY_TST(AGEOFONSET) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_GROSSDESCR on HISTOPATHOLOGY_TST(GROSSDESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_MICROSCOPI on HISTOPATHOLOGY_TST(MICROSCOPICDESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_RELATIONAL on HISTOPATHOLOGY_TST(RELATIONALOPERATION) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_COMMENTS on HISTOPATHOLOGY_TST(COMMENTS) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_TUMORINCID on HISTOPATHOLOGY_TST(TUMORINCIDENCERATE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_SURVIVALIN on HISTOPATHOLOGY_TST(SURVIVALINFO) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_HISTOLOGY_ on HISTOPATHOLOGY_TST(HISTOLOGY_CODE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_TISSUE_COD on HISTOPATHOLOGY_TST(TISSUE_CODE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index HISTOPAT_TST_HISTOPATHO on HISTOPATHOLOGY_TST(HISTOPATHOLOGY_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
