/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index LIBRARYRARY_LIBRARY_ID on LIBRARY(LIBRARY_ID) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_CLONES_TO_ on LIBRARY(CLONES_TO_DATE) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_IDS_LIB_TI on LIBRARY(IDS_LIB_TISSUE_SAMPLE) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_IMAGE_LEGE on LIBRARY(IMAGE_LEGEND) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_KEYWORD on LIBRARY(KEYWORD) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_LAB_HOST on LIBRARY(LAB_HOST) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_LIBRARY_NA on LIBRARY(LIBRARY_NAME) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_R_SITE_1 on LIBRARY(R_SITE_1) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_R_SITE_2 on LIBRARY(R_SITE_2) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_SEQUENCES_ on LIBRARY(SEQUENCES_TO_DATE) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_DESCRIPTIO on LIBRARY(DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_CGAP_LIBRA on LIBRARY(CGAP_LIBRARY_ID) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_LIBRARY_TY on LIBRARY(LIBRARY_TYPE) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_CREATE_DAT on LIBRARY(CREATE_DATE) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_LIBRARY_PR on LIBRARY(LIBRARY_PROTOCOL) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_TISSUE_PRO on LIBRARY(TISSUE_PROTOCOL) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_TISSUE_ID on LIBRARY(TISSUE_ID) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_TAXON_ID on LIBRARY(TAXON_ID) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_UNIGENE_ID on LIBRARY(UNIGENE_ID) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_VECTOR on LIBRARY(VECTOR) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_VECTOR_TYP on LIBRARY(VECTOR_TYPE) PARALLEL NOLOGGING tablespace CABIO;
create index LIBRARYRARY_PRODUCER on LIBRARY(PRODUCER) PARALLEL NOLOGGING tablespace CABIO;

--EXIT;
