/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

drop index LIBRARYRARY_PRODUCER_LWR;
drop index LIBRARYRARY_VECTOR_TYP_LWR;
drop index LIBRARYRARY_VECTOR_LWR;
drop index LIBRARYRARY_LIBRARY_TY_LWR;
drop index LIBRARYRARY_DESCRIPTIO_LWR;
drop index LIBRARYRARY_R_SITE_2_LWR;
drop index LIBRARYRARY_R_SITE_1_LWR;
drop index LIBRARYRARY_LIBRARY_NA_LWR;
drop index LIBRARYRARY_LAB_HOST_LWR;
drop index LIBRARYRARY_KEYWORD_LWR;
drop index LIBRARYRARY_IMAGE_LEGE_LWR;
drop index LIBRARYRARY_IDS_LIB_TI_LWR;
drop index LIBRARYRARY_PRODUCER;
drop index LIBRARYRARY_VECTOR_TYP;
drop index LIBRARYRARY_VECTOR;
drop index LIBRARYRARY_UNIGENE_ID;
drop index LIBRARYRARY_TAXON_ID;
drop index LIBRARYRARY_TISSUE_ID;
drop index LIBRARYRARY_TISSUE_PRO;
drop index LIBRARYRARY_LIBRARY_PR;
drop index LIBRARYRARY_CGAP_LIBRA;
drop index LIBRARYRARY_DESCRIPTIO;
drop index LIBRARYRARY_SEQUENCES_;
drop index LIBRARYRARY_R_SITE_2;
drop index LIBRARYRARY_R_SITE_1;
drop index LIBRARYRARY_LIBRARY_NA;
drop index LIBRARYRARY_LAB_HOST;
drop index LIBRARYRARY_KEYWORD;
drop index LIBRARYRARY_CLONES_TO_;
drop index LIBRARYRARY_IMAGE_LEGE;
drop index LIBPK;
drop index LIBRARYBRARY_BIG_ID;
drop index LIBRARYRARY_LIBRARY_TY;
drop index LIBRARYRARY_CREATE_DAT;
drop index LIBRARYRARY_IDS_LIB_TI;
drop index LIBRARYBRARY_BIG_ID_LWR;

--EXIT;
