/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index MARKER_RTION_PROBE_SET_ on MARKER_RELATIVE_LOCATION(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MARKER_RTION_SNP_ID on MARKER_RELATIVE_LOCATION(SNP_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MARKER_RTION_DISTANCE on MARKER_RELATIVE_LOCATION(DISTANCE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MARKER_RTION_ORIENTATIO on MARKER_RELATIVE_LOCATION(ORIENTATION) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MARKER_RTION_TYPE on MARKER_RELATIVE_LOCATION(TYPE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MARKER_RTION_ID on MARKER_RELATIVE_LOCATION(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
