
create index ORGANONTSHIP_ORGAN_ONTO on ORGANONTOLOGYRELATIONSHIP(ORGAN_ONTOLOGY_RELATIONSHIP_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index ORGANONTSHIP_CHILD_ID on ORGANONTOLOGYRELATIONSHIP(CHILD_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index ORGANONTSHIP_PARENT_ID on ORGANONTOLOGYRELATIONSHIP(PARENT_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index ORGANONTSHIP_RELATIONSH on ORGANONTOLOGYRELATIONSHIP(RELATIONSHIP) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index ORGANONTSHIP_CHILD_ID_2 on ORGANONTOLOGYRELATIONSHIP(CHILD_ID_2) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
