
create index PID_INTEENCE_EVIDENCE_I on PID_INTERACTION_EVIDENCE(EVIDENCE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PID_INTEENCE_INTERACTIO on PID_INTERACTION_EVIDENCE(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
