/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index POPULATIENCY_MAJOR_FREQ on POPULATION_FREQUENCY(MAJOR_FREQUENCY) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_ETHNICITY on POPULATION_FREQUENCY(ETHNICITY) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_TYPE on POPULATION_FREQUENCY(TYPE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_ID on POPULATION_FREQUENCY(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_SNP_PROBES on POPULATION_FREQUENCY(SNP_PROBESET_AFFY_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_MINOR_ALLE on POPULATION_FREQUENCY(MINOR_ALLELE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_MAJOR_ALLE on POPULATION_FREQUENCY(MAJOR_ALLELE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_SNP_ID on POPULATION_FREQUENCY(SNP_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_HETEROZYGO on POPULATION_FREQUENCY(HETEROZYGOUS_FREQUENCY) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_MINOR_FREQ on POPULATION_FREQUENCY(MINOR_FREQUENCY) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
