/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index POPULATIENCY_ETHNICITY_lwr on POPULATION_FREQUENCY(lower(ETHNICITY)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_TYPE_lwr on POPULATION_FREQUENCY(lower(TYPE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_SNP_PROBES_lwr on POPULATION_FREQUENCY(lower(SNP_PROBESET_AFFY_ID)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_MINOR_ALLE_lwr on POPULATION_FREQUENCY(lower(MINOR_ALLELE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index POPULATIENCY_MAJOR_ALLE_lwr on POPULATION_FREQUENCY(lower(MAJOR_ALLELE)) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
