
create index PROTEIN_OUND_VALUE on PROTEIN_COMPOUND(VALUE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTEIN_OUND_COMPOUND_I on PROTEIN_COMPOUND(COMPOUND_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
