/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index PROTOCOLCOLS_PDQ_PROTOC_lwr on PROTOCOLS(lower(PDQ_PROTOCOL_CODE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_REVIEWER_N_lwr on PROTOCOLS(lower(REVIEWER_NAME)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_PI_NAME_lwr on PROTOCOLS(lower(PI_NAME)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_LEAD_ORGAN_lwr on PROTOCOLS(lower(LEAD_ORGANIZATION_NAME)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_LEAD_ORGAN_lwr on PROTOCOLS(lower(LEAD_ORGANIZATION_CTEP_ID)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_CURRENT_ST_lwr on PROTOCOLS(lower(CURRENT_STATUS)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_NIH_ADMIN__lwr on PROTOCOLS(lower(NIH_ADMIN_CODE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_TREATMENT__lwr on PROTOCOLS(lower(TREATMENT_FLAG)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_PARTICIPAT_lwr on PROTOCOLS(lower(PARTICIPATION_TYPE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_PHASE_lwr on PROTOCOLS(lower(PHASE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_TITLE_lwr on PROTOCOLS(lower(TITLE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROTOCOLCOLS_DOCUMENT_N_lwr on PROTOCOLS(lower(DOCUMENT_NUMBER)) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
