
drop index SYS_IL0000012764C00003$$;
drop index PROVENANANCE_ID;
drop index PROVENANANCE_EVIDENCE_C;
drop index PROVENANANCE_SOURCE_REF;
drop index PROVENANANCE_IMMEDIATE_;
drop index PROVENANANCE_SUPPLYING_;
drop index PROVENANANCE_ORIGINAL_S;
drop index PROVENANANCE_FULLY_QUAL;
drop index PROVENANANCE_OBJECT_IDE;
drop index PROVENANANCE_EVIDENCE_C_LWR;
drop index PROVENANANCE_FULLY_QUAL_LWR;
drop index PROVENANANCE_OBJECT_IDE_LWR;

--EXIT;
