/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index TAXONAXON_PERFERED on TAXON(PERFERED) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TAXONAXON_TAXON_ID on TAXON(TAXON_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TAXONAXON_STRAIN_OR_ on TAXON(STRAIN_OR_ETHNICITY) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TAXONAXON_COMMON_NAM on TAXON(COMMON_NAME) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TAXONAXON_ABBREVIATI on TAXON(ABBREVIATION) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TAXONAXON_SCIENTIFIC on TAXON(SCIENTIFIC_NAME) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
