
drop index TISSUE_SMPLE_TISSUE_PRO;
drop index TISSUE_SMPLE_SAMPLE_ID;
drop index TISSUE_SMPLE_DEVELOPMEN;
drop index TISSUE_SMPLE_CELL_LINE;
drop index TISSUE_SMPLE_CELL_TYPE;
drop index TISSUE_SMPLE_TISSUE_TYP;
drop index TISSUE_SMPLE_DESCRIPTIO;
drop index TISSUE_SMPLE_HISTOLOGY;
drop index TISSUE_SMPLE_SUPPLIER;
drop index TISSUE_SMPLE_SEX;
drop index TISSUE_SMPLE_ORGAN;
drop index TISSUE_SMPLE_TISSUE_NAM;
drop index TISSUE_SMPLE_TISSUE_ID;
drop index TISSUE_SMPLE_DEVELOPMEN_LWR;
drop index TISSUE_SMPLE_CELL_LINE_LWR;
drop index TISSUE_SMPLE_CELL_TYPE_LWR;
drop index TISSUE_SMPLE_TISSUE_TYP_LWR;
drop index TISSUE_SMPLE_DESCRIPTIO_LWR;
drop index TISSUE_SMPLE_HISTOLOGY_LWR;
drop index TISSUE_SMPLE_SUPPLIER_LWR;
drop index TISSUE_SMPLE_SEX_LWR;
drop index TISSUE_SMPLE_ORGAN_LWR;
drop index TISSUE_SMPLE_TISSUE_NAM_LWR;
drop index TISSUE_SSUE_SAMPLE_BIG_ID_LWR;
drop index TISSUE_SSUE_SAMPLE_BIG_ID;

--EXIT;
