
drop index TRANSCRIPT_BIG_ID_LWR;
drop index TRANSCRIPT_BIG_ID;
drop index SYS_C0021192_IDX;
drop index TRANSCRIRIPT_MANUFACTUR_LWR;
drop index TRANSCRIRIPT_SOURCE_LWR;
drop index TRANSCRIRIPT_STRAND_LWR;
drop index TRANSCRIRIPT_PROBE_COUN_LWR;
drop index TRANSCRIRIPT_ID;
drop index TRANSCRIRIPT_SOURCE;
drop index TRANSCRIRIPT_STRAND;
drop index TRANSCRIRIPT_PROBE_COUN;
drop index TRANSCRIPT_MI_INDEX;

--EXIT;
