/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index TRANSCRIRIPT_PROBE_COUN on TRANSCRIPT(PROBE_COUNT) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TRANSCRIRIPT_STRAND on TRANSCRIPT(STRAND) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TRANSCRIRIPT_SOURCE on TRANSCRIPT(SOURCE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TRANSCRIRIPT_MANUFACTUR on TRANSCRIPT(MANUFACTURER_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index TRANSCRIRIPT_ID on TRANSCRIPT(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
