
drop index SYS_IL0000012922C00004$$;
drop index URL_SOURENCE_SOURCE_URL_LWR;
drop index URL_SOURENCE_ID;
drop index URL_SOURENCE_SOURCE_REF;
drop index URL_SOURENCE_SOURCE_URL;
drop index URL_SOURENCE_SOURCE_REF_LWR;

--EXIT;
