
create index ZSTG_GENSION_PROTEIN_ID on ZSTG_GENE2ACCESSION(PROTEIN_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_ORIENTATIO on ZSTG_GENE2ACCESSION(ORIENTATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_END_POSITO on ZSTG_GENE2ACCESSION(END_POSITON) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_START_POSI on ZSTG_GENE2ACCESSION(START_POSITION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_GENOMIC_NU on ZSTG_GENE2ACCESSION(GENOMIC_NUCLEOTIDE_GI) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_GENOMIC_NU on ZSTG_GENE2ACCESSION(GENOMIC_NUCLEOTIDE_ACC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_PROTEIN_GI on ZSTG_GENE2ACCESSION(PROTEIN_GI) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_PROTEIN_AC on ZSTG_GENE2ACCESSION(PROTEIN_ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_RNA_NUCLEO on ZSTG_GENE2ACCESSION(RNA_NUCLEOTIDE_GI) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_RNA_NUCLEO on ZSTG_GENE2ACCESSION(RNA_NUCLEOTIDE_ACC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_STATUS on ZSTG_GENE2ACCESSION(STATUS) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_GENEID on ZSTG_GENE2ACCESSION(GENEID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_TAX_ID on ZSTG_GENE2ACCESSION(TAX_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
