
create index ZSTG_ARRR_CH_ORIG_ID on ZSTG_ARRAY_REPORTER_CH(ORIG_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_ASSEMBLY on ZSTG_ARRAY_REPORTER_CH(ASSEMBLY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_END_CYTOID on ZSTG_ARRAY_REPORTER_CH(END_CYTOID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_START_CYTO on ZSTG_ARRAY_REPORTER_CH(START_CYTOID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_CHROMOSOME on ZSTG_ARRAY_REPORTER_CH(CHROMOSOME_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_CYTO_STOP on ZSTG_ARRAY_REPORTER_CH(CYTO_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_CYTO_START on ZSTG_ARRAY_REPORTER_CH(CYTO_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_CHR_STOP on ZSTG_ARRAY_REPORTER_CH(CHR_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_CHR_START on ZSTG_ARRAY_REPORTER_CH(CHR_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_EXON_ID on ZSTG_ARRAY_REPORTER_CH(EXON_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_TRANSCRIPT on ZSTG_ARRAY_REPORTER_CH(TRANSCRIPT_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_GENE_ID on ZSTG_ARRAY_REPORTER_CH(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_NAS_ID on ZSTG_ARRAY_REPORTER_CH(NAS_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_SNP_ID on ZSTG_ARRAY_REPORTER_CH(SNP_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_STRAND on ZSTG_ARRAY_REPORTER_CH(STRAND) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_PROBE_COUN on ZSTG_ARRAY_REPORTER_CH(PROBE_COUNT) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_MANUFACTUR on ZSTG_ARRAY_REPORTER_CH(MANUFACTURER_PSR_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_PHAST_CONS on ZSTG_ARRAY_REPORTER_CH(PHAST_CONSERVATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_TARGET_DES on ZSTG_ARRAY_REPORTER_CH(TARGET_DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_TARGET_ID on ZSTG_ARRAY_REPORTER_CH(TARGET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_SEQUENCE_S on ZSTG_ARRAY_REPORTER_CH(SEQUENCE_SOURCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_SEQUENCE_T on ZSTG_ARRAY_REPORTER_CH(SEQUENCE_TYPE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_DISCRIMINA on ZSTG_ARRAY_REPORTER_CH(DISCRIMINATOR) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_MICROARRAY on ZSTG_ARRAY_REPORTER_CH(MICROARRAY_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_NAME on ZSTG_ARRAY_REPORTER_CH(NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_ARRR_CH_ID on ZSTG_ARRAY_REPORTER_CH(ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
