/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_GENSION_ORIENTATIO_lwr on ZSTG_GENE2ACCESSION(lower(ORIENTATION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_END_POSITO_lwr on ZSTG_GENE2ACCESSION(lower(END_POSITON)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_START_POSI_lwr on ZSTG_GENE2ACCESSION(lower(START_POSITION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_GENOMIC_NU_lwr on ZSTG_GENE2ACCESSION(lower(GENOMIC_NUCLEOTIDE_GI)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_GENOMIC_NU_lwr on ZSTG_GENE2ACCESSION(lower(GENOMIC_NUCLEOTIDE_ACC)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_PROTEIN_GI_lwr on ZSTG_GENE2ACCESSION(lower(PROTEIN_GI)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_PROTEIN_AC_lwr on ZSTG_GENE2ACCESSION(lower(PROTEIN_ACCESSION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_RNA_NUCLEO_lwr on ZSTG_GENE2ACCESSION(lower(RNA_NUCLEOTIDE_GI)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_RNA_NUCLEO_lwr on ZSTG_GENE2ACCESSION(lower(RNA_NUCLEOTIDE_ACC)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENSION_STATUS_lwr on ZSTG_GENE2ACCESSION(lower(STATUS)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
