/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_MOUMRNA_CHROMOSOME on ZSTG_MOUSE_MRNA(CHROMOSOME_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOUMRNA_CHROMOSOME on ZSTG_MOUSE_MRNA(CHROMOSOME_NO) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOUMRNA_TEND on ZSTG_MOUSE_MRNA(TEND) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOUMRNA_TSTART on ZSTG_MOUSE_MRNA(TSTART) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOUMRNA_TNAME on ZSTG_MOUSE_MRNA(TNAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOUMRNA_QNAME on ZSTG_MOUSE_MRNA(QNAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
