
create index ZSTG_GENE_DI_GENE_ID_lwr on ZSTG_GENE_DISEASEONTOLOGY_CGID(lower(GENE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENE_DI_DISEASEONTOL_lwr on ZSTG_GENE_DISEASEONTOLOGY_CGID(lower(DISEASEONTOLOGY_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
