/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_MOLARTS_MSTOP_lwr on ZSTG_MOLECULEPARTS(lower(MSTOP)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_MSTART_lwr on ZSTG_MOLECULEPARTS(lower(MSTART)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_PART_MOLEC_lwr on ZSTG_MOLECULEPARTS(lower(PART_MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_WHOLE_MOLE_lwr on ZSTG_MOLECULEPARTS(lower(WHOLE_MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_MTYPE_lwr on ZSTG_MOLECULEPARTS(lower(MTYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_MOLECULE_I_lwr on ZSTG_MOLECULEPARTS(lower(MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_SOURCE_ID_lwr on ZSTG_MOLECULEPARTS(lower(SOURCE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
