
create index ZSTG_MERPING_ORIEN2CURR on ZSTG_MERGED_SNP_RSIDS_MAPPING(ORIEN2CURRENT) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MERPING_CURRENT_RS on ZSTG_MERGED_SNP_RSIDS_MAPPING(CURRENT_RS_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MERPING_LAST_UPDAT on ZSTG_MERGED_SNP_RSIDS_MAPPING(LAST_UPDATE_TIME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MERPING_CREATE_TIM on ZSTG_MERGED_SNP_RSIDS_MAPPING(CREATE_TIME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MERPING_ORIENTATIO on ZSTG_MERGED_SNP_RSIDS_MAPPING(ORIENTATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MERPING_BUILD_ID on ZSTG_MERGED_SNP_RSIDS_MAPPING(BUILD_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MERPING_NEW_RS_ID on ZSTG_MERGED_SNP_RSIDS_MAPPING(NEW_RS_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MERPING_OLD_RS_ID on ZSTG_MERGED_SNP_RSIDS_MAPPING(OLD_RS_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
