
drop index ZSTG_BIOENES_PATHWAY_NA_LWR;
drop index ZSTG_BIOENES_BC_ID_LWR;
drop index ZSTG_BIOENES_LOCUS_ID_LWR;
drop index ZSTG_BIOENES_PATHWAY_NA;
drop index ZSTG_BIOENES_BC_ID;
drop index ZSTG_BIOENES_LOCUS_ID;
drop index ZSTG_BIOENES_TAXON_ID;

--EXIT;
