
create index ZSTG_MOLARTS_MSTOP on ZSTG_MOLECULEPARTS(MSTOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_MSTART on ZSTG_MOLECULEPARTS(MSTART) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_PART_MOLEC on ZSTG_MOLECULEPARTS(PART_MOLECULE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_WHOLE_MOLE on ZSTG_MOLECULEPARTS(WHOLE_MOLECULE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_MTYPE on ZSTG_MOLECULEPARTS(MTYPE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_MOLECULE_I on ZSTG_MOLECULEPARTS(MOLECULE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_MOLARTS_SOURCE_ID on ZSTG_MOLECULEPARTS(SOURCE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
