
drop index ZSTG_INTENCE_INTERACTIO_LWR;
drop index ZSTG_INTENCE_SOURCE_ID_LWR;
drop index ZSTG_INTENCE_EVIDENCECO_LWR;
drop index ZSTG_INTENCE_INTERACTIO;
drop index ZSTG_INTENCE_SOURCE_ID;
drop index ZSTG_INTENCE_EVIDENCECO;

--EXIT;
