
create index ZSTG_SEQGENE_EVIDENCE_C_lwr on ZSTG_SEQGENE(lower(EVIDENCE_CODE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_TRANSCRIPT_lwr on ZSTG_SEQGENE(lower(TRANSCRIPT)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_GROUP_LABE_lwr on ZSTG_SEQGENE(lower(GROUP_LABEL)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_FEATURE_TY_lwr on ZSTG_SEQGENE(lower(FEATURE_TYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_FEATURE_ID_lwr on ZSTG_SEQGENE(lower(FEATURE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_FEATURE_NA_lwr on ZSTG_SEQGENE(lower(FEATURE_NAME)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_CTG_ORIENT_lwr on ZSTG_SEQGENE(lower(CTG_ORIENT)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_CONTIG_lwr on ZSTG_SEQGENE(lower(CONTIG)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_CHR_ORIENT_lwr on ZSTG_SEQGENE(lower(CHR_ORIENT)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SEQGENE_CHROMOSOME_lwr on ZSTG_SEQGENE(lower(CHROMOSOME)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
