/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_PIDTYPE_XREF on ZSTG_PID_MACROPROCESS_TYPE(XREF) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDTYPE_MACROPROCE on ZSTG_PID_MACROPROCESS_TYPE(MACROPROCESS_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDTYPE_INTERACTIO on ZSTG_PID_MACROPROCESS_TYPE(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
