
drop index ZSTG_EXPRTER_ID;
drop index ZSTG_EXPRTER_MICROARRAY;
drop index ZSTG_EXPRTER_SEQUENCE_T;
drop index ZSTG_EXPRTER_SEQUENCE_S;
drop index ZSTG_EXPRTER_TRANSCRIPT;
drop index ZSTG_EXPRTER_TARGET_DES;
drop index ZSTG_EXPRTER_GENE_ID;
drop index ZSTG_EXPRTER_NAS_ID;
drop index ZSTG_EXPRTER_CHROMOSOME;
drop index ZSTG_EXPRTER_CHR_START;
drop index ZSTG_EXPRTER_CHR_STOP;
drop index ZSTG_EXPRTER_CYTO_START;
drop index ZSTG_EXPRTER_CYTO_STOP;
drop index ZSTG_EXPRTER_ASSEMBLY;
drop index ER_NAME_INDEX;

--EXIT;
