
drop index ZSTG_SEQQSTS_TAX_ID;
drop index ZSTG_SEQQSTS_CHROMOSOME;
drop index ZSTG_SEQQSTS_CHR_START;
drop index ZSTG_SEQQSTS_CHR_STOP;
drop index ZSTG_SEQQSTS_CHR_ORIENT;
drop index ZSTG_SEQQSTS_CONTIG;
drop index ZSTG_SEQQSTS_CTG_START;
drop index ZSTG_SEQQSTS_CTG_STOP;
drop index ZSTG_SEQQSTS_CTG_ORIENT;
drop index ZSTG_SEQQSTS_FEATURE_NA;
drop index ZSTG_SEQQSTS_FEATURE_ID;
drop index ZSTG_SEQQSTS_FEATURE_TY;
drop index ZSTG_SEQQSTS_GROUP_LABE;
drop index ZSTG_SEQQSTS_WEIGHT;

--EXIT;
