/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_EXOAFFY_TOTAL_PROB on ZSTG_EXON_TRANS_AFFY(TOTAL_PROBES) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_STOP_LOCAT on ZSTG_EXON_TRANS_AFFY(STOP_LOCATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_START_LOCA on ZSTG_EXON_TRANS_AFFY(START_LOCATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_STRAND on ZSTG_EXON_TRANS_AFFY(STRAND) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_SEQNAME on ZSTG_EXON_TRANS_AFFY(SEQNAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_PROBE_SET_ on ZSTG_EXON_TRANS_AFFY(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_TRANSCRIPT on ZSTG_EXON_TRANS_AFFY(TRANSCRIPT_CLUSTER_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_CATEGORY on ZSTG_EXON_TRANS_AFFY(CATEGORY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
