
drop index ZSTG_MOUBAND_CHROM;
drop index ZSTG_MOUBAND_CHROMSTART;
drop index ZSTG_MOUBAND_CHROMEND;
drop index ZSTG_MOUBAND_CYTONAME;
drop index ZSTG_MOUBAND_STAIN;
drop index ZSTG_MOUBAND_CHROMOSOME;
drop index ZSTG_MOUBAND_ID;
drop index ZSTG_MOUBAND_CYTOBAND;

--EXIT;
