
drop index ZSTG_AR_CH_BIG_ID_LWR;
drop index ZSTG_AR_CH_BIG_ID;
drop index ZSTG_ARRR_CH_ID;
drop index ZSTG_ARRR_CH_NAME;
drop index ZSTG_ARRR_CH_MICROARRAY;
drop index ZSTG_ARRR_CH_DISCRIMINA;
drop index ZSTG_ARRR_CH_SEQUENCE_T;
drop index ZSTG_ARRR_CH_SEQUENCE_S;
drop index ZSTG_ARRR_CH_TARGET_ID;
drop index ZSTG_ARRR_CH_TARGET_DES;
drop index ZSTG_ARRR_CH_PHAST_CONS;
drop index ZSTG_ARRR_CH_MANUFACTUR;
drop index ZSTG_ARRR_CH_PROBE_COUN;
drop index ZSTG_ARRR_CH_STRAND;
drop index ZSTG_ARRR_CH_SNP_ID;
drop index ZSTG_ARRR_CH_NAS_ID;
drop index ZSTG_ARRR_CH_GENE_ID;
drop index ZSTG_ARRR_CH_TRANSCRIPT;
drop index ZSTG_ARRR_CH_EXON_ID;
drop index ZSTG_ARRR_CH_CHR_START;
drop index ZSTG_ARRR_CH_CHR_STOP;
drop index ZSTG_ARRR_CH_CYTO_START;
drop index ZSTG_ARRR_CH_CYTO_STOP;
drop index ZSTG_ARRR_CH_CHROMOSOME;
drop index ZSTG_ARRR_CH_START_CYTO;
drop index ZSTG_ARRR_CH_END_CYTOID;
drop index ZSTG_ARRR_CH_ASSEMBLY;
drop index ZSTG_ARRR_CH_ORIG_ID;

--EXIT;
