
drop index ZSTG_GENE2UNIGENE_UCLUSTER2;
drop index ZSTG_GENE2UNIGENE_UCLUSTER1;
drop index SYS_C0020835_IDX;
drop index ZSTG_GENGENE_UCLUSTER;
drop index ZSTG_GENGENE_TAXON;
drop index ZSTG_GENGENE_UNIGENE_CL;
drop index ZSTG_GENGENE_GENEID;

--EXIT;
