
drop index ZSTG_INTIONS_INTERACTIO_LWR;
drop index ZSTG_INTIONS_PATHWAY_ID_LWR;
drop index ZSTG_INTIONS_PATHWAY_NA_LWR;
drop index ZSTG_INTIONS_EXTERNAL_P_LWR;
drop index ZSTG_INTIONS_SOURCE_ID_LWR;
drop index ZSTG_INTIONS_SOURCE_NAM_LWR;
drop index ZSTG_INTIONS_INTERACTIO;
drop index ZSTG_INTIONS_PATHWAY_ID;
drop index ZSTG_INTIONS_PATHWAY_NA;
drop index ZSTG_INTIONS_EXTERNAL_P;
drop index ZSTG_INTIONS_SOURCE_ID;
drop index ZSTG_INTIONS_SOURCE_NAM;

--EXIT;
