
create index ZSTG_INTRPRO_GENECHIP_A on ZSTG_INTERPRO(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTRPRO_SCORE on ZSTG_INTERPRO(SCORE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTRPRO_DESCRIPTIO on ZSTG_INTERPRO(DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTRPRO_ACCESSION_ on ZSTG_INTERPRO(ACCESSION_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTRPRO_PROBE_SET_ on ZSTG_INTERPRO(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
