/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_PIDCTST_XREF on ZSTG_PID_INTR_PARTCPANT_ACTST(XREF) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDCTST_ACTIVITY_S on ZSTG_PID_INTR_PARTCPANT_ACTST(ACTIVITY_STATE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDCTST_ORDER_OF_I on ZSTG_PID_INTR_PARTCPANT_ACTST(ORDER_OF_INTERACTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDCTST_INTERACTIO on ZSTG_PID_INTR_PARTCPANT_ACTST(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_PIDCTST_PID_PHYSIC on ZSTG_PID_INTR_PARTCPANT_ACTST(PID_PHYSICALENTITY_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
