package gov.nih.nci.cagrid.cabio.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface CaBIO42GridSvcConstantsBase {
	public static final String SERVICE_NS = "http://cabio.cagrid.nci.nih.gov/CaBIO42GridSvc";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "CaBIO42GridSvcKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "CaBIO42GridSvcResourceProperties");
	public static final QName DOMAINMODEL = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata.dataservice", "DomainModel");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
