
drop index AGENT_ID_NEW_PK;
drop index AGENTENT_BIG_ID_LWR;
drop index AGENTENT_BIG_ID;
drop index AGENTGENT_EVS_ID_LWR;
drop index AGENTGENT_AGENT_COMM_LWR;
drop index AGENTGENT_AGENT_SOUR_LWR;
drop index AGENTGENT_AGENT_NAME_LWR;
drop index AGENTGENT_AGENT_TYPE_LWR;
drop index AGENTGENT_EVS_ID;
drop index AGENTGENT_NSC_NUMBER;
drop index AGENTGENT_CMAP_AGENT;
drop index AGENTGENT_AGENT_COMM;
drop index AGENTGENT_AGENT_SOUR;
drop index AGENTGENT_AGENT_NAME;
drop index AGENTGENT_AGENT_TYPE;

--EXIT;
