/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

drop index AGENTGENT_CHEMICAL_F_LWR;
drop index AGENTGENT_HALF_LIFE_LWR;
drop index AGENTGENT_INDICATION_LWR;
drop index AGENTGENT_IUPAC_NAME_LWR;
drop index AGENTGENT_MECHANISM__LWR;
drop index AGENTGENT_PHARMACOLO_LWR;
drop index AGENTGENT_PROTEIN_BI_LWR;
drop index AGENTGENT_SMILES_COD_LWR;
drop index AGENTGENT_TOXICITY_LWR;
drop index AGENTGENT_DRUGBANK_A_LWR;
drop index AGENTGENT_AGENT_TYPE_LWR;
drop index AGENTGENT_AGENT_NAME_LWR;
drop index AGENTGENT_AGENT_SOUR_LWR;
drop index AGENTGENT_AGENT_COMM_LWR;
drop index AGENTGENT_EVS_ID_LWR;
drop index AGENTGENT_ABSORPTION;
drop index AGENTGENT_BIOTRANSFO;
drop index AGENTGENT_CAS_NUMBER;
drop index AGENTGENT_CHEMICAL_F;
drop index AGENTGENT_HALF_LIFE;
drop index AGENTGENT_INDICATION;
drop index AGENTGENT_IUPAC_NAME;
drop index AGENTGENT_MECHANISM_;
drop index AGENTGENT_MOLECULAR_;
drop index AGENTGENT_PHARMACOLO;
drop index AGENTGENT_PROTEIN_BI;
drop index AGENTGENT_PUBCHEM_CI;
drop index AGENTGENT_PUBCHEM_SI;
drop index AGENTGENT_SMILES_COD;
drop index AGENTGENT_TOXICITY;
drop index AGENTGENT_DRUGBANK_A;
drop index AGENTGENT_AGENT_TYPE;
drop index AGENTGENT_AGENT_NAME;
drop index AGENTGENT_AGENT_SOUR;
drop index AGENTGENT_AGENT_COMM;
drop index AGENTGENT_CMAP_AGENT;
drop index AGENTGENT_NSC_NUMBER;
drop index AGENTGENT_EVS_ID;
drop index AGENTENT_BIG_ID_LWR;
drop index AGENTENT_BIG_ID;
drop index AGENTGENT_ABSORPTION_LWR;
drop index AGENTGENT_CAS_NUMBER_LWR;
drop index AGENTGENT_BIOTRANSFO_LWR;
drop index AGENT_ID_NEW_PK_IDX;

--EXIT;
