
create index AGENTGENT_AGENT_ID on AGENT(AGENT_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_TYPE on AGENT(AGENT_TYPE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_NAME on AGENT(AGENT_NAME) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_SOUR on AGENT(AGENT_SOURCE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_AGENT_COMM on AGENT(AGENT_COMMENT) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_CMAP_AGENT on AGENT(CMAP_AGENT) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_NSC_NUMBER on AGENT(NSC_NUMBER) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index AGENTGENT_EVS_ID on AGENT(EVS_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
