
drop index SYS_C0021039_IDX;
drop index AR_ALIGN_TMP_GENECHIP_A;
drop index AR_ALIGN_TMP_ASSEMBLY;
drop index AR_ALIGN_TMP_TRIM_CHR;
drop index AR_ALIGN_TMP_DIRECTION;
drop index AR_ALIGN_TMP_END_POSITI;
drop index AR_ALIGN_TMP_START_POSI;
drop index AR_ALIGN_TMP_CHROMOSOME;
drop index AR_ALIGN_TMP_PROBE_SET_;

--EXIT;
