
drop index AR_CHROMTION_GENECHIP_A;
drop index AR_CHROMTION_ASSEMBLY;
drop index AR_CHROMTION_TRIM_CHR;
drop index AR_CHROMTION_CYTO_STOP;
drop index AR_CHROMTION_CYTO_START;
drop index AR_CHROMTION_CHROMOSOME;
drop index AR_CHROMTION_CHROMOSOMA;
drop index AR_CHROMTION_PROBE_SET_;

--EXIT;
