/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index AR_CHROM_TMP_CHROMOSOME on AR_CHROMOSOMAL_LOCATION_TMP(CHROMOSOME_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_GENECHIP_A on AR_CHROMOSOMAL_LOCATION_TMP(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_ASSEMBLY on AR_CHROMOSOMAL_LOCATION_TMP(ASSEMBLY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_TRIM_CHR on AR_CHROMOSOMAL_LOCATION_TMP(TRIM_CHR) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_CYTO_STOP on AR_CHROMOSOMAL_LOCATION_TMP(CYTO_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_CYTO_START on AR_CHROMOSOMAL_LOCATION_TMP(CYTO_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_CHROMOSOME on AR_CHROMOSOMAL_LOCATION_TMP(CHROMOSOME_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_CHROMOSOMA on AR_CHROMOSOMAL_LOCATION_TMP(CHROMOSOMAL_LOCATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_CHROM_TMP_PROBE_SET_ on AR_CHROMOSOMAL_LOCATION_TMP(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
