/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index AR_GO_MOTION_GENECHIP_A on AR_GO_MOLECULAR_FUNCTION(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_MOTION_EVIDENCE on AR_GO_MOLECULAR_FUNCTION(EVIDENCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_MOTION_DESCRIPTIO on AR_GO_MOLECULAR_FUNCTION(DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_MOTION_ACCESSION_ on AR_GO_MOLECULAR_FUNCTION(ACCESSION_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index AR_GO_MOTION_PROBE_SET_ on AR_GO_MOLECULAR_FUNCTION(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
