
drop index SYS_C0021055_IDX;
drop index AR_GO_MOTION_GENECHIP_A;
drop index AR_GO_MOTION_EVIDENCE;
drop index AR_GO_MOTION_DESCRIPTIO;
drop index AR_GO_MOTION_ACCESSION_;
drop index AR_GO_MOTION_PROBE_SET_;

--EXIT;
