
drop index ARRAY_RERTER_ID;
drop index ARRAY_REP_BIGID_LWR;
drop index ARRAY_RTER_BIG_ID;
drop index ARRAY_RERTER_MICROARRAY;
drop index ARRAY_RERTER_NAME_LWR;
drop index ARRAY_RERTER_NAME;

--EXIT;
