
drop index SYS_C0021036_IDX;
drop index ARRAY_RERTER_NAME_LWR;
drop index ARRAY_RERTER_MICROARRAY;
drop index ARRAY_RERTER_NAME;
drop index ARRAY_RERTER_ID;
drop index ARRAY_REP_BIGID_LWR;
drop index ARRAY_RTER_BIG_ID;

--EXIT;
