
drop index BIO_PATHWAYS_PATHWAY_DI_LWR;
drop index BIO_PATHWAYS_PATHWAY_NA_LWR;
drop index BIO_PATHWAYS_TAXON;
drop index BIO_PATHWAYS_PATHWAY_DI;
drop index BIO_PATHWAYS_PATHWAY_NA;
drop index BIOPATH_PK;
drop index SYS_IL0000012043C00006$$;

--EXIT;
