
drop index SYS_IL0000012043C00006$$;
drop index BIOPATH_IDX_LWR;
drop index BIO_PATHWAYS_PATHWAY_DI_LWR;
drop index BIO_PATHWAYS_PATHWAY_NA_LWR;
drop index BIO_PATHWAYS_TAXON;
drop index BIO_PATHWAYS_PATHWAY_DI;
drop index BIOPATH_IDX;
drop index BIO_PATHWAYS_PATHWAY_NA;
drop index BIO_PATHWAYS_PATHWAY_ID;

--EXIT;
