
drop index BIO_PATHS_TV_PATHWAY_NA_LWR;
drop index BIO_PATHS_TV_PATHWAY_DI_LWR;
drop index BIO_PATHS_TV_LONG_NAME_LWR;
drop index BIO_PATHS_TV_CURATOR_LWR;
drop index BIO_PATHS_TV_REVIEWER_LWR;
drop index BIO_PATHS_TV_SOURCE_LWR;
drop index BIO_PATHS_TV_PATHWAY_NA;
drop index BIO_PATHS_TV_TAXON;
drop index BIO_PATHS_TV_PATHWAY_DI;
drop index BIO_PATHS_TV_LONG_NAME;
drop index BIO_PATHS_TV_CURATOR;
drop index BIO_PATHS_TV_REVIEWER;
drop index BIO_PATHS_TV_SOURCE;
drop index BIO_PATHS_TV_PID_ID;
drop index BIO_PAT_TV_BIG_ID_LWR;
drop index BIO_PAT_TV_BIG_ID;
drop index BIO_PATHS_TV_PATHWAY_ID;
drop index SYS_IL0000012050C00006$$;
drop index SYS_IL0000012050C00007$$;
drop index PATHWAYS_UNIQ_IDX;

--EXIT;
