
drop index CYTOGENAND_BIG_ID_LWR;
drop index CYTOGENAND_BIG_ID;
drop index SYS_C0021080_IDX;
drop index CYTOGENIBAND_END_CYTOBA;
drop index CYTOGENIBAND_START_CYTO;
drop index CYTOGENIBAND_CHROMOSOME;
drop index CYTOGENIBAND_SNP_ID;
drop index CYTOGENIBAND_NUCLEIC_AC;
drop index CYTOGENIBAND_GENE_ID;
drop index CYTOGENIBAND_CYTOGENIC_;

--EXIT;
