
drop index SYS_C0021081_IDX;
drop index DATABASEENCE_SUMMARY_LWR;
drop index DATABASEENCE_SOURCE_TYP_LWR;
drop index DATABASEENCE_CROSS_REFE_LWR;
drop index DATABASEENCE_SOURCE_NAM_LWR;
drop index DATABASEENCE_TYPE_LWR;
drop index DATABASEENCE_SOURCE_TYP;
drop index DATABASEENCE_CROSS_REFE;
drop index DATABASEENCE_SOURCE_NAM;
drop index DATABASEENCE_TYPE;
drop index DATABASEENCE_ID;
drop index DATABASEENCE_ENGINEERED;
drop index DATABASEENCE_PROTEIN_ID;
drop index DATABASEENCE_NUCLEIC_AC;
drop index DATABASEENCE_SNP_ID;
drop index DATABASEENCE_SUMMARY;
drop index DATABASEENCE_GENE_ID;

--EXIT;
