
drop index BIN$ZCoa+fS8+4PgQLuJIbZfqA==$0;
drop index BIN$ZCoa+fTX+4PgQLuJIbZfqA==$0;
drop index ZSTG_BI_TV_BIG_ID;
drop index ZSTG_AGENT_BIG_ID;
drop index TARGETGET_BIG_ID;
drop index ZSTG_OLOLS_BIG_ID;
drop index ZSTG_OLSES_BIG_ID;
drop index ZSTG_AG_BK_BIG_ID;
drop index ZSTG_TAGET_BIG_ID;
drop index ZSTG_MAKER_BIG_ID;
drop index VOCABULARY_BIG_ID;
drop index TISSUE_ODE_BIG_ID;
drop index TAXONXON_BIG_ID;
drop index PROTOCOCOL_BIG_ID;
drop index ORGANONHIP_BIG_ID;
drop index HISTOPATST_BIG_ID;
drop index DISEASEHIP_BIG_ID;
drop index CHROMOSOME_BIG_ID;
drop index TISSUE_PLE_BIG_ID;
drop index NUCLEICNCE_BIG_ID;
drop index LIBRARYARY_BIG_ID;
drop index HISTOLOODE_BIG_ID;
drop index REL_LOC_BIGID;
drop index AR_REP_CH_BIGID;
drop index BIN$Y0mxqcaWLB7gQLuJIbZjFw==$0;
drop index BIN$Y0mxqcaxLB7gQLuJIbZjFw==$0;
drop index ARRAY_REP_BIGID;
drop index RELATIVE_LOC_BIGID;
drop index BIN$YzQh/gBc3FTgQLuJIbZX8w==$0;
drop index BIN$Y9ggVG71x5jgQLuJIbZulQ==$0;
drop index BIN$Y9ggVG8Qx5jgQLuJIbZulQ==$0;
drop index BIN$Y8W/46ZkQQ/gQLuJIbZYyA==$0;
drop index BIN$YzQh/gB33FTgQLuJIbZX8w==$0;
drop index BIN$Y8W/46Z/QQ/gQLuJIbZYyA==$0;

EXIT;
