
drop index VOCABULARY_BIG_ID;
drop index TISSUE_ODE_BIG_ID;
drop index PROTOCOCOL_BIG_ID;
drop index ORGANONHIP_BIG_ID;
drop index HISTOPATST_BIG_ID;
drop index DISEASEHIP_BIG_ID;
drop index HISTOLOODE_BIG_ID;
drop index TISSUE_PLE_BIG_ID;
drop index LIBRARYARY_BIG_ID;
drop index ARRAY_REP_BIGID;
drop index CHROMOSOME_BIG_ID;
drop index BIN$aksh+O4y1wzgQLuJIbY3Ig==$0;
drop index ZSTG_OLOLS_BIG_ID;
drop index ZSTG_OLSES_BIG_ID;
drop index ZSTG_AG_BK_BIG_ID;
drop index ZSTG_TAGET_BIG_ID;
drop index ZSTG_MAKER_BIG_ID;
drop index ZSTG_TAXON_BIG_ID;
drop index TARGETGET_BIG_ID;
drop index ZSTG_BI_TV_BIG_ID;
drop index ZSTG_AGENT_BIG_ID;
drop index REL_LOC_BIGID;
drop index RELATIVE_LOC_BIGID;
drop index SYS_C004778_IDX;
drop index SYS_C004808_IDX;
drop index BIN$aksh+O5N1wzgQLuJIbY3Ig==$0;
drop index AR_REP_CH_BIGID;

EXIT;
