
drop index EVID_SENT_LWR;
drop index EVID_SENT;
drop index EVIDENCNCE_BIG_ID_LWR;
drop index EVIDENCNCE_BIG_ID;
drop index EVIDENCEENCE_SENTENCE_S_LWR;
drop index EVIDENCEENCE_COMMENTS_LWR;
drop index EVIDENCEENCE_CELLLINE_S_LWR;
drop index SYS_IL0000012164C00007$$;
drop index EVIDENCEENCE_NEGATION_S_LWR;
drop index EVIDENCEENCE_SENTENCE_S;
drop index EVIDENCEENCE_COMMENTS;
drop index EVIDENCEENCE_CELLLINE_S;
drop index EVIDENCEENCE_NEGATION_S;
drop index EVIDENCEENCE_PUBMED_ID;
drop index EVIDENCEENCE_ID;

--EXIT;
