
drop index EXON_REPRTER_MANUFACTUR;
drop index XONREPORTER;
drop index EXON_REPRTER_ID;
drop index EXON_REPRTER_MICROARRAY;
drop index EXON_REPRTER_NAME;
drop index EXON_REPRTER_EXON_ID;
drop index EXON_REPRTER_STRAND;
drop index EXON_REPRTER_PROBE_COUN;
drop index ER_TI_INDEX;
drop index EXON_REPRTER_STRAND_LWR;
drop index EXON_REPRTER_PROBE_COUN_LWR;
drop index EXON_REPRTER_MANUFACTUR_LWR;
drop index EXON_REPRTER_NAME_LWR;
drop index EXON_REON_REPORTER_BIG_ID_LWR;

--EXIT;
