/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index EXPRESSIRTER_NAS_ID on EXPRESSION_REPORTER(NAS_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_GENE_ID on EXPRESSION_REPORTER(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_TARGET_DES on EXPRESSION_REPORTER(TARGET_DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_TRANSCRIPT on EXPRESSION_REPORTER(TRANSCRIPT_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_SEQUENCE_S on EXPRESSION_REPORTER(SEQUENCE_SOURCE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_SEQUENCE_T on EXPRESSION_REPORTER(SEQUENCE_TYPE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_MICROARRAY on EXPRESSION_REPORTER(MICROARRAY_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_NAME on EXPRESSION_REPORTER(NAME) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXPRESSIRTER_ID on EXPRESSION_REPORTER(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
