
drop index GENERICRAY_BIG_ID_LWR;
drop index GENERICRAY_BIG_ID;
drop index SYS_C0021098_IDX;
drop index GENERIC_RRAY_TYPE_LWR;
drop index GENERIC_RRAY_PLATFORM_LWR;
drop index GENERIC_RRAY_ARRAY_NAME_LWR;
drop index GENERIC_RRAY_TYPE;
drop index GENERIC_RRAY_PLATFORM;
drop index GENERIC_RRAY_ARRAY_NAME;
drop index GENERIC_RRAY_ID;

--EXIT;
