
create index GENE_KWE_KW_GENE_ID on GENE_KW(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_KWE_KW_CLUSTER_NU on GENE_KW(CLUSTER_NUMBER) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_KWE_KW_LIBRARY_ID on GENE_KW(LIBRARY_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index GENE_KWE_KW_KEYWORD on GENE_KW(KEYWORD) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
