
drop index GO_RELAHIP_BIG_ID_LWR;
drop index GO_RELAHIP_BIG_ID;
drop index SYS_C0021109_IDX;
drop index GO_RELATSHIP_RELATIONSH_LWR;
drop index GO_RELATSHIP_CHILD_ID;
drop index GO_RELATSHIP_PARENT_ID;
drop index GO_RELATSHIP_RELATIONSH;
drop index GO_RELATSHIP_ID;

--EXIT;
