
drop index SYS_C0021113_IDX;
drop index HOMOLOGOTION_HOMOLOGOUS;
drop index HOMOLOGOTION_SIMILARITY;
drop index HOMOLOGOTION_ID;
drop index HOMOLOGION_BIG_ID;
drop index HOMOLOGION_BIG_ID_LWR;

--EXIT;
