
drop index LOCATIONN_TV_ID;
drop index LOCATIONN_TV_GENE_ID;
drop index LOCATIONN_TV_NUCLEIC_AC;
drop index LOCATIONN_TV_SNP_ID;
drop index LOCATIONN_TV_CHROMOSOME;
drop index LOCATIONN_TV_TRANSCRIPT;
drop index LOCATIONN_TV_EXON_REPOR;
drop index LOCATIONN_TV_MARKER_ID;
drop index LOCATIONN_TV_CYTOBAND_I;

--EXIT;
