/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index MICROARRRRAY_LSID_lwr on MICROARRAY(lower(LSID)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_ACCESSION_lwr on MICROARRAY(lower(ACCESSION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_DESCRIPTIO_lwr on MICROARRAY(lower(DESCRIPTION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_TYPE_lwr on MICROARRAY(lower(TYPE)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_PLATFORM_lwr on MICROARRAY(lower(PLATFORM)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_DBSNP_VERS_lwr on MICROARRAY(lower(DBSNP_VERSION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_GENOME_VER_lwr on MICROARRAY(lower(GENOME_VERSION)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_ARRAY_NAME_lwr on MICROARRAY(lower(ARRAY_NAME)) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index MICROARRRRAY_ANNOTATION_lwr on MICROARRAY(lower(ANNOTATION_VERSION)) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
