
drop index SYS_IL0000012643C00006$$;
drop index NUCLEICNCE_BIG_ID_LWR;
drop index NUCLEICNCE_BIG_ID;
drop index NUCLEIC_ENCE_ACCESSION__LWR;
drop index NUCLEIC_ENCE_VERSION_LWR;
drop index NUCLEIC_ENCE_SEQUENCE_T_LWR;
drop index NUCLEIC_ENCE_DESCRIPTIO_LWR;
drop index NUCLEIC_ENCE_DISCRIMINA_LWR;
drop index NUCLEIC_ENCE_ID;
drop index NUCLEIC_ENCE_ACCESSION_;
drop index NUCLEIC_ENCE_VERSION;
drop index NUCLEIC_ENCE_SEQUENCE_T;
drop index NUCLEIC_ENCE_CLONE_ID;
drop index NUCLEIC_ENCE_LENGTH;
drop index NUCLEIC_ENCE_DESCRIPTIO;
drop index NUCLEIC_ENCE_DISCRIMINA;

--EXIT;
