
drop index PHYSICALTION_EXON_REPOR;
drop index PHYSICALTION_TRANSCRIPT;
drop index PHYSICALTION_GENE_ID;
drop index PHYSICALTION_NUCLEIC_AC;
drop index PHYSICALTION_CHROMOSOMA;
drop index PHYSICALTION_ID;
drop index PHYSICALTION_SNP_ID;
drop index PHYSICALTION_CHROMOSOME;
drop index PHYSICALTION_MARKER_ID;
drop index PHYSICALTION_CYTOBAND_I;

--EXIT;
