
drop index PID_PHYSTITY_ORDER_OF_C;
drop index PID_PHYSTITY_ID;
drop index PID_PHYSTITY_PROT_SUBUN;
drop index PID_PHYSTITY_DISCRIMINA;
drop index PID_PHYSTITY_PROTEIN_EN;
drop index PID_PHYSTITY_PID_PHYSIC;
drop index SYS_C0021157_IDX;
drop index PID_PHYSTITY_DISCRIMINA_LWR;

--EXIT;
