
drop index PID_ENTISION_ID;
drop index PID_ENTISION_ACCESSION;
drop index PID_ENTISION_DATABASE;
drop index PID_ENTISION_PID_PHYSIC;
drop index SYS_C0021149_IDX;
drop index SYS_C0017725_IDX;
drop index PID_ENTISION_ACCESSION_LWR;
drop index PID_ENTISION_DATABASE_LWR;

--EXIT;
