
create index PROVENANANCE_ID on PROVENANCE(ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROVENANANCE_EVIDENCE_C on PROVENANCE(EVIDENCE_CODE) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROVENANANCE_SOURCE_REF on PROVENANCE(SOURCE_REFERENCE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROVENANANCE_IMMEDIATE_ on PROVENANCE(IMMEDIATE_SOURCE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROVENANANCE_SUPPLYING_ on PROVENANCE(SUPPLYING_SOURCE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROVENANANCE_ORIGINAL_S on PROVENANCE(ORIGINAL_SOURCE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROVENANANCE_FULLY_QUAL on PROVENANCE(FULLY_QUALIFIED_CLASS_NAME) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index PROVENANANCE_OBJECT_IDE on PROVENANCE(OBJECT_IDENTIFIER) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
