
drop index RELATIVION_BIG_ID;
drop index RELATIVETION_DISTANCE_LWR;
drop index RELATIVETION_ORIENTATIO_LWR;
drop index RELATIVETION_SNP_ID;
drop index RELATIVETION_DISTANCE;
drop index RELATIVETION_ORIENTATIO;
drop index RELATIVETION_ID;
drop index REL_LOC_BIGID_LWR;

--EXIT;
