
drop index SNP_REPP_REPORTER_BIG_ID_LWR;
drop index SNP_REPORTER_MICROARRAY;
drop index SNP_REPORTER_NAME;
drop index SNP_REPORTER_ID;
drop index SNP_REPORTER_PHAST_CONS_LWR;
drop index SNP_REPORTER_NAME_LWR;
drop index SNPREPBIGID;
drop index SNP_REPORTER_PHAST_CONS;
drop index SNP_REPORTER_SNP_ID;

--EXIT;
