
drop index TRANSCRTER_BIG_ID_LWR;
drop index TRANSCRTER_BIG_ID;
drop index SYS_C0021193_IDX;
drop index TRANSCRIRTER_NAME_LWR;
drop index TRANSCRIRTER_MICROARRAY;
drop index TRANSCRIRTER_NAME;
drop index TRANSCRIRTER_ID;

--EXIT;
