
drop index ZSTG_MOLAMES_MOLECULE_I_LWR;
drop index ZSTG_MOLAMES_SOURCE_ID;
drop index ZSTG_MOLAMES_NAS_ID;
drop index ZSTG_MOLAMES_GENE_ID;
drop index ZSTG_MOLAMES_PROTEIN_ID;
drop index ZSTG_MOLAMES_VALUE;
drop index ZSTG_MOLAMES_LONG_NAME_;
drop index ZSTG_MOLAMES_NAME_TYPE;
drop index ZSTG_MOLAMES_MTYPE;
drop index ZSTG_MOLAMES_MOLECULE_I;
drop index ZSTG_MOLAMES_SOURCE_ID_LWR;
drop index ZSTG_MOLAMES_VALUE_LWR;
drop index ZSTG_MOLAMES_LONG_NAME__LWR;
drop index ZSTG_MOLAMES_NAME_TYPE_LWR;
drop index ZSTG_MOLAMES_MTYPE_LWR;

--EXIT;
