/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_SNPRTER_CYTO_STOP on ZSTG_SNP_REPORTER(CYTO_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_CYTO_START on ZSTG_SNP_REPORTER(CYTO_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_CHR_STOP on ZSTG_SNP_REPORTER(CHR_STOP) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_CHR_START on ZSTG_SNP_REPORTER(CHR_START) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_CHROMOSOME on ZSTG_SNP_REPORTER(CHROMOSOME_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_PHAST_CONS on ZSTG_SNP_REPORTER(PHAST_CONSERVATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_SNP_ID on ZSTG_SNP_REPORTER(SNP_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_MICROARRAY on ZSTG_SNP_REPORTER(MICROARRAY_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_NAME on ZSTG_SNP_REPORTER(NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPRTER_ID on ZSTG_SNP_REPORTER(ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
