
drop index ZSTG_GENE2GO_GO;
drop index ZSTG_GENE2GO_TAX_ID;
drop index ZSTG_GENE2GO_ENTREZ_GEN;
drop index ZSTG_GENE2GO_GO_ID;
drop index ZSTG_GENE2GO_EVIDENCE;
drop index ZSTG_GENE2GO_QUALIFIER;
drop index ZSTG_GENE2GO_GO_TERM;
drop index ZSTG_GENE2GO_PUBMED;
drop index ZSTG_GENE2GO_GO_ID_TRIM;
drop index ZSTG_GENE2GO_CATEGORY;

--EXIT;
