
create index ZSTG_MISCGID_DRUG on ZSTG_MISSING_AGENT_CGID(DRUG) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_MISCGID_MATCHING_C on ZSTG_MISSING_AGENT_CGID(MATCHING_CONCEPT) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_MISCGID_EVS_ID on ZSTG_MISSING_AGENT_CGID(EVS_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
