
create index ZSTG_GENCGID_GENE_ID on ZSTG_GENE_AGENT_EVIDENCE_CGID(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENCGID_AGENT_ID on ZSTG_GENE_AGENT_EVIDENCE_CGID(AGENT_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENCGID_EVIDENCE_I on ZSTG_GENE_AGENT_EVIDENCE_CGID(EVIDENCE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_GENCGID_ROLE_ID on ZSTG_GENE_AGENT_EVIDENCE_CGID(ROLE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
