
drop index ZSTG_RNALENT_PROBE_SET_;
drop index ZSTG_RNALENT_PRIMARY_AC;
drop index ZSTG_RNALENT_REF_SEQ_AC;
drop index ZSTG_RNALENT_GENBANK_AC;
drop index ZSTG_RNALENT_UNIGENE_ID;
drop index ZSTG_RNALENT_ENTREZ_GEN;
drop index ZSTG_RNALENT_GENE_SYMBO;
drop index ZSTG_RNALENT_GENE_NAME;
drop index ZSTG_RNALENT_ENSEMBL_ID;
drop index ZSTG_RNALENT_TIGR_ID;
drop index ZSTG_RNALENT_DESCRIPTIO;
drop index ZSTG_RNALENT_COORDINATE;
drop index ZSTG_RNALENT_CYTOBAND;
drop index ZSTG_RNALENT_CYTOLOC;
drop index ZSTG_RNALENT_CYTO_START;
drop index ZSTG_RNALENT_CYTO_STOP;
drop index ZSTG_RNALENT_CHR_STOP;
drop index ZSTG_RNALENT_CHR_START;
drop index ZSTG_RNALENT_CHROMOSOME;
drop index SYS_IL0000013327C00011$$;

--EXIT;
