
create index ZSTG_PIDENCE_PATHWAY_ID on ZSTG_PID_PATHWAYREFERENCE(PATHWAY_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_PIDENCE_PUBMED_ID on ZSTG_PID_PATHWAYREFERENCE(PUBMED_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
