
create index ZSTG_PIDTYPE_MACROPROCE_lwr on ZSTG_PID_MACROPROCESS_TYPE(lower(MACROPROCESS_NAME)) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_PIDTYPE_XREF_lwr on ZSTG_PID_MACROPROCESS_TYPE(lower(XREF)) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
