
create index ZSTG_INTENCE_INTERACTIO on ZSTG_INTERACTIONEVIDENCE(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTENCE_SOURCE_ID on ZSTG_INTERACTIONEVIDENCE(SOURCE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTENCE_EVIDENCECO on ZSTG_INTERACTIONEVIDENCE(EVIDENCECODE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
