
drop index ZSTG_CLOLONE_TAXON_ID;
drop index ZSTG_CLOLONE_CLONE_ID;
drop index ZSTG_CLOLONE_CLONE_NAME;
drop index ZSTG_CLOLONE_UNIGENE_LI;
drop index ZSTG_CLOLONE_RELATIVE_T;
drop index ZSTG_CLOLONE_LIBRARY_ID;

--EXIT;
