
drop index ZSTG_PONCY_BIG_ID_LWR;
drop index ZSTG_PONCY_BIG_ID;
drop index ZSTG_POPENCY_SNP_PROBES_LWR;
drop index ZSTG_POPENCY_MINOR_ALLE_LWR;
drop index ZSTG_POPENCY_MAJOR_ALLE_LWR;
drop index ZSTG_POPENCY_ETHNICITY_LWR;
drop index ZSTG_POPENCY_TYPE_LWR;
drop index ZSTG_POPENCY_SNP_PROBES;
drop index ZSTG_POPENCY_MINOR_ALLE;
drop index ZSTG_POPENCY_MAJOR_ALLE;
drop index ZSTG_POPENCY_SNP_ID;
drop index ZSTG_POPENCY_HETEROZYGO;
drop index ZSTG_POPENCY_MINOR_FREQ;
drop index ZSTG_POPENCY_MAJOR_FREQ;
drop index ZSTG_POPENCY_ETHNICITY;
drop index ZSTG_POPENCY_ID;
drop index ZSTG_POPENCY_TYPE;

--EXIT;
