
drop index ZSTG_PATTORS_CURATOR_NA_LWR;
drop index ZSTG_PATTORS_SOURCE_ID_LWR;
drop index ZSTG_PATTORS_PATHWAY_ID_LWR;
drop index ZSTG_PATTORS_CURATOR_NA;
drop index ZSTG_PATTORS_SOURCE_ID;
drop index ZSTG_PATTORS_PATHWAY_ID;

--EXIT;
