
create index ZSTG_GENCGID_GENE_ID on ZSTG_GENE_ROLE_CGID(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_GENCGID_ROLE_ID on ZSTG_GENE_ROLE_CGID(ROLE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
