
drop index ZSTG_PATENTS_PATHWAY_ID_LWR;
drop index ZSTG_PATENTS_SOURCE_ID_LWR;
drop index ZSTG_PATENTS_INTERACTIO_LWR;
drop index ZSTG_PATENTS_PATHWAY_ID;
drop index ZSTG_PATENTS_SOURCE_ID;
drop index ZSTG_PATENTS_INTERACTIO;

--EXIT;
