
drop index SYS_IL0000037626C00008$$;
drop index ZSTG_PIDHWAY_REVIEWER_S_LWR;
drop index ZSTG_PIDHWAY_CURATOR_ST_LWR;
drop index ZSTG_PIDHWAY_IS_SUBNET_LWR;
drop index ZSTG_PIDHWAY_LONGNAME_LWR;
drop index ZSTG_PIDHWAY_SHORTNAME_LWR;
drop index ZSTG_PIDHWAY_SOURCE_LWR;
drop index ZSTG_PIDHWAY_REVIEWER_S;
drop index ZSTG_PIDHWAY_CURATOR_ST;
drop index ZSTG_PIDHWAY_IS_SUBNET;
drop index ZSTG_PIDHWAY_LONGNAME;
drop index ZSTG_PIDHWAY_SHORTNAME;
drop index ZSTG_PIDHWAY_SOURCE;
drop index ZSTG_PIDHWAY_PATHWAY_ID;

--EXIT;
