/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_INTERMS_MODIFICATI_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(MODIFICATION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTERMS_AA_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(AA)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTERMS_POSITION_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(POSITION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTERMS_PROTEIN_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(PROTEIN)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTERMS_ROLE_TYPE_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(ROLE_TYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTERMS_MOLECULE_I_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(MOLECULE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTERMS_SOURCE_ID_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(SOURCE_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTERMS_INTERACTIO_lwr on ZSTG_INTERACTIONCOMPPTMTERMS(lower(INTERACTION_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
