
drop index ZSTG_MOLERMS_PROTEIN_LWR;
drop index ZSTG_MOLERMS_MODIFICATI_LWR;
drop index ZSTG_MOLERMS_AA_LWR;
drop index ZSTG_MOLERMS_POSITION_LWR;
drop index ZSTG_MOLERMS_MOLECULE_I_LWR;
drop index ZSTG_MOLERMS_SOURCE_ID_LWR;
drop index ZSTG_MOLERMS_INTERACTIO_LWR;
drop index ZSTG_MOLERMS_MODIFICATI;
drop index ZSTG_MOLERMS_AA;
drop index ZSTG_MOLERMS_POSITION;
drop index ZSTG_MOLERMS_PROTEIN;
drop index ZSTG_MOLERMS_MOLECULE_I;
drop index ZSTG_MOLERMS_SOURCE_ID;
drop index ZSTG_MOLERMS_INTERACTIO;

--EXIT;
