/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_INTIONS_SOURCE_NAM on ZSTG_INTERACTIONS(SOURCE_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTIONS_SOURCE_ID on ZSTG_INTERACTIONS(SOURCE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTIONS_EXTERNAL_P on ZSTG_INTERACTIONS(EXTERNAL_PATHWAY_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTIONS_PATHWAY_NA on ZSTG_INTERACTIONS(PATHWAY_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTIONS_PATHWAY_ID on ZSTG_INTERACTIONS(PATHWAY_IDREF) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTIONS_INTERACTIO on ZSTG_INTERACTIONS(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_INTIONS_INTERACTIO on ZSTG_INTERACTIONS(INTERACTION_TYPE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
