
create index ZSTG_SNPGENE_PROBESET_I on ZSTG_SNP_ASSOCIATED_GENE(PROBESET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPGENE_ACCESSION on ZSTG_SNP_ASSOCIATED_GENE(ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPGENE_ASSOCIATIO on ZSTG_SNP_ASSOCIATED_GENE(ASSOCIATION_POSITION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPGENE_DISTANCE on ZSTG_SNP_ASSOCIATED_GENE(DISTANCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPGENE_UNIGENE_ID on ZSTG_SNP_ASSOCIATED_GENE(UNIGENE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPGENE_ASSOCIATED on ZSTG_SNP_ASSOCIATED_GENE(ASSOCIATED_GENE_SYMBOL) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPGENE_ASSOCIATED on ZSTG_SNP_ASSOCIATED_GENE(ASSOCIATED_GENE_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
