
create index ZSTG_PIDCTST_ACTIVITY_S_lwr on ZSTG_PID_INTR_PARTCPANT_ACTST(lower(ACTIVITY_STATE)) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_PIDCTST_XREF_lwr on ZSTG_PID_INTR_PARTCPANT_ACTST(lower(XREF)) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
