
create index ZSTG_PIDTION_INTERACTIO on ZSTG_PID_INTERACTIONCONDITION(INTERACTION_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_PIDTION_CONDITIONN on ZSTG_PID_INTERACTIONCONDITION(CONDITIONNAME) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_PIDTION_XREF on ZSTG_PID_INTERACTIONCONDITION(XREF) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
