/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_EXOAFFY_PROBESET_T_lwr on ZSTG_EXON_AFFY(lower(PROBESET_TYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_MITOMAP_lwr on ZSTG_EXON_AFFY(lower(MITOMAP)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_RNA_GENE_lwr on ZSTG_EXON_AFFY(lower(RNA_GENE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_MICRO_RNA__lwr on ZSTG_EXON_AFFY(lower(MICRO_RNA_REGISTRY)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_RAT_MRNA_lwr on ZSTG_EXON_AFFY(lower(RAT_MRNA)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_RAT_FL_lwr on ZSTG_EXON_AFFY(lower(RAT_FL)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_MOUSE_MRNA_lwr on ZSTG_EXON_AFFY(lower(MOUSE_MRNA)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_MOUSE_FL_lwr on ZSTG_EXON_AFFY(lower(MOUSE_FL)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_GENSCAN_SU_lwr on ZSTG_EXON_AFFY(lower(GENSCAN_SUBOPT)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_GENSCAN_lwr on ZSTG_EXON_AFFY(lower(GENSCAN)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_GENEID_lwr on ZSTG_EXON_AFFY(lower(GENEID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_TWINSCAN_lwr on ZSTG_EXON_AFFY(lower(TWINSCAN)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_EXONIPHY_lwr on ZSTG_EXON_AFFY(lower(EXONIPHY)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_SGP_GENE_lwr on ZSTG_EXON_AFFY(lower(SGP_GENE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_ENS_GENE_lwr on ZSTG_EXON_AFFY(lower(ENS_GENE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_VEGA_PSEUD_lwr on ZSTG_EXON_AFFY(lower(VEGA_PSEUDO_GENE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_VEGA_GENE_lwr on ZSTG_EXON_AFFY(lower(VEGA_GENE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_EST_lwr on ZSTG_EXON_AFFY(lower(EST)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_MRNA_lwr on ZSTG_EXON_AFFY(lower(MRNA)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_FL_lwr on ZSTG_EXON_AFFY(lower(FL)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_HAS_CDS_lwr on ZSTG_EXON_AFFY(lower(HAS_CDS)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_NO_BOUNDED_lwr on ZSTG_EXON_AFFY(lower(NO_BOUNDED_EVIDENCE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_BOUNDED_lwr on ZSTG_EXON_AFFY(lower(BOUNDED)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_NUM_NONOVE_lwr on ZSTG_EXON_AFFY(lower(NUM_NONOVERLAP_PROBES)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_NUM_CROSS__lwr on ZSTG_EXON_AFFY(lower(NUM_CROSS_HYB_PROBES)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_NUM_INDEPE_lwr on ZSTG_EXON_AFFY(lower(NUM_INDEPENDENT_PROBES)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_CROSSHYB_T_lwr on ZSTG_EXON_AFFY(lower(CROSSHYB_TYPE)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_PSR_ID_lwr on ZSTG_EXON_AFFY(lower(PSR_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_EXON_ID_lwr on ZSTG_EXON_AFFY(lower(EXON_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_TRANSCRIPT_lwr on ZSTG_EXON_AFFY(lower(TRANSCRIPT_CLUSTER_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_PROBE_COUN_lwr on ZSTG_EXON_AFFY(lower(PROBE_COUNT)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_STOP_LOCAT_lwr on ZSTG_EXON_AFFY(lower(STOP_LOCATION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_START_LOCA_lwr on ZSTG_EXON_AFFY(lower(START_LOCATION)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_STRAND_lwr on ZSTG_EXON_AFFY(lower(STRAND)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_SEQNAME_lwr on ZSTG_EXON_AFFY(lower(SEQNAME)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_EXOAFFY_PROBE_SET__lwr on ZSTG_EXON_AFFY(lower(PROBE_SET_ID)) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
