
create index ZSTG_PIDSION_PHYSICALEN on ZSTG_PID_ENTITYACCESSION(PHYSICALENTITY_ID) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_PIDSION_DATABASE on ZSTG_PID_ENTITYACCESSION(DATABASE) PARALLEL NOLOGGING tablespace CABIO_MAP;
create index ZSTG_PIDSION_ACCESSION on ZSTG_PID_ENTITYACCESSION(ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP;

--EXIT;
