/*L
   Copyright SAIC

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cabio/LICENSE.txt for details.
L*/

create index ZSTG_RNA_TMP_ANNOTATION on ZSTG_RNA_PROBESETS_TMP(ANNOTATION_DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_QTL on ZSTG_RNA_PROBESETS_TMP(QTL) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_SGD_ACCESS on ZSTG_RNA_PROBESETS_TMP(SGD_ACCESSION_NUMBER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_RGD_NAME on ZSTG_RNA_PROBESETS_TMP(RGD_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_MGI_NAME on ZSTG_RNA_PROBESETS_TMP(MGI_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_WORMBASE on ZSTG_RNA_PROBESETS_TMP(WORMBASE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_AGI on ZSTG_RNA_PROBESETS_TMP(AGI) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_FLYBASE on ZSTG_RNA_PROBESETS_TMP(FLYBASE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_REFSEQ_TRA on ZSTG_RNA_PROBESETS_TMP(REFSEQ_TRANSCRIPT_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_REFSEQ_PRO on ZSTG_RNA_PROBESETS_TMP(REFSEQ_PROTEIN_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_OMIM on ZSTG_RNA_PROBESETS_TMP(OMIM) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_EC on ZSTG_RNA_PROBESETS_TMP(EC) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_ENTREZ_GEN on ZSTG_RNA_PROBESETS_TMP(ENTREZ_GENE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_ENSEMBL on ZSTG_RNA_PROBESETS_TMP(ENSEMBL) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_UNIGENE_CL on ZSTG_RNA_PROBESETS_TMP(UNIGENE_CLUSTER_TYPE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_CHROMOSOMA on ZSTG_RNA_PROBESETS_TMP(CHROMOSOMAL_LOCATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_GENE_SYMBO on ZSTG_RNA_PROBESETS_TMP(GENE_SYMBOL) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_ALIGNMENTS on ZSTG_RNA_PROBESETS_TMP(ALIGNMENTS) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_GENOME_VER on ZSTG_RNA_PROBESETS_TMP(GENOME_VERSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_UNIGENE_ID on ZSTG_RNA_PROBESETS_TMP(UNIGENE_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_ARCHIVAL_U on ZSTG_RNA_PROBESETS_TMP(ARCHIVAL_UNIGENE_CLUSTER) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_REPRESENTA on ZSTG_RNA_PROBESETS_TMP(REPRESENTATIVE_PUBLIC_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_TARGET_DES on ZSTG_RNA_PROBESETS_TMP(TARGET_DESCRIPTION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_TRANSCRIPT on ZSTG_RNA_PROBESETS_TMP(TRANSCRIPT_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_SEQUENCE_S on ZSTG_RNA_PROBESETS_TMP(SEQUENCE_SOURCE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_SEQUENCE_T on ZSTG_RNA_PROBESETS_TMP(SEQUENCE_TYPE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_ANNOTATION on ZSTG_RNA_PROBESETS_TMP(ANNOTATION_DATE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_SPECIES_SC on ZSTG_RNA_PROBESETS_TMP(SPECIES_SCIENTIFIC_NAME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_GENECHIP_A on ZSTG_RNA_PROBESETS_TMP(GENECHIP_ARRAY) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_RNA_TMP_PROBE_SET_ on ZSTG_RNA_PROBESETS_TMP(PROBE_SET_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
