
drop index CYTOBANAND_BIG_ID_LWR;
drop index CYTOBANAND_BIG_ID;
drop index CYTOUNIQ_IDX;
drop index SYS_C0021079_IDX;
drop index CYTOBANDBAND_NAME_LWR;
drop index CYTOBANDBAND_ID;
drop index CYTOBANDBAND_NAME;
drop index CYTOBANDBAND_PHYSICAL_L;
drop index CYTOBANDBAND_CHROMOSOME;

--EXIT;
