
create index EXON_REPGENE_GENE_ID on EXON_REPORTER_GENE(GENE_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;
create index EXON_REPGENE_EXON_REPOR on EXON_REPORTER_GENE(EXON_REPORTER_ID) PARALLEL NOLOGGING tablespace CABIO_FUT;

--EXIT;
