
create index VOCABULARY_GENERAL_TERM on VOCABULARY(GENERAL_TERM) tablespace CABIO_FUT;
create index VOCABULARY_CORE_TERM on VOCABULARY(CORE_TERM) tablespace CABIO_FUT;
create index VOCABULARY_VOCABULARY_ID on VOCABULARY(VOCABULARY_ID) tablespace CABIO_FUT;

--EXIT;
