
create index ZSTG_SNPMINA_PHAST_CONS on ZSTG_SNP_ILLUMINA(PHAST_CONSERVATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_ID_WITH_MO on ZSTG_SNP_ILLUMINA(ID_WITH_MOUSE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_AMINO_ACID on ZSTG_SNP_ILLUMINA(AMINO_ACID_CHANGE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_CODING_STA on ZSTG_SNP_ILLUMINA(CODING_STATUS) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_LOCATION_R on ZSTG_SNP_ILLUMINA(LOCATION_RELATIVE_TO_GENE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_LOCATION on ZSTG_SNP_ILLUMINA(LOCATION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_GENE_ACCES on ZSTG_SNP_ILLUMINA(GENE_ACCESSION) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_GENE_SYMBO on ZSTG_SNP_ILLUMINA(GENE_SYMBOL) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_GENOME_BUI on ZSTG_SNP_ILLUMINA(GENOME_BUILD) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_COORDINATE on ZSTG_SNP_ILLUMINA(COORDINATE) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_CHROMOSOME on ZSTG_SNP_ILLUMINA(CHROMOSOME) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;
create index ZSTG_SNPMINA_DBSNP_RS_I on ZSTG_SNP_ILLUMINA(DBSNP_RS_ID) PARALLEL NOLOGGING tablespace CABIO_MAP_FUT;

--EXIT;
