#!/bin/sh 
mkpath.pl $CABIO_DATA_DIR/temp/relative_clone 
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr1_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr1_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr2_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr2_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr3_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr3_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr4_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr4_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr5_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr5_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr6_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr6_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr7_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr7_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr8_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr8_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr9_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr9_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr10_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr10_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr11_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr11_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr12_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr12_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr13_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr13_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr14_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr14_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr15_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr15_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr16_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr16_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr17_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr17_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr18_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr18_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr20_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr20_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr21_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr21_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr22_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr22_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chrX_est.txt $CABIO_DATA_DIR/temp/relative_clone/chrX_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chrY_est.txt $CABIO_DATA_DIR/temp/relative_clone/chrY_est_human_stage.dat $1 $2 $3 &
java -classpath ".:../build:../lib/ojdbc14.jar:../lib/commons-net-1.4.0.jar" gov.nih.nci.caBIO.dataload.ParseAllmrna $CABIO_DATA_DIR/relative_clone/human/chr19_est.txt $CABIO_DATA_DIR/temp/relative_clone/chr19_est_human_stage.dat $1 $2 $3 &
wait
