CREATE BITMAP INDEX CABIODEV.LCH_ASSEMBLY ON CABIODEV.LOCATION_CH
(ASSEMBLY)
  TABLESPACE CABIO_FUT
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
LOGGING
LOCAL (  
  PARTITION CHR_PART005
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART005_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART004
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART004_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART1
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART1_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART11
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART11_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART12
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART12_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART14
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART14_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART15
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART15_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART16
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART16_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART17
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART17_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART18
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART18_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART2
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART2_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART3
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART3_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART4
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART4_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART5
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART5_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART6
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART6_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART7
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART7_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART8
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART8_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART9
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART9_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP8    TABLESPACE CABIO_FUT )
)
NOPARALLEL;


CREATE BITMAP INDEX CABIODEV.LCH_ASSEMBLY_LWR ON CABIODEV.LOCATION_CH
(LOWER("ASSEMBLY"))
  TABLESPACE CABIO_FUT
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
LOGGING
LOCAL (  
  PARTITION CHR_PART005
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART005_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART004
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART004_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART1
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART1_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART11
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART11_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART12
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART12_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART14
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART14_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART15
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART15_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART16
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART16_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART17
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART17_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART18
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART18_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART2
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART2_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART3
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART3_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART4
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART4_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART5
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART5_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART6
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART6_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART7
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART7_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART8
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART8_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART9
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART9_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP8    TABLESPACE CABIO_FUT )
)
NOPARALLEL;

CREATE BITMAP INDEX CABIODEV.LCH_DISCRIMINATOR ON CABIODEV.LOCATION_CH
(DISCRIMINATOR)
  TABLESPACE CABIO_FUT
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
LOGGING
LOCAL (  
  PARTITION CHR_PART005
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART005_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART004
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART004_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART1
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART1_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART11
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART11_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART12
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART12_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART14
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART14_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART15
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART15_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART16
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART16_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART17
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART17_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART18
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART18_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART2
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART2_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART3
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART3_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART4
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART4_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART5
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART5_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART6
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART6_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART7
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART7_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART8
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART8_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART9
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART9_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP8    TABLESPACE CABIO_FUT )
)
NOPARALLEL;


CREATE BITMAP INDEX CABIODEV.LCH_DISCRIMINATOR_LWR ON CABIODEV.LOCATION_CH
(LOWER("DISCRIMINATOR"))
  TABLESPACE CABIO_FUT
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
LOGGING
LOCAL (  
  PARTITION CHR_PART005
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART005_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART004
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART004_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART1
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART1_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART11
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART11_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART12
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART12_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART14
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART14_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART15
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART15_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART16
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART16_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART17
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART17_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART18
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART18_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART2
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART2_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART3
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART3_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART4
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART4_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART5
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART5_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART6
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART6_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART7
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART7_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART8
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART8_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART9
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART9_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP8    TABLESPACE CABIO_FUT )
)
NOPARALLEL;


CREATE BITMAP INDEX CABIODEV.LCH_FEATURE_TYPE ON CABIODEV.LOCATION_CH
(FEATURE_TYPE)
  TABLESPACE CABIO_FUT
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
LOGGING
LOCAL (  
  PARTITION CHR_PART005
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART005_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART004
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART004_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART1
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART1_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART11
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART11_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART12
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART12_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART14
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART14_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART15
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART15_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART16
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART16_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART17
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART17_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART18
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART18_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART2
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART2_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART3
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART3_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART4
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART4_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART5
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART5_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART6
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART6_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART7
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART7_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART8
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART8_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART9
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART9_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP8    TABLESPACE CABIO_FUT )
)
NOPARALLEL;

CREATE BITMAP INDEX CABIODEV.LCH_FEATURE_TYPE_LWR ON CABIODEV.LOCATION_CH
(LOWER("FEATURE_TYPE"))
  TABLESPACE CABIO_FUT
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
LOGGING
LOCAL (  
  PARTITION CHR_PART005
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART005_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART005_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART004
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART004_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART004_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART1
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART1_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART1_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART11
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART11_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART11_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART12
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART12_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART12_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART14
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART14_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART14_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART15
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART15_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART15_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART16
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART16_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART16_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART17
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART17_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART17_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART18
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART18_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART18_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART2
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART2_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART2_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART3
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART3_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART3_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART4
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART4_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART4_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART5
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART5_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART5_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART6
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART6_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART6_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART7
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART7_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART7_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART8
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART8_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART8_SP8    TABLESPACE CABIO_FUT ),  
  PARTITION CHR_PART9
    LOGGING
    TABLESPACE CABIO_FUT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
               )
  ( SUBPARTITION CHR_PART9_SP1    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP2    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP3    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP4    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP5    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP6    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP7    TABLESPACE CABIO_FUT,
    SUBPARTITION CHR_PART9_SP8    TABLESPACE CABIO_FUT )
)
NOPARALLEL;
