
CREATE INDEX CABIODEV.LOC_ID ON CABIODEV.LOCATION_CH
(ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_REPORTER_ID ON CABIODEV.LOCATION_CH
(ARRAY_REPORTER_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE BITMAP INDEX CABIODEV.LOC_ASSEMBLY ON CABIODEV.LOCATION_CH
(ASSEMBLY)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE BITMAP INDEX CABIODEV.LOC_ASSEMBLY_LWR ON CABIODEV.LOCATION_CH
(LOWER("ASSEMBLY"))
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_BIG_ID ON CABIODEV.LOCATION_CH
(BIG_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_BIG_ID_LWR ON CABIODEV.LOCATION_CH
(LOWER("BIG_ID"))
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_CHROM_START ON CABIODEV.LOCATION_CH
(CHROMOSOMAL_START_POSITION)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_CHROM_END ON CABIODEV.LOCATION_CH
(CHROMOSOMAL_END_POSITION)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE BITMAP INDEX CABIODEV.LOC_CHROMOSOME_ID ON CABIODEV.LOCATION_CH
(CHROMOSOME_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_CYTOBAND_ID ON CABIODEV.LOCATION_CH
(CYTOBAND_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_CYTOGENE_ID ON CABIODEV.LOCATION_CH
(CYTO_GENE_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_CYTOREPORTER_ID ON CABIODEV.LOCATION_CH
(CYTO_REPORTER_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_CYTOSNP_ID ON CABIODEV.LOCATION_CH
(CYTO_SNP_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE BITMAP INDEX CABIODEV.LOC_DISCRIMINATOR ON CABIODEV.LOCATION_CH
(DISCRIMINATOR)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE BITMAP INDEX CABIODEV.LOC_DISCRIMINATOR_LWR ON CABIODEV.LOCATION_CH
(LOWER("DISCRIMINATOR"))
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_START_CYTO_ID ON CABIODEV.LOCATION_CH
(START_CYTOBAND_LOC_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_END_CYTO_ID ON CABIODEV.LOCATION_CH
(END_CYTOBAND_LOC_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_EXON_REPORTER_ID ON CABIODEV.LOCATION_CH
(EXON_REPORTER_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE BITMAP INDEX CABIODEV.LOC_FEATURE_TYPE ON CABIODEV.LOCATION_CH
(FEATURE_TYPE)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE BITMAP INDEX CABIODEV.LOC_FEATURE_TYPE_LWR ON CABIODEV.LOCATION_CH
(LOWER("FEATURE_TYPE"))
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_GENE_ID ON CABIODEV.LOCATION_CH
(GENE_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_MARKER_ID ON CABIODEV.LOCATION_CH
(MARKER_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_MULTIALIGN_ID ON CABIODEV.LOCATION_CH
(MULTIPLE_ALIGNMENT_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_SEQUENCE_ID ON CABIODEV.LOCATION_CH
(NUCLEIC_ACID_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_SNP_ID ON CABIODEV.LOCATION_CH
(SNP_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_TRANSCRIPT_ID ON CABIODEV.LOCATION_CH
(TRANSCRIPT_ID)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );


CREATE INDEX CABIODEV.LOC_RANGE_QUERY ON CABIODEV.LOCATION_CH
(CHROMOSOME_ID, LOWER("ASSEMBLY"), CHROMOSOMAL_START_POSITION, CHROMOSOMAL_END_POSITION)
NOLOGGING
TABLESPACE CABIO_FUT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE DEFAULT INSTANCES DEFAULT );

