package gov.nih.nci.maservice.service.globus;

import gov.nih.nci.maservice.service.MaGridServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the MaGridServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class MaGridServiceProviderImpl{
	
	MaGridServiceImpl impl;
	
	public MaGridServiceProviderImpl() throws RemoteException {
		impl = new MaGridServiceImpl();
	}
	

    public gov.nih.nci.maservice.stubs.GetGeneBySymbolResponse getGeneBySymbol(gov.nih.nci.maservice.stubs.GetGeneBySymbolRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetGeneBySymbolResponse boxedResult = new gov.nih.nci.maservice.stubs.GetGeneBySymbolResponse();
    boxedResult.setGene(impl.getGeneBySymbol(params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetAgentAssociationResponse getAgentAssociation(gov.nih.nci.maservice.stubs.GetAgentAssociationRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetAgentAssociationResponse boxedResult = new gov.nih.nci.maservice.stubs.GetAgentAssociationResponse();
    boxedResult.setAgentAssociation(impl.getAgentAssociation(params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetBiologicalProcessesResponse getBiologicalProcesses(gov.nih.nci.maservice.stubs.GetBiologicalProcessesRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetBiologicalProcessesResponse boxedResult = new gov.nih.nci.maservice.stubs.GetBiologicalProcessesResponse();
    boxedResult.setBiologicalProcess(impl.getBiologicalProcesses(params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetCellularLocationsResponse getCellularLocations(gov.nih.nci.maservice.stubs.GetCellularLocationsRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetCellularLocationsResponse boxedResult = new gov.nih.nci.maservice.stubs.GetCellularLocationsResponse();
    boxedResult.setCellularComponent(impl.getCellularLocations(params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetDiseaseAssociationsResponse getDiseaseAssociations(gov.nih.nci.maservice.stubs.GetDiseaseAssociationsRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetDiseaseAssociationsResponse boxedResult = new gov.nih.nci.maservice.stubs.GetDiseaseAssociationsResponse();
    boxedResult.setDiseaseAssociation(impl.getDiseaseAssociations(params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetFunctionalAssociationsResponse getFunctionalAssociations(gov.nih.nci.maservice.stubs.GetFunctionalAssociationsRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetFunctionalAssociationsResponse boxedResult = new gov.nih.nci.maservice.stubs.GetFunctionalAssociationsResponse();
    boxedResult.setMolecularFunction(impl.getFunctionalAssociations(params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetStructuralVariationsResponse getStructuralVariations(gov.nih.nci.maservice.stubs.GetStructuralVariationsRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetStructuralVariationsResponse boxedResult = new gov.nih.nci.maservice.stubs.GetStructuralVariationsResponse();
    boxedResult.setSingleNucleotidePolymorphism(impl.getStructuralVariations(params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetHomologousGeneResponse getHomologousGene(gov.nih.nci.maservice.stubs.GetHomologousGeneRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetHomologousGeneResponse boxedResult = new gov.nih.nci.maservice.stubs.GetHomologousGeneResponse();
    boxedResult.setGene(impl.getHomologousGene(params.getOrganism().getOrganism(),params.getGeneSearchCriteria().getGeneSearchCriteria()));
    return boxedResult;
  }

    public gov.nih.nci.maservice.stubs.GetGeneByMicroarrayReporterResponse getGeneByMicroarrayReporter(gov.nih.nci.maservice.stubs.GetGeneByMicroarrayReporterRequest params) throws RemoteException {
    gov.nih.nci.maservice.stubs.GetGeneByMicroarrayReporterResponse boxedResult = new gov.nih.nci.maservice.stubs.GetGeneByMicroarrayReporterResponse();
    boxedResult.setGene(impl.getGeneByMicroarrayReporter(params.getReporterSearchCriteria().getReporterSearchCriteria()));
    return boxedResult;
  }

}
