package gov.nih.nci.maservice.service.globus;

import gov.nih.nci.maservice.service.MaGridServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the MaGridServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class MaGridServiceProviderImpl{
	
	MaGridServiceImpl impl;
	
	public MaGridServiceProviderImpl() throws RemoteException {
		impl = new MaGridServiceImpl();
	}
	

}
