DROP PUBLIC SYNONYM AR_GO_CELLULAR_COMPONENT
/

--
-- AR_GO_CELLULAR_COMPONENT  (Synonym) 
--
--  Dependencies: 
--   AR_GO_CELLULAR_COMPONENT (Table)
--
CREATE PUBLIC SYNONYM AR_GO_CELLULAR_COMPONENT FOR AR_GO_CELLULAR_COMPONENT
/


