DROP PUBLIC SYNONYM AR_REFSEQ_TRANSCRIPTS
/

--
-- AR_REFSEQ_TRANSCRIPTS  (Synonym) 
--
--  Dependencies: 
--   AR_REFSEQ_TRANSCRIPTS (Table)
--
CREATE PUBLIC SYNONYM AR_REFSEQ_TRANSCRIPTS FOR AR_REFSEQ_TRANSCRIPTS
/


