DROP PUBLIC SYNONYM CONCEPT_RELATIONSHIP
/

--
-- CONCEPT_RELATIONSHIP  (Synonym) 
--
--  Dependencies: 
--   CONCEPT_RELATIONSHIP (Table)
--
CREATE PUBLIC SYNONYM CONCEPT_RELATIONSHIP FOR CONCEPT_RELATIONSHIP
/


