DROP PUBLIC SYNONYM HOMOLOGOUS_ASSOCIATION
/

--
-- HOMOLOGOUS_ASSOCIATION  (Synonym) 
--
--  Dependencies: 
--   HOMOLOGOUS_ASSOCIATION (Table)
--
CREATE PUBLIC SYNONYM HOMOLOGOUS_ASSOCIATION FOR HOMOLOGOUS_ASSOCIATION
/


