DROP PUBLIC SYNONYM OBJECT_TO_OBJECT_MAP
/

--
-- OBJECT_TO_OBJECT_MAP  (Synonym) 
--
--  Dependencies: 
--   OBJECT_TO_OBJECT_MAP (Table)
--
CREATE PUBLIC SYNONYM OBJECT_TO_OBJECT_MAP FOR OBJECT_TO_OBJECT_MAP
/


