DROP PUBLIC SYNONYM PID_PHYSICAL_ENTITY
/

--
-- PID_PHYSICAL_ENTITY  (Synonym) 
--
--  Dependencies: 
--   PID_PHYSICAL_ENTITY (Table)
--
CREATE PUBLIC SYNONYM PID_PHYSICAL_ENTITY FOR PID_PHYSICAL_ENTITY
/


