DROP PUBLIC SYNONYM ZSTG_PID_INTR_PARTCPANT_ACTST
/

--
-- ZSTG_PID_INTR_PARTCPANT_ACTST  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_INTR_PARTCPANT_ACTST (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_INTR_PARTCPANT_ACTST FOR ZSTG_PID_INTR_PARTCPANT_ACTST
/


