DROP PUBLIC SYNONYM ZSTG_INTERACTIONREFERENCE
/

--
-- ZSTG_INTERACTIONREFERENCE  (Synonym) 
--
--  Dependencies: 
--   ZSTG_INTERACTIONREFERENCE (Table)
--
CREATE PUBLIC SYNONYM ZSTG_INTERACTIONREFERENCE FOR ZSTG_INTERACTIONREFERENCE
/


