DROP PUBLIC SYNONYM ZSTG_PID_INTR_PARTCPANT_PTM
/

--
-- ZSTG_PID_INTR_PARTCPANT_PTM  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_INTR_PARTCPANT_PTM (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_INTR_PARTCPANT_PTM FOR ZSTG_PID_INTR_PARTCPANT_PTM
/


