DROP PUBLIC SYNONYM ZSTG_PATHWAYREVIEWERS
/

--
-- ZSTG_PATHWAYREVIEWERS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PATHWAYREVIEWERS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PATHWAYREVIEWERS FOR ZSTG_PATHWAYREVIEWERS
/


