DROP PUBLIC SYNONYM ZSTG_STARTSNPARRAYREPCYTOIDS
/

--
-- ZSTG_STARTSNPARRAYREPCYTOIDS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_STARTSNPARRAYREPCYTOIDS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_STARTSNPARRAYREPCYTOIDS FOR ZSTG_STARTSNPARRAYREPCYTOIDS
/


