DROP PUBLIC SYNONYM ZSTG_PID_FMLY_PRTPNT_ACTST
/

--
-- ZSTG_PID_FMLY_PRTPNT_ACTST  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_FMLY_PRTPNT_ACTST (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_FMLY_PRTPNT_ACTST FOR ZSTG_PID_FMLY_PRTPNT_ACTST
/


