DROP PUBLIC SYNONYM ZSTG_INTERACTIONCONDITION
/

--
-- ZSTG_INTERACTIONCONDITION  (Synonym) 
--
--  Dependencies: 
--   ZSTG_INTERACTIONCONDITION (Table)
--
CREATE PUBLIC SYNONYM ZSTG_INTERACTIONCONDITION FOR ZSTG_INTERACTIONCONDITION
/


