DROP PUBLIC SYNONYM ZSTG_PID_ENTITYNAME
/

--
-- ZSTG_PID_ENTITYNAME  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_ENTITYNAME (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_ENTITYNAME FOR ZSTG_PID_ENTITYNAME
/


