DROP PUBLIC SYNONYM ZSTG_RNA_PROBESETS_TMP
/

--
-- ZSTG_RNA_PROBESETS_TMP  (Synonym) 
--
--  Dependencies: 
--   ZSTG_RNA_PROBESETS_TMP (Table)
--
CREATE PUBLIC SYNONYM ZSTG_RNA_PROBESETS_TMP FOR ZSTG_RNA_PROBESETS_TMP
/


