DROP PUBLIC SYNONYM ZSTG_PID_COMPL_PARTICIPANT_LOC
/

--
-- ZSTG_PID_COMPL_PARTICIPANT_LOC  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_COMPL_PARTICIPANT_LOC (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_COMPL_PARTICIPANT_LOC FOR ZSTG_PID_COMPL_PARTICIPANT_LOC
/


