DROP PUBLIC SYNONYM ZSTG_RNA_PROBESETS_TEXT
/

--
-- ZSTG_RNA_PROBESETS_TEXT  (Synonym) 
--
--  Dependencies: 
--   ZSTG_RNA_PROBESETS_TEXT (Table)
--
CREATE PUBLIC SYNONYM ZSTG_RNA_PROBESETS_TEXT FOR ZSTG_RNA_PROBESETS_TEXT
/


