DROP PUBLIC SYNONYM ZSTG_PID_PATHWAY_INTERACTION
/

--
-- ZSTG_PID_PATHWAY_INTERACTION  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_PATHWAY_INTERACTION (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_PATHWAY_INTERACTION FOR ZSTG_PID_PATHWAY_INTERACTION
/


