DROP PUBLIC SYNONYM ZSTG_GENE_IDENTIFIERS
/

--
-- ZSTG_GENE_IDENTIFIERS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_GENE_IDENTIFIERS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_GENE_IDENTIFIERS FOR ZSTG_GENE_IDENTIFIERS
/


