DROP PUBLIC SYNONYM ZSTG_MISSING_AGENT_CGID_EVS
/

--
-- ZSTG_MISSING_AGENT_CGID_EVS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_MISSING_AGENT_CGID_EVS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_MISSING_AGENT_CGID_EVS FOR ZSTG_MISSING_AGENT_CGID_EVS
/


