DROP PUBLIC SYNONYM ZSTG_RNA_PROBESETS
/

--
-- ZSTG_RNA_PROBESETS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_RNA_PROBESETS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_RNA_PROBESETS FOR ZSTG_RNA_PROBESETS
/


