DROP PUBLIC SYNONYM ZSTG_POP_FREQUENCY
/

--
-- ZSTG_POP_FREQUENCY  (Synonym) 
--
--  Dependencies: 
--   ZSTG_POP_FREQUENCY (Table)
--
CREATE PUBLIC SYNONYM ZSTG_POP_FREQUENCY FOR ZSTG_POP_FREQUENCY
/


