DROP PUBLIC SYNONYM ZSTG_PATHWAYCURATORS
/

--
-- ZSTG_PATHWAYCURATORS  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PATHWAYCURATORS (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PATHWAYCURATORS FOR ZSTG_PATHWAYCURATORS
/


