DROP PUBLIC SYNONYM ZSTG_PID_INTERACTION
/

--
-- ZSTG_PID_INTERACTION  (Synonym) 
--
--  Dependencies: 
--   ZSTG_PID_INTERACTION (Table)
--
CREATE PUBLIC SYNONYM ZSTG_PID_INTERACTION FOR ZSTG_PID_INTERACTION
/


